export const CHAT_SUGGESTIONS = [
  'Er hagstæðara að reka rafbíl?',
  'Hvaða rafbílar bjóða upp á 7 sæti?',
  'Hver hentar best fyrir langferðir?',
  'Hvaða rafbíll hentar best fyrir íslenskan vetur?',
  'Hvað kostar að hlaða heima?',
  'Hver er með nútímalegasta tölvuviðmótið?',
  'Hvaða rafbíll verður góður í endursölu?',
  'Hver er öruggastur fyrir börn?',
  'Hver er með stærsta skottið?',
  'Hver er flottur fyrir innanbæjarakstur?',
  'Hversu mikið minnkar drægnin í frosti?',
  'Hver er með mestu veghæðina?',
  'Hver er besti kínverski rafbíllinn?',
  'Hvaða rafbílar geta dregið hjólhýsi?',
  'Skiptir forhitun miklu máli á veturna?',
]
