import { NewCar } from '../types'

const newCars: Array<NewCar> = [
  {
    make: 'Aiways',
    model: 'U5',
    heroImageName: 'aiways-u5',
    price: 6890000,
    sellerURL: 'https://aiwaysaislandi.is',
    acceleration: 7.5,
    capacity: 63,
    range: 410,
    evDatabaseURL: 'https://ev-database.org/car/1678/Aiways-U5',
    drive: 'FWD',
    timeToCharge10T080: 35,
    power: 150,
  },
  {
    make: 'Audi',
    model: 'e-tron GT',
    subModel: 'quattro',
    heroImageName: 'audi-etron-gt',
    price: 16190000,
    sellerURL: 'https://www.audi.is/is/web/is/models/e-tron-gt/e-tron-gt.html',
    acceleration: 4.1,
    capacity: 93.4,
    range: 487,
    evDatabaseURL: 'https://ev-database.org/car/1420/Audi-e-tron-GT-quattro',
    drive: 'AWD',
    power: 390,
    timeToCharge10T080: 21,
  },
  {
    make: 'Audi',
    model: 'e-tron GT RS',
    subModel: 'quattro',
    heroImageName: 'audi-etron-gt',
    price: 21790000,
    sellerURL: 'https://ev-database.org/car/1153/Audi-e-tron-GT-RS',
    acceleration: 3.3,
    capacity: 93.4,
    range: 472,
    evDatabaseURL: 'https://ev-database.org/car/1420/Audi-e-tron-GT-quattro',
    drive: 'AWD',
    power: 475,
    timeToCharge10T080: 17,
  },
  {
    make: 'Audi',
    model: 'Q4 e-tron',
    subModel: '40',
    heroImageName: 'audi-q4-alt',
    price: 9090000,
    sellerURL: 'http://www.audi.is/is/web/is/models/q4-e-tron/q4-e-tron.html',
    acceleration: 8.5,
    capacity: 82,
    range: 522,
    evDatabaseURL: 'https://ev-database.org/car/1490/Audi-Q4-e-tron-40',
    drive: 'RWD',
    timeToCharge10T080: 34,
    power: 150,
  },
  {
    make: 'Audi',
    model: 'Q4 e-tron',
    subModel: '45 quattro',
    heroImageName: 'audi-q4-alt2',
    price: 9890000,
    sellerURL: 'http://www.audi.is/is/web/is/models/q4-e-tron/q4-e-tron.html',
    acceleration: 6.9,
    capacity: 82,
    range: 490,
    evDatabaseURL: 'https://ev-database.org/car/1527/Audi-Q4-e-tron-45-quattro',
    drive: 'AWD',
    timeToCharge10T080: 34,
    power: 195,
  },
  {
    make: 'Audi',
    model: 'Q4 e-tron',
    subModel: '50 quattro',
    heroImageName: 'audi-q4',
    price: 11090000,
    sellerURL: 'http://www.audi.is/is/web/is/models/q4-e-tron/q4-e-tron.html',
    acceleration: 6.2,
    capacity: 82,
    range: 488,
    evDatabaseURL: 'https://ev-database.org/car/1491/Audi-Q4-e-tron-50-quattro',
    drive: 'AWD',
    timeToCharge10T080: 34,
    power: 220,
  },
  {
    make: 'Audi',
    model: 'Q4 Sportback e-tron',
    subModel: '50 quattro',
    heroImageName: 'audi-q4-sportback-alt2',
    price: 11490000,
    sellerURL: 'http://www.audi.is/is/web/is/models/q4-e-tron/q4-e-tron.html',
    acceleration: 6.2,
    capacity: 82,
    range: 488,
    evDatabaseURL:
      'https://ev-database.org/car/1492/Audi-Q4-Sportback-e-tron-50-quattro',
    drive: 'AWD',
    power: 220,
    timeToCharge10T080: 33,
  },
  {
    make: 'Audi',
    model: 'Q8 e-tron',
    subModel: '50 quattro',
    heroImageName: 'audi-q8',
    price: 12790000,
    sellerURL:
      'https://www.audi.is/is/web/is/models/q8-e-tron/q8-e-tron-2023.html',
    acceleration: 6.0,
    capacity: 95,
    range: 453,
    evDatabaseURL: 'https://ev-database.org/car/1769/Audi-Q8-e-tron-50-quattro',
    drive: 'AWD',
    timeToCharge10T080: 30,
    power: 250,
  },
  {
    make: 'Audi',
    model: 'Q8 e-tron',
    subModel: '55 quattro',
    heroImageName: 'audi-q8-alt',
    price: 14290000,
    sellerURL:
      'https://www.audi.is/is/web/is/models/q8-e-tron/q8-e-tron-2023.html',
    acceleration: 5.6,
    capacity: 114,
    range: 532,
    evDatabaseURL: 'https://ev-database.org/car/1770/Audi-Q8-e-tron-55-quattro',
    drive: 'AWD',
    timeToCharge10T080: 31,
    power: 300,
  },
  {
    make: 'Audi',
    model: 'Q8 e-tron Sportback',
    subModel: '50 quattro',
    heroImageName: 'audi-q8-sportback',
    price: 13190000,
    sellerURL:
      'https://www.audi.is/is/web/is/models/q8-e-tron/q8-e-tron-2023.html',
    acceleration: 6.0,
    capacity: 95,
    range: 465,
    evDatabaseURL:
      'https://ev-database.org/car/1771/Audi-Q8-e-tron-Sportback-50-quattro',
    drive: 'AWD',
    timeToCharge10T080: 30,
    power: 250,
  },
  {
    make: 'Audi',
    model: 'Q8 e-tron Sportback',
    subModel: '55 quattro',
    heroImageName: 'audi-q8-sportback-alt',
    price: 14690000,
    sellerURL:
      'https://www.audi.is/is/web/is/models/q8-e-tron/q8-e-tron-2023.html',
    acceleration: 5.6,
    capacity: 114,
    range: 548,
    evDatabaseURL:
      'https://ev-database.org/car/1772/Audi-Q8-e-tron-Sportback-55-quattro',
    drive: 'AWD',
    timeToCharge10T080: 31,
    power: 300,
  },
  {
    make: 'Audi',
    model: 'SQ8 e-tron',
    subModel: '55 quattro',
    heroImageName: 'audi-sq8',
    price: 19000000,
    sellerURL:
      'https://www.audi.is/is/web/is/models/q8-e-tron/q8-e-tron-2023.html',
    acceleration: 4.5,
    capacity: 114,
    range: 494,
    evDatabaseURL: 'https://ev-database.org/car/1773/Audi-SQ8-e-tron',
    drive: 'AWD',
    timeToCharge10T080: 31,
    power: 370,
    expectedDelivery: '2023',
  },
  {
    make: 'Audi',
    model: 'SQ8 e-tron Sportback',
    subModel: '55 quattro',
    heroImageName: 'audi-sq8-sportback',
    price: 19500000,
    sellerURL:
      'https://www.audi.is/is/web/is/models/q8-e-tron/q8-e-tron-2023.html',
    acceleration: 4.5,
    capacity: 114,
    range: 513,
    evDatabaseURL: 'https://ev-database.org/car/1774/Audi-SQ8-e-tron-Sportback',
    drive: 'AWD',
    timeToCharge10T080: 31,
    power: 370,
    expectedDelivery: '2023',
  },
  {
    make: 'BMW',
    model: 'i4',
    subModel: 'eDrive 35',
    heroImageName: 'bmw-i4-alt',
    price: 9000000,
    sellerURL:
      'https://www.bmw.is/is/all-models/bmw-i/i4/2021/bmw-i4-highlights.html',
    acceleration: 6.0,
    capacity: 70.2,
    range: 483,
    evDatabaseURL: 'https://ev-database.org/car/1785/BMW-i4-eDrive35',
    drive: 'RWD',
    power: 210,
    timeToCharge10T080: 31,
    expectedDelivery: '2023',
  },
  {
    make: 'BMW',
    model: 'i4',
    subModel: 'eDrive 40',
    heroImageName: 'bmw-i4',
    price: 9990000,
    sellerURL:
      'https://www.bmw.is/is/all-models/bmw-i/i4/2021/bmw-i4-highlights.html',
    acceleration: 5.7,
    capacity: 83.9,
    range: 590,
    evDatabaseURL: 'https://ev-database.org/car/1252/BMW-i4-eDrive40',
    drive: 'RWD',
    power: 250,
    timeToCharge10T080: 30,
  },
  {
    make: 'BMW',
    model: 'i4',
    subModel: 'M50',
    heroImageName: 'bmw-i4-m50',
    price: 12290000,
    sellerURL:
      'https://www.bmw.is/is/all-models/m-series/i4-m50/2021/bmw-i4-m50-highlights.html',
    acceleration: 3.9,
    capacity: 83.9,
    range: 510,
    evDatabaseURL: 'https://ev-database.org/car/1519/BMW-i4-M50',
    drive: 'AWD',
    power: 400,
    timeToCharge10T080: 30,
  },
  {
    make: 'BMW',
    model: 'i7',
    heroImageName: 'bmw-i7',
    price: 24490000,
    sellerURL:
      'https://www.bmw.is/is/all-models/bmw-i/i7/2022/bmw-i7-sedan-highlights.html',
    acceleration: 4.7,
    capacity: 105,
    range: 625,
    evDatabaseURL: 'https://ev-database.org/car/1676/BMW-i7-xDrive60',
    expectedDelivery: '2023',
    drive: 'AWD',
    power: 400,
    timeToCharge10T080: 35,
  },
  {
    make: 'BMW',
    model: 'iX',
    subModel: 'xDrive 40',
    heroImageName: 'bmw-ix',
    price: 13390000,
    sellerURL: 'https://www.bmw.is/is/all-models/bmw-i/bmw-ix/2021/bmw-ix.html',
    acceleration: 6.1,
    capacity: 75,
    range: 425,
    evDatabaseURL: 'https://ev-database.org/car/1472/BMW-iX-xDrive-40',
    drive: 'AWD',
    power: 240,
    timeToCharge10T080: 30,
  },
  {
    make: 'BMW',
    model: 'iX',
    subModel: 'xDrive 50',
    heroImageName: 'bmw-ix-alt',
    price: 16390000,
    sellerURL: 'https://www.bmw.is/is/all-models/bmw-i/bmw-ix/2021/bmw-ix.html',
    acceleration: 4.6,
    capacity: 110,
    range: 630,
    evDatabaseURL: 'https://ev-database.org/car/1473/BMW-iX-xDrive-50',
    drive: 'AWD',
    power: 385,
    timeToCharge10T080: 31,
  },
  {
    make: 'BMW',
    model: 'iX',
    subModel: 'xDrive M60',
    heroImageName: 'bmw-ix-alt',
    price: 19390000,
    sellerURL: 'https://www.bmw.is/is/all-models/bmw-i/bmw-ix/2021/bmw-ix.html',
    acceleration: 3.8,
    capacity: 110,
    range: 549,
    evDatabaseURL: 'https://ev-database.org/car/1590/BMW-iX-M60',
    drive: 'AWD',
    power: 455,
    timeToCharge10T080: 31,
  },
  {
    make: 'BMW',
    model: 'iX1',
    heroImageName: 'bmw-ix1',
    price: 9990000,
    sellerURL: 'https://www.bmw.is/is/all-models/bmw-i/iX1/2022/bmw-ix1.html',
    acceleration: 5.7,
    capacity: 68,
    range: 438,
    evDatabaseURL: 'https://ev-database.org/car/1701/BMW-iX1-xDrive30',
    expectedDelivery: '2023',
    drive: 'AWD',
    power: 230,
    timeToCharge10T080: 29,
  },
  {
    make: 'BMW',
    model: 'iX3',
    heroImageName: 'bmw-ix3',
    price: 10890000,
    sellerURL:
      'https://www.bmw.is/is/all-models/x-series/iX3/2021/bmw-ix3-highlights.html',
    acceleration: 6.8,
    capacity: 80,
    range: 461,
    evDatabaseURL: 'https://ev-database.org/car/1535/BMW-iX3',
    drive: 'RWD',
    power: 210,
    timeToCharge10T080: 33,
  },
  {
    make: 'BYD',
    model: 'Atto3',
    heroImageName: 'byd-atto3',
    price: 5980000,
    sellerURL: 'https://byd.is/typur/byd-atto-3/',
    acceleration: 7.3,
    capacity: 60,
    range: 420,
    evDatabaseURL: 'https://ev-database.org/car/1782/BYD-ATTO-3',
    drive: 'FWD',
    power: 150,
    timeToCharge10T080: 44,
    expectedDelivery: 'Maí 2023',
  },
  {
    make: 'BYD',
    model: 'Han',
    heroImageName: 'byd-han',
    price: 9980000,
    sellerURL: 'https://byd.is/typur/han-4x4/',
    acceleration: 3.9,
    capacity: 85.4,
    range: 521,
    evDatabaseURL: 'https://ev-database.org/car/1784/BYD-HAN',
    drive: 'AWD',
    power: 380,
    timeToCharge10T080: 43,
    expectedDelivery: 'Maí 2023',
  },
  {
    make: 'BYD',
    model: 'Tang',
    heroImageName: 'byd-tang',
    price: 10068000,
    sellerURL: 'https://byd.is/typur/tang-4x4-sportjeppi/',
    acceleration: 4.6,
    capacity: 86.4,
    range: 400,
    evDatabaseURL: 'https://ev-database.org/car/1783/BYD-TANG',
    drive: 'AWD',
    power: 380,
    timeToCharge10T080: 44,
    expectedDelivery: 'Maí 2023',
  },
  {
    make: 'Citroën',
    model: 'ë-C4',
    heroImageName: 'citroen-ec4',
    price: 5590000,
    sellerURL: 'https://www.citroen.is/bill/citroen-e-c4-rafbill/',
    acceleration: 9.7,
    capacity: 50,
    range: 350,
    evDatabaseURL: 'https://ev-database.org/car/1286/Citroen-e-C4',
    drive: 'FWD',
    timeToCharge10T080: 31,
    power: 100,
  },
  {
    make: 'Fiat',
    model: '500e',
    heroImageName: 'fiat-500e',
    price: 5850000,
    sellerURL: 'https://www.fiat.is/model/500e-la-prima/',
    acceleration: 9.0,
    capacity: 42,
    range: 320,
    evDatabaseURL:
      'https://ev-database.org/car/1285/Fiat-500e-Hatchback-42-kWh',
    drive: 'FWD',
    timeToCharge10T080: 25,
    power: 87,
  },
  {
    make: 'Ford',
    model: 'Mustang Mach-E',
    subModel: 'SR RWD',
    heroImageName: 'ford-mach-e',
    price: 6990000,
    sellerURL: 'https://www.ford.is/is/nyir-bilar/Mustang-Mach-E',
    acceleration: 6.1,
    capacity: 75,
    range: 440,
    evDatabaseURL:
      'https://ev-database.org/car/1242/Ford-Mustang-Mach-E-SR-RWD',
    drive: 'RWD',
    timeToCharge10T080: 38,
    power: 198,
  },
  {
    make: 'Ford',
    model: 'Mustang Mach-E',
    subModel: 'LR RWD',
    heroImageName: 'ford-mach-e-alt',
    price: 8390000,
    sellerURL: 'https://www.ford.is/is/nyir-bilar/Mustang-Mach-E',
    acceleration: 6.2,
    capacity: 98,
    range: 600,
    evDatabaseURL:
      'https://ev-database.org/car/1243/Ford-Mustang-Mach-E-ER-RWD',
    drive: 'RWD',
    power: 216,
    timeToCharge10T080: 43,
  },
  {
    make: 'Ford',
    model: 'Mustang Mach-E',
    subModel: 'SR AWD',
    heroImageName: 'ford-mach-e-alt2',
    price: 8290000,
    sellerURL: 'https://www.ford.is/is/nyir-bilar/Mustang-Mach-E',
    acceleration: 5.6,
    capacity: 75,
    range: 400,
    evDatabaseURL:
      'https://ev-database.org/car/1244/Ford-Mustang-Mach-E-SR-AWD',
    drive: 'AWD',
    timeToCharge10T080: 38,
    power: 198,
  },
  {
    make: 'Ford',
    model: 'Mustang Mach-E',
    subModel: 'LR AWD',
    heroImageName: 'ford-mach-e-alt3',
    price: 8990000,
    sellerURL: 'https://www.ford.is/is/nyir-bilar/Mustang-Mach-E',
    acceleration: 5.1,
    capacity: 98,
    range: 550,
    evDatabaseURL:
      'https://ev-database.org/car/1245/Ford-Mustang-Mach-E-ER-AWD',
    drive: 'AWD',
    power: 258,
    timeToCharge10T080: 43,
  },
  {
    make: 'Ford',
    model: 'Mustang Mach-E',
    subModel: 'GT',
    heroImageName: 'ford-mach-e-alt',
    price: 10490000,
    sellerURL: 'https://www.ford.is/is/nyir-bilar/Mustang-Mach-E',
    acceleration: 3.7,
    capacity: 98,
    range: 490,
    evDatabaseURL: 'https://ev-database.org/car/1672/Ford-Mustang-Mach-E-GT',
    drive: 'AWD',
    power: 358,
    timeToCharge10T080: 43,
  },
  {
    make: 'Honda',
    model: 'e',
    subModel: 'Advance',
    heroImageName: 'honda-e',
    price: 4990000,
    sellerURL: 'https://www.honda.is/voruflokkar/bilar/honda-e/',
    acceleration: 8.3,
    capacity: 32.0,
    range: 220,
    evDatabaseURL: 'https://ev-database.org/car/1233/Honda-e-Advance',
    drive: 'RWD',
    power: 113,
    timeToCharge10T080: 36,
  },
  {
    make: 'Hongqi',
    model: 'E-HS9',
    heroImageName: 'hongqi-ehs9',
    price: 11990000,
    sellerURL: 'https://www.hongqi.is/ehs9.html',
    acceleration: 6.5,
    capacity: 84.0,
    range: 396,
    evDatabaseURL: 'https://ev-database.org/car/1746/Hongqi-E-HS9-84-kWh',
    drive: 'AWD',
    power: 320,
    timeToCharge10T080: 30,
    expectedDelivery: '2023',
  },
  {
    make: 'Hongqi',
    model: 'E-HS9',
    heroImageName: 'hongqi-ehs9-alt',
    price: 13790000,
    sellerURL: 'https://www.hongqi.is/ehs9.html',
    acceleration: 4.9,
    capacity: 99.0,
    range: 465,
    evDatabaseURL: 'https://ev-database.org/car/1747/Hongqi-E-HS9-99-kWh',
    drive: 'AWD',
    power: 405,
    timeToCharge10T080: 36,
    expectedDelivery: '2023',
  },
  {
    make: 'Hongqi',
    model: 'E-HS9',
    heroImageName: 'hongqi-ehs9',
    price: 16990000,
    sellerURL: 'https://www.hongqi.is/ehs9.html',
    acceleration: 5.1,
    capacity: 120.0,
    range: 520,
    drive: 'AWD',
    power: 405,
    timeToCharge10T080: 36,
    expectedDelivery: '2023',
  },
  {
    make: 'Hyundai',
    model: 'IONIQ 5',
    subModel: 'Standard Range 2WD',
    heroImageName: 'hyundai-ioniq-5',
    price: 7490000,
    sellerURL: 'https://www.hyundai.is/nyir/nyr-ioniq-5/yfirlit',
    acceleration: 8.5,
    capacity: 58,
    range: 384,
    evDatabaseURL:
      'https://ev-database.org/car/1476/Hyundai-IONIQ-5-Standard-Range-2WD',
    drive: 'RWD',
    power: 125,
    timeToCharge10T080: 17,
  },
  {
    make: 'Hyundai',
    model: 'IONIQ 5',
    subModel: 'Long Range 2WD',
    heroImageName: 'hyundai-ioniq-5-alt',
    price: 8290000,
    sellerURL: 'https://www.hyundai.is/nyir/nyr-ioniq-5/yfirlit',
    acceleration: 7.4,
    capacity: 77.4,
    range: 507,
    evDatabaseURL:
      'https://ev-database.org/car/1662/Hyundai-IONIQ-5-Long-Range-2WD',
    drive: 'RWD',
    power: 168,
    timeToCharge10T080: 17,
  },
  {
    make: 'Hyundai',
    model: 'IONIQ 5',
    subModel: 'Long Range AWD',
    heroImageName: 'hyundai-ioniq-5-alt2',
    price: 8790000,
    sellerURL: 'https://www.hyundai.is/nyir/nyr-ioniq-5/yfirlit',
    acceleration: 5.2,
    capacity: 77.4,
    range: 481,
    evDatabaseURL:
      'https://ev-database.org/car/1663/Hyundai-IONIQ-5-Long-Range-AWD',
    drive: 'AWD',
    power: 239,
    timeToCharge10T080: 17,
  },
  {
    make: 'Hyundai',
    model: 'IONIQ 6',
    subModel: 'Long Range 2WD',
    heroImageName: 'hyundai-ioniq-6',
    price: 8190000,
    sellerURL: 'https://hyundai.is/ioniq-6/',
    acceleration: 7.4,
    capacity: 77.4,
    range: 614,
    evDatabaseURL:
      'https://ev-database.org/car/1718/Hyundai-IONIQ-6-Long-Range-2WD',
    drive: 'RWD',
    power: 168,
    timeToCharge10T080: 16,
  },
  {
    make: 'Hyundai',
    model: 'IONIQ 6',
    subModel: 'Long Range 4WD',
    heroImageName: 'hyundai-ioniq-6-alt',
    price: 8790000,
    sellerURL: 'https://hyundai.is/ioniq-6/',
    acceleration: 5.1,
    capacity: 77.4,
    range: 583,
    evDatabaseURL:
      'https://ev-database.org/car/1719/Hyundai-IONIQ-6-Long-Range-AWD',
    drive: 'AWD',
    power: 239,
    timeToCharge10T080: 16,
  },
  {
    make: 'Hyundai',
    model: 'Kona Electric',
    subModel: '39 kWh',
    heroImageName: 'kona-39',
    price: 6390000,
    sellerURL: 'https://www.hyundai.is/nyir/kona-ev/yfirlit',
    acceleration: 9.9,
    capacity: 39,
    range: 305,
    evDatabaseURL:
      'https://ev-database.org/car/1422/Hyundai-Kona-Electric-39-kWh',
    drive: 'FWD',
    power: 100,
    timeToCharge10T080: 50,
  },
  {
    make: 'Hyundai',
    model: 'Kona Electric',
    subModel: '64 kWh',
    heroImageName: 'kona',
    price: 7090000,
    sellerURL: 'https://www.hyundai.is/nyir/kona-ev/yfirlit',
    acceleration: 7.6,
    capacity: 64,
    range: 484,
    evDatabaseURL:
      'https://ev-database.org/car/1423/Hyundai-Kona-Electric-64-kWh',
    drive: 'FWD',
    power: 150,
    timeToCharge10T080: 44,
  },
  {
    make: 'Jaguar',
    model: 'I-PACE',
    heroImageName: 'jaguar-i-pace',
    price: 12890000,
    sellerURL: 'https://www.jaguarisland.is/jaguar-range-i-pace',
    acceleration: 4.8,
    capacity: 90,
    range: 470,
    evDatabaseURL: 'https://ev-database.org/car/1812/Jaguar-I-Pace-EV400',
    drive: 'AWD',
    power: 294,
    timeToCharge10T080: 44,
  },
  {
    make: 'Jeep',
    model: 'Avenger',
    heroImageName: 'jeep-avenger',
    price: 5850000,
    sellerURL: 'https://www.jeep.is/model/avenger-my22/',
    acceleration: 9,
    capacity: 54,
    range: 400,
    evDatabaseURL: 'https://ev-database.org/car/1816/Jeep-Avenger-Electric',
    drive: 'FWD',
    power: 115,
    timeToCharge10T080: 44,
    expectedDelivery: 'Sumar 2023',
  },
  {
    make: 'Kia',
    model: 'Niro EV',
    heroImageName: 'kia-niro-2023',
    price: 6990777,
    sellerURL: 'https://www.kia.com/is/nyir-bilar/niro-sg2/',
    acceleration: 7.8,
    capacity: 64.8,
    range: 463,
    evDatabaseURL: 'https://ev-database.org/car/1666/Kia-Niro-EV',
    drive: 'FWD',
    power: 150,
    timeToCharge10T080: 43,
  },
  {
    make: 'Kia',
    model: 'e-Soul',
    subModel: '64 kWh',
    heroImageName: 'e-soul',
    price: 6690777,
    sellerURL: 'https://www.kia.com/is/nyir-bilar/e-soul/upplifdu/',
    acceleration: 7.9,
    capacity: 64,
    range: 452,
    evDatabaseURL: 'https://ev-database.org/car/1288/Kia-e-Soul-64-kWh',
    drive: 'FWD',
    power: 150,
    timeToCharge10T080: 44,
  },
  {
    make: 'Kia',
    model: 'EV6',
    subModel: 'Standard Range RWD',
    heroImageName: 'kia-ev6',
    price: 7990777,
    sellerURL: 'https://www.kia.com/is/nyir-bilar/ev6/upplifdu/',
    acceleration: 8.5,
    capacity: 58,
    range: 400,
    evDatabaseURL:
      'https://ev-database.org/car/1480/Kia-EV6-Standard-Range-2WD',
    drive: 'RWD',
    power: 125,
    timeToCharge10T080: 18,
  },
  {
    make: 'Kia',
    model: 'EV6',
    subModel: 'Long Range RWD',
    heroImageName: 'kia-ev6-alt2',
    price: 8690777,
    sellerURL: 'https://www.kia.com/is/nyir-bilar/ev6/upplifdu/',
    acceleration: 7.3,
    capacity: 77.4,
    range: 528,
    evDatabaseURL: 'https://ev-database.org/car/1481/Kia-EV6-Long-Range-2WD',
    drive: 'RWD',
    power: 168,
    timeToCharge10T080: 18,
  },
  {
    make: 'Kia',
    model: 'EV6',
    subModel: 'Long Range AWD',
    heroImageName: 'kia-ev6-alt3',
    price: 9390777,
    sellerURL: 'https://www.kia.com/is/nyir-bilar/ev6/upplifdu/',
    acceleration: 5.2,
    capacity: 77.4,
    range: 506,
    evDatabaseURL: 'https://ev-database.org/car/1482/Kia-EV6-Long-Range-AWD',
    drive: 'AWD',
    power: 239,
    timeToCharge10T080: 18,
  },
  {
    make: 'Kia',
    model: 'EV6',
    subModel: 'GT',
    heroImageName: 'kia-ev6-alt2',
    price: 11990777,
    sellerURL: 'https://www.kia.com/is/nyir-bilar/ev6/upplifdu/',
    acceleration: 3.5,
    capacity: 77.4,
    range: 406,
    evDatabaseURL: 'https://ev-database.org/car/1471/Kia-EV6-GT',
    drive: 'AWD',
    power: 430,
    timeToCharge10T080: 16,
  },
  {
    make: 'Lexus',
    model: 'RZ',
    subModel: '450e',
    heroImageName: 'lexus-rz',
    price: 14000000,
    sellerURL: 'https://www.lexus.is/new-cars/rz-world-premiere',
    acceleration: 5.6,
    capacity: 75,
    range: 420,
    evDatabaseURL: 'https://ev-database.org/car/1677/Lexus-RZ-450e',
    drive: 'AWD',
    power: 230,
    timeToCharge10T080: 32,
    expectedDelivery: '2023',
  },
  {
    make: 'Lexus',
    model: 'UX',
    subModel: '300e',
    heroImageName: 'lexus-ux-300e',
    price: 9350000,
    sellerURL: 'https://www.lexus.is/car-models/ux-300e/',
    acceleration: 7.5,
    capacity: 50,
    range: 315,
    evDatabaseURL: 'https://ev-database.org/car/1251/Lexus-UX-300e',
    drive: 'FWD',
    power: 150,
    timeToCharge10T080: 69,
  },
  {
    make: 'Maxus',
    model: 'EUNIQ 5',
    heroImageName: 'maxus-euniq-5',
    price: 7290000,
    sellerURL: 'https://maxus.is/typur/euniq5-6-saeta/',
    acceleration: 9.5,
    capacity: 52.5,
    range: 356,
    drive: 'FWD',
    power: 130,
    timeToCharge10T080: 38,
  },
  {
    make: 'Maxus',
    model: 'EUNIQ 6',
    heroImageName: 'maxus-euniq-6',
    price: 7150000,
    sellerURL: 'https://maxus.is/typur/euniq6/',
    acceleration: 9.5,
    capacity: 70,
    range: 354,
    drive: 'FWD',
    power: 130,
    timeToCharge10T080: 38,
  },
  {
    make: 'Maxus',
    model: 'eT90',
    heroImageName: 'maxus-et90',
    price: 9900000,
    sellerURL: 'https://maxus.is/typur/t90-ev-rafknuinn-pallbill',
    acceleration: 10,
    capacity: 88.5,
    range: 330,
    drive: 'RWD',
    power: 150,
    timeToCharge10T080: 45,
    expectedDelivery: 'Byrjun 2023',
  },
  {
    make: 'Mazda',
    model: 'MX-30',
    heroImageName: 'mazda-mx-30',
    price: 4670000,
    sellerURL: 'https://www.mazda.is/is/nyir-bilar/mazda-mx-30',
    acceleration: 9.0,
    capacity: 35.5,
    range: 200,
    evDatabaseURL: 'https://ev-database.org/car/1680/Mazda-MX-30',
    drive: 'FWD',
    power: 105,
    timeToCharge10T080: 39,
  },
  {
    make: 'Mercedes-Benz',
    model: 'EQA SUV',
    subModel: '250',
    heroImageName: 'mercedes-eqa',
    price: 7990000,
    sellerURL:
      'https://www.mercedes-benz.is/passengercars/mercedes-benz-cars/models/eqa/',
    acceleration: 8.9,
    capacity: 66.5,
    range: 426,
    evDatabaseURL: 'https://ev-database.org/car/1147/Mercedes-EQA-250',
    drive: 'FWD',
    power: 140,
    timeToCharge10T080: 35,
  },
  {
    make: 'Mercedes-Benz',
    model: 'EQA SUV',
    subModel: '300 4MATIC',
    heroImageName: 'mercedes-eqa-alt',
    price: 8490000,
    sellerURL:
      'https://www.mercedes-benz.is/passengercars/mercedes-benz-cars/models/eqa/',
    acceleration: 6.9,
    capacity: 66.5,
    range: 423,
    evDatabaseURL: 'https://ev-database.org/car/1495/Mercedes-EQA-300-4MATIC',
    drive: 'AWD',
    power: 168,
    timeToCharge10T080: 35,
  },
  {
    make: 'Mercedes-Benz',
    model: 'EQA SUV',
    subModel: '350 4MATIC',
    heroImageName: 'mercedes-eqa-alt2',
    price: 10790000,
    sellerURL:
      'https://www.mercedes-benz.is/passengercars/mercedes-benz-cars/models/eqa/',
    acceleration: 5.8,
    capacity: 66.5,
    range: 423,
    evDatabaseURL: 'https://ev-database.org/car/1496/Mercedes-EQA-350-4MATIC',
    drive: 'AWD',
    power: 215,
    timeToCharge10T080: 35,
  },
  {
    make: 'Mercedes-Benz',
    model: 'EQB SUV',
    subModel: '250',
    heroImageName: 'mercedes-eqb',
    price: 8490000,
    sellerURL:
      'https://www.mercedes-benz.is/passengercars/mercedes-benz-cars/models/eqb/',
    acceleration: 9.2,
    capacity: 66.5,
    range: 474,
    evDatabaseURL: 'https://ev-database.org/car/1664/Mercedes-EQB-250',
    drive: 'FWD',
    power: 140,
    timeToCharge10T080: 29,
  },
  {
    make: 'Mercedes-Benz',
    model: 'EQB SUV',
    subModel: '300 4MATIC',
    heroImageName: 'mercedes-eqb-alt',
    price: 8990000,
    sellerURL:
      'https://www.mercedes-benz.is/passengercars/mercedes-benz-cars/models/eqb/',
    acceleration: 8.0,
    capacity: 66.5,
    range: 419,
    evDatabaseURL: 'https://ev-database.org/car/1559/Mercedes-EQB-300-4MATIC',
    drive: 'AWD',
    power: 168,
    timeToCharge10T080: 29,
  },
  {
    make: 'Mercedes-Benz',
    model: 'EQB SUV',
    subModel: '350 4MATIC',
    heroImageName: 'mercedes-eqb',
    price: 11290000,
    sellerURL:
      'https://www.mercedes-benz.is/passengercars/mercedes-benz-cars/models/eqb/',
    acceleration: 6.2,
    capacity: 66.5,
    range: 419,
    evDatabaseURL: 'https://ev-database.org/car/1493/Mercedes-EQB-350-4MATIC',
    drive: 'AWD',
    power: 215,
    timeToCharge10T080: 29,
  },
  {
    make: 'Mercedes-Benz',
    model: 'EQC',
    subModel: '400 4MATIC',
    heroImageName: 'eqc',
    price: 10890000,
    sellerURL:
      'https://www.mercedes-benz.is/passengercars/mercedes-benz-cars/models/eqc/',
    acceleration: 5.1,
    capacity: 80,
    range: 417,
    evDatabaseURL: 'https://ev-database.org/car/1135/Mercedes-EQC-400-4MATIC',
    drive: 'AWD',
    power: 300,
    timeToCharge10T080: 35,
  },
  {
    make: 'Mercedes-Benz',
    model: 'EQE',
    subModel: '300',
    heroImageName: 'mercedes-eqe',
    price: 10990000,
    sellerURL:
      'https://mercedes-benz.is/passengercars/mercedes-benz-cars/models/eqe',
    acceleration: 7.2,
    capacity: 90.6,
    range: 630,
    evDatabaseURL: 'https://ev-database.org/car/1713/Mercedes-EQE-300',
    drive: 'RWD',
    power: 180,
    timeToCharge10T080: 33,
  },
  {
    make: 'Mercedes-Benz',
    model: 'EQE',
    subModel: '350 4MATIC',
    heroImageName: 'mercedes-eqe-alt',
    price: 11990000,
    sellerURL:
      'https://mercedes-benz.is/passengercars/mercedes-benz-cars/models/eqe',
    acceleration: 6.3,
    capacity: 90.6,
    range: 587,
    evDatabaseURL: 'https://ev-database.org/car/1538/Mercedes-EQE-350plus',
    drive: 'AWD',
    power: 215,
    timeToCharge10T080: 33,
  },
  {
    make: 'Mercedes-Benz',
    model: 'EQE',
    subModel: 'AMG 43 4MATIC',
    heroImageName: 'mercedes-eqe-amg',
    price: 18290000,
    sellerURL:
      'https://mercedes-benz.is/passengercars/mercedes-benz-cars/models/eqe',
    acceleration: 4.2,
    capacity: 90.6,
    range: 533,
    evDatabaseURL:
      'https://ev-database.org/car/1652/Mercedes-EQE-AMG-43-4MATIC',
    drive: 'AWD',
    power: 350,
    timeToCharge10T080: 33,
  },
  {
    make: 'Mercedes-Benz',
    model: 'EQE',
    subModel: 'AMG 53 4MATIC+',
    heroImageName: 'mercedes-eqe-alt',
    price: 20950000,
    sellerURL:
      'https://mercedes-benz.is/passengercars/mercedes-benz-cars/models/eqe',
    acceleration: 3.3,
    capacity: 90.6,
    range: 518,
    evDatabaseURL:
      'https://ev-database.org/car/1653/Mercedes-EQE-AMG-53-4MATICplus',
    drive: 'AWD',
    power: 505,
    timeToCharge10T080: 33,
  },
  {
    make: 'Mercedes-Benz',
    model: 'EQE SUV',
    subModel: '350 4MATIC',
    heroImageName: 'mercedes-eqe-suv-alt',
    price: 14590000,
    sellerURL:
      'https://www.mercedes-benz.is/passengercars/models/suv/eqe/new.html',
    acceleration: 6.5,
    capacity: 90.6,
    range: 558,
    evDatabaseURL:
      'https://ev-database.org/car/1761/Mercedes-EQE-SUV-350-4MATIC',
    drive: 'AWD',
    power: 215,
    timeToCharge10T080: 28,
  },
  {
    make: 'Mercedes-Benz',
    model: 'EQE SUV',
    subModel: '500 4MATIC',
    heroImageName: 'mercedes-eqe-suv-alt2',
    price: 17690000,
    sellerURL:
      'https://www.mercedes-benz.is/passengercars/models/suv/eqe/new.html',
    acceleration: 5.0,
    capacity: 90.6,
    range: 547,
    evDatabaseURL:
      'https://ev-database.org/car/1762/Mercedes-EQE-SUV-500-4MATIC',
    drive: 'AWD',
    power: 300,
    timeToCharge10T080: 28,
  },
  {
    make: 'Mercedes-Benz',
    model: 'EQE SUV',
    subModel: 'AMG 43 4MATIC',
    heroImageName: 'mercedes-eqe-suv-amg',
    price: 21990000,
    sellerURL:
      'https://www.mercedes-benz.is/passengercars/models/suv/eqe/new.html',
    acceleration: 4.3,
    capacity: 90.6,
    range: 488,
    evDatabaseURL:
      'https://ev-database.org/car/1763/Mercedes-EQE-SUV-AMG-43-4MATIC',
    drive: 'AWD',
    power: 350,
    timeToCharge10T080: 28,
  },
  {
    make: 'Mercedes-Benz',
    model: 'EQE SUV',
    subModel: 'AMG 53 4MATIC',
    heroImageName: 'mercedes-eqe-suv-amg-alt',
    price: 24000000,
    sellerURL:
      'https://www.mercedes-benz.is/passengercars/models/suv/eqe/new.html',
    acceleration: 3.5,
    capacity: 90.6,
    range: 470,
    evDatabaseURL:
      'https://ev-database.org/car/1764/Mercedes-EQE-SUV-AMG-53-4MATICplus',
    drive: 'AWD',
    power: 460,
    timeToCharge10T080: 28,
    expectedDelivery: '2023',
  },
  {
    make: 'Mercedes-Benz',
    model: 'EQS',
    subModel: '450+',
    heroImageName: 'mercedes-eqs',
    price: 18390000,
    sellerURL:
      'https://www.mercedes-benz.is/passengercars/mercedes-benz-cars/models/eqs',
    acceleration: 6.2,
    capacity: 108,
    range: 741,
    evDatabaseURL: 'https://ev-database.org/car/1483/Mercedes-EQS-450plus',
    drive: 'RWD',
    power: 245,
    timeToCharge10T080: 32,
  },
  {
    make: 'Mercedes-Benz',
    model: 'EQS',
    subModel: '450 4MATIC',
    heroImageName: 'mercedes-eqs-alt',
    price: 18890000,
    sellerURL:
      'https://www.mercedes-benz.is/passengercars/mercedes-benz-cars/models/eqs',
    acceleration: 5.6,
    capacity: 108,
    range: 670,
    evDatabaseURL: 'https://ev-database.org/car/1699/Mercedes-EQS-450-4MATIC',
    drive: 'AWD',
    power: 265,
    timeToCharge10T080: 32,
  },
  {
    make: 'Mercedes-Benz',
    model: 'EQS',
    subModel: '580 4MATIC',
    heroImageName: 'mercedes-eqs',
    price: 25190000,
    sellerURL:
      'https://www.mercedes-benz.is/passengercars/mercedes-benz-cars/models/eqs',
    acceleration: 4.3,
    capacity: 108,
    range: 656,
    evDatabaseURL: 'https://ev-database.org/car/1483/Mercedes-EQS-450plus',
    drive: 'AWD',
    power: 385,
    timeToCharge10T080: 32,
  },
  {
    make: 'Mercedes-Benz',
    model: 'EQS',
    subModel: 'AMG 53 4MATIC',
    heroImageName: 'mercedes-eqs-alt',
    price: 29990000,
    sellerURL:
      'https://www.mercedes-benz.is/passengercars/mercedes-benz-cars/models/eqs',
    acceleration: 3.4,
    capacity: 108,
    range: 577,
    evDatabaseURL:
      'https://ev-database.org/car/1537/Mercedes-EQS-AMG-53-4MATICplus',
    drive: 'AWD',
    power: 560,
    timeToCharge10T080: 32,
  },
  {
    make: 'Mercedes-Benz',
    model: 'EQS SUV',
    subModel: '450 4MATIC',
    heroImageName: 'mercedes-eqs-suv',
    price: 20590000,
    sellerURL:
      'https://www.mercedes-benz.is/passengercars/mercedes-benz-cars/models/eqs/suv-x296/pad.html',
    acceleration: 5.8,
    capacity: 108,
    range: 610,
    evDatabaseURL:
      'https://ev-database.org/car/1674/Mercedes-EQS-SUV-450-4MATIC',
    expectedDelivery: '2023',
    drive: 'AWD',
    power: 265,
    timeToCharge10T080: 32,
  },
  {
    make: 'Mercedes-Benz',
    model: 'EQS SUV',
    subModel: '580 4MATIC',
    heroImageName: 'mercedes-eqs-suv',
    price: 26490000,
    sellerURL:
      'https://www.mercedes-benz.is/passengercars/mercedes-benz-cars/models/eqs/suv-x296/pad.html',
    acceleration: 4.7,
    capacity: 108,
    range: 609,
    evDatabaseURL:
      'https://ev-database.org/car/1675/Mercedes-EQS-SUV-580-4MATIC',
    expectedDelivery: '2023',
    drive: 'AWD',
    power: 400,
    timeToCharge10T080: 32,
  },
  {
    make: 'Mercedes-Benz',
    model: 'EQV',
    subModel: '300',
    heroImageName: 'eqv',
    price: 13690000,
    sellerURL:
      'https://www.mercedes-benz.is/passengercars/mercedes-benz-cars/models/v-class/v-class-447/eqv/labeling.module.html',
    acceleration: 12.1,
    capacity: 90,
    range: 363,
    evDatabaseURL: 'https://ev-database.org/car/1240/Mercedes-EQV-300-Long',
    drive: 'FWD',
    power: 150,
    timeToCharge10T080: 47,
  },
  {
    make: 'Mercedes-Benz',
    model: 'eVito',
    subModel: 'Tourer',
    heroImageName: 'mercedes-evito-tourer',
    price: 11590000,
    sellerURL:
      'https://www.mercedes-benz.is/passengercars/mercedes-benz-cars/brochures-pricelists/teaser/_jcr_content/par/productinfotextimage/interactions.attachments.16.eVito_verdlisti.pdf',
    acceleration: 12.1,
    capacity: 90,
    range: 361,
    drive: 'FWD',
    power: 150,
    timeToCharge10T080: 47,
  },
  {
    make: 'MG',
    model: 'Marvel R',
    heroImageName: 'mg-marvel-r',
    price: 7299000,
    sellerURL: 'https://mgmotor.eu/is-IS/model/marvel-r',
    acceleration: 7.9,
    capacity: 70,
    range: 402,
    evDatabaseURL: 'https://ev-database.org/car/1524/MG-Marvel-R',
    drive: 'RWD',
    power: 132,
    timeToCharge10T080: 36,
  },
  {
    make: 'MG',
    model: 'Marvel R',
    subModel: 'Performance',
    heroImageName: 'mg-marvel-r-alt',
    price: 7999000,
    sellerURL: 'https://mgmotor.eu/is-IS/model/marvel-r',
    acceleration: 4.9,
    capacity: 70,
    range: 370,
    evDatabaseURL: 'https://ev-database.org/car/1475/MG-Marvel-R-Performance',
    drive: 'AWD',
    power: 212,
    timeToCharge10T080: 36,
  },
  {
    make: 'MG',
    model: 'MG4',
    subModel: 'Luxury',
    heroImageName: 'mg-mg4',
    price: 5490000,
    sellerURL: 'https://www.mgmotor.eu/is-IS/model/mg4',
    acceleration: 7.9,
    capacity: 64,
    range: 435,
    evDatabaseURL:
      'https://ev-database.org/car/1708/MG-MG4-Electric-Long-Range',
    drive: 'RWD',
    power: 150,
    timeToCharge10T080: 35,
  },
  {
    make: 'MG',
    model: 'MG5',
    subModel: 'Long Range',
    heroImageName: 'mg-mg5',
    price: 6190000,
    sellerURL: 'https://mgmotor.eu/is-IS/model/mg5',
    acceleration: 8.3,
    capacity: 61.1,
    range: 400,
    evDatabaseURL: 'https://ev-database.org/car/1474/MG-MG5-Electric',
    drive: 'FWD',
    power: 115,
    timeToCharge10T080: 42,
  },
  {
    make: 'MG',
    model: 'ZS',
    subModel: 'Standard Range',
    heroImageName: 'mg-zs-ev-2022',
    price: 4990000,
    sellerURL: 'https://mgmotor.eu/is-IS/model/zs-ev',
    acceleration: 8.6,
    capacity: 50.3,
    range: 320,
    evDatabaseURL: 'https://ev-database.org/car/1540/MG-ZS-EV-Standard-Range',
    drive: 'FWD',
    power: 130,
    timeToCharge10T080: 43,
  },
  {
    make: 'MG',
    model: 'ZS',
    subModel: 'Long Range',
    heroImageName: 'mg-zs-ev-2022-alt',
    price: 6490000,
    sellerURL: 'https://mgmotor.eu/is-IS/model/zs-ev',
    acceleration: 8.4,
    capacity: 73,
    range: 440,
    evDatabaseURL: 'https://ev-database.org/car/1541/MG-ZS-EV-Long-Range',
    drive: 'FWD',
    power: 115,
    timeToCharge10T080: 43,
  },
  {
    make: 'Mini Cooper',
    model: 'SE',
    heroImageName: 'mini',
    price: 6290000,
    sellerURL: 'https://www.mini.is/is_IS/home/range/electric.html',
    acceleration: 7.3,
    capacity: 33.0,
    range: 232,
    evDatabaseURL: 'https://ev-database.org/car/1409/Mini-Cooper-SE',
    drive: 'FWD',
    power: 135,
    timeToCharge10T080: 29,
  },
  {
    make: 'Nissan',
    model: 'Ariya',
    subModel: '63 kWh',
    heroImageName: 'nissan-ariya',
    price: 8500000,
    sellerURL: 'https://www.nissan.is/vehicles/new-vehicles/ariya.html',
    acceleration: 7.5,
    capacity: 63,
    range: 403,
    evDatabaseURL: 'https://ev-database.org/car/1301/Nissan-Ariya-63kWh',
    drive: 'FWD',
    power: 160,
    timeToCharge10T080: 31,
    expectedDelivery: '2023',
  },
  {
    make: 'Nissan',
    model: 'Ariya',
    subModel: '87 kWh',
    heroImageName: 'nissan-ariya-alt',
    price: 9500000,
    sellerURL: 'https://www.nissan.is/vehicles/new-vehicles/ariya.html',
    acceleration: 7.6,
    capacity: 87,
    range: 520,
    evDatabaseURL: 'https://ev-database.org/car/1302/Nissan-Ariya-87kWh',
    drive: 'FWD',
    power: 178,
    timeToCharge10T080: 35,
    expectedDelivery: '2023',
  },
  {
    make: 'Nissan',
    model: 'Ariya',
    subModel: 'e-4ORCE',
    heroImageName: 'nissan-ariya',
    price: 10000000,
    sellerURL: 'https://www.nissan.is/vehicles/new-vehicles/ariya.html',
    acceleration: 5.7,
    capacity: 87,
    range: 460,
    evDatabaseURL:
      'https://ev-database.org/car/1304/Nissan-Ariya-e-4ORCE-87kWh',
    expectedDelivery: '2023',
    drive: 'AWD',
    power: 225,
    timeToCharge10T080: 35,
  },
  {
    make: 'Nissan',
    model: 'Leaf',
    heroImageName: 'leaf',
    price: 4990000,
    sellerURL: 'https://www.nissan.is/vehicles/new-vehicles/leaf-vlp-2022.html',
    acceleration: 7.9,
    capacity: 40,
    range: 270,
    evDatabaseURL: 'https://ev-database.org/car/1106/Nissan-Leaf',
    drive: 'FWD',
    power: 110,
    timeToCharge10T080: 40,
  },
  {
    make: 'Nissan',
    model: 'Leaf',
    subModel: 'e+',
    heroImageName: 'leaf-eplus',
    price: 6190000,
    sellerURL: 'https://www.nissan.is/vehicles/new-vehicles/leaf-vlp-2022.html',
    acceleration: 7.3,
    capacity: 62,
    range: 385,
    evDatabaseURL: 'https://ev-database.org/car/1144/Nissan-Leaf-eplus',
    drive: 'FWD',
    power: 160,
    timeToCharge10T080: 35,
  },
  {
    make: 'Opel',
    model: 'Corsa-e',
    heroImageName: 'opel-corsa-e',
    price: 4990000,
    sellerURL:
      'https://www.opelisland.is/cars/corsa-models/corsa-e/yfirsyn.html',
    acceleration: 8.1,
    capacity: 50,
    range: 330,
    evDatabaseURL: 'https://ev-database.org/car/1192/Opel-Corsa-e',
    drive: 'FWD',
    power: 100,
    timeToCharge10T080: 31,
  },
  {
    make: 'Opel',
    model: 'Mokka-e',
    heroImageName: 'opel-mokka-e',
    price: 5390000,
    sellerURL:
      'https://www.opelisland.is/cars/mokka-models/mokka-e/Yfirsyn.html',
    acceleration: 8.5,
    capacity: 50,
    range: 322,
    evDatabaseURL: 'https://ev-database.org/car/1278/Opel-Mokka-e',
    drive: 'FWD',
    power: 100,
    timeToCharge10T080: 31,
  },
  {
    make: 'Peugeot',
    model: 'e-2008',
    heroImageName: 'e-2008',
    price: 5290000,
    sellerURL:
      'https://www.peugeotisland.is/nyir-bilar/velja-bil/glaenyr-peugeot-e-2008/',
    acceleration: 8.5,
    capacity: 50,
    range: 320,
    evDatabaseURL: 'https://ev-database.org/car/1206/Peugeot-e-2008-SUV',
    drive: 'FWD',
    power: 100,
    timeToCharge10T080: 31,
  },
  {
    make: 'Peugeot',
    model: 'e-208',
    heroImageName: 'e-208',
    price: 5190000,
    sellerURL:
      'https://www.peugeotisland.is/nyir-bilar/velja-bil/glaenyr-peugeot-e-208/',
    acceleration: 8.1,
    capacity: 50,
    range: 340,
    evDatabaseURL: 'https://ev-database.org/car/1168/Peugeot-e-208',
    drive: 'FWD',
    power: 100,
    timeToCharge10T080: 31,
  },
  {
    make: 'Peugeot',
    model: 'e-Rifter',
    heroImageName: 'peugeot-e-rifter',
    price: 5990000,
    sellerURL: 'https://www.peugeotisland.is/nyir-bilar/peugeot-e-rifter/',
    acceleration: 11.7,
    capacity: 50,
    range: 282,
    evDatabaseURL:
      'https://ev-database.org/car/1522/Peugeot-e-Rifter-Standard-50-kWh',
    drive: 'FWD',
    power: 100,
    timeToCharge10T080: 26,
  },
  {
    make: 'Peugeot',
    model: 'e-Traveller',
    heroImageName: 'peugeot-e-traveller',
    price: 10190000,
    sellerURL: 'https://www.peugeotisland.is/nyir-bilar/sko/e-traveller/',
    acceleration: 13.3,
    capacity: 75,
    range: 330,
    evDatabaseURL:
      'https://ev-database.org/car/1353/Peugeot-e-Traveller-Standard-75-kWh',
    drive: 'FWD',
    power: 100,
    timeToCharge10T080: 38,
  },
  {
    make: 'Polestar',
    model: '2',
    subModel: 'Standard Range Single Motor',
    heroImageName: 'polestar-2',
    price: 7390000,
    sellerURL: 'https://www.polestar.com/en-is/polestar-2/',
    acceleration: 7.4,
    capacity: 69,
    range: 440,
    evDatabaseURL:
      'https://ev-database.org/car/1654/Polestar-2-Standard-Range-Single-Motor',
    drive: 'FWD',
    power: 170,
    timeToCharge10T080: 33,
  },
  {
    make: 'Polestar',
    model: '2',
    subModel: 'Long Range Single Motor',
    heroImageName: 'polestar-2-alt',
    price: 7590000,
    sellerURL: 'https://www.polestar.com/en-is/polestar-2/',
    acceleration: 7.4,
    capacity: 78,
    range: 542,
    evDatabaseURL:
      'https://ev-database.org/car/1487/Polestar-2-Long-Range-Single-Motor',
    drive: 'FWD',
    power: 170,
    timeToCharge10T080: 32,
  },
  {
    make: 'Polestar',
    model: '2',
    subModel: 'Long Range Dual Motor',
    heroImageName: 'polestar-2-alt2',
    price: 8190000,
    sellerURL: 'https://www.polestar.com/en-is/polestar-2/',
    acceleration: 4.7,
    capacity: 78,
    range: 482,
    evDatabaseURL:
      'https://ev-database.org/car/1488/Polestar-2-Long-Range-Dual-Motor',
    drive: 'AWD',
    power: 300,
    timeToCharge10T080: 32,
  },
  {
    make: 'Polestar',
    model: '2',
    subModel: 'Long Range Dual Motor Performance',
    heroImageName: 'polestar-2',
    price: 9340000,
    sellerURL: 'https://www.polestar.com/en-is/polestar-2/',
    acceleration: 4.4,
    capacity: 78,
    range: 468,
    evDatabaseURL:
      'https://ev-database.org/car/1777/Polestar-2-Long-Range-Performance',
    drive: 'AWD',
    power: 350,
    timeToCharge10T080: 32,
  },
  {
    make: 'Polestar',
    model: '2',
    subModel: '2024 Standard Range Single Motor',
    heroImageName: 'polestar-2-2024',
    price: 8000000,
    sellerURL: 'https://www.polestar.com/en-is/polestar-2/',
    acceleration: 6.4,
    capacity: 69,
    range: 518,
    evDatabaseURL:
      'https://ev-database.org/car/1817/Polestar-2-Standard-Range-Single-Motor',
    drive: 'RWD',
    power: 200,
    timeToCharge10T080: 26,
    expectedDelivery: 'Október 2023',
  },
  {
    make: 'Polestar',
    model: '2',
    subModel: '2024 Long Range Single Motor',
    heroImageName: 'polestar-2-2024-alt',
    price: 8500000,
    sellerURL: 'https://www.polestar.com/en-is/polestar-2/',
    acceleration: 6.2,
    capacity: 82,
    range: 635,
    evDatabaseURL:
      'https://ev-database.org/car/1818/Polestar-2-Long-Range-Single-Motor',
    drive: 'RWD',
    power: 220,
    timeToCharge10T080: 27,
    expectedDelivery: 'Október 2023',
  },
  {
    make: 'Polestar',
    model: '2',
    subModel: '2024 Long Range Dual Motor',
    heroImageName: 'polestar-2-2024-alt2',
    price: 9000000,
    sellerURL: 'https://www.polestar.com/en-is/polestar-2/',
    acceleration: 4.5,
    capacity: 82,
    range: 592,
    evDatabaseURL:
      'https://ev-database.org/car/1819/Polestar-2-Long-Range-Dual-Motor',
    drive: 'AWD',
    power: 310,
    timeToCharge10T080: 27,
    expectedDelivery: 'Október 2023',
  },
  {
    make: 'Polestar',
    model: '2',
    subModel: '2024 Long Range Dual Motor Performance',
    heroImageName: 'polestar-2-2024',
    price: 10000000,
    sellerURL: 'https://www.polestar.com/en-is/polestar-2/',
    acceleration: 4.2,
    capacity: 82,
    range: 592,
    evDatabaseURL:
      'https://ev-database.org/car/1820/Polestar-2-Long-Range-Performance',
    drive: 'AWD',
    power: 350,
    timeToCharge10T080: 27,
    expectedDelivery: 'Október 2023',
  },
  {
    make: 'Polestar',
    model: '3',
    heroImageName: 'polestar-3',
    price: 13890000,
    sellerURL: 'https://www.polestar.com/en-is/polestar-3/',
    acceleration: 5,
    capacity: 111,
    range: 610,
    evDatabaseURL:
      'https://ev-database.org/car/1758/Polestar-3-Long-Range-Dual-motor',
    drive: 'AWD',
    power: 360,
    timeToCharge10T080: 32,
    expectedDelivery: 'Byrjun 2024',
  },
  {
    make: 'Polestar',
    model: '3',
    subModel: 'Performance',
    heroImageName: 'polestar-3-alt',
    price: 14890000,
    sellerURL: 'https://www.polestar.com/en-is/polestar-3/',
    acceleration: 4.7,
    capacity: 111,
    range: 560,
    evDatabaseURL:
      'https://ev-database.org/car/1759/Polestar-3-Long-Range-Performance',
    drive: 'AWD',
    power: 380,
    timeToCharge10T080: 32,
    expectedDelivery: 'Byrjun 2024',
  },
  {
    make: 'Porsche',
    model: 'Taycan',
    heroImageName: 'porsche-taycan',
    price: 13990000,
    sellerURL: 'https://dealer.porsche.com/is/island/is-IS/nyir-bilar/Taycan',
    acceleration: 5.4,
    capacity: 79.2,
    range: 431,
    evDatabaseURL: 'https://ev-database.org/car/1393/Porsche-Taycan',
    drive: 'RWD',
    power: 300,
    timeToCharge10T080: 21,
  },
  {
    make: 'Porsche',
    model: 'Taycan',
    subModel: '4S',
    heroImageName: 'taycan-4s',
    price: 17990000,
    sellerURL: 'https://dealer.porsche.com/is/island/is-IS/nyir-bilar/Taycan',
    acceleration: 4.0,
    capacity: 79.2,
    range: 407,
    evDatabaseURL: 'https://ev-database.org/car/1237/Porsche-Taycan-4S',
    drive: 'AWD',
    power: 390,
    timeToCharge10T080: 21,
  },
  {
    make: 'Porsche',
    model: 'Taycan',
    subModel: 'Sport Turismo',
    heroImageName: 'porsche-taycan-sport-turismo-alt',
    price: 13990000,
    sellerURL: 'https://dealer.porsche.com/is/island/is-IS/nyir-bilar/Taycan',
    acceleration: 5.4,
    capacity: 79.2,
    range: 433,
    evDatabaseURL:
      'https://ev-database.org/car/1621/Porsche-Taycan-Sport-Turismo',
    drive: 'RWD',
    power: 300,
    timeToCharge10T080: 19,
  },
  {
    make: 'Porsche',
    model: 'Taycan',
    subModel: '4 Cross Turismo',
    heroImageName: 'porsche-taycan-cross-turismo',
    price: 15990000,
    sellerURL: 'https://dealer.porsche.com/is/island/is-IS/nyir-bilar/Taycan',
    acceleration: 5.1,
    capacity: 93.4,
    range: 456,
    evDatabaseURL:
      'https://ev-database.org/car/1186/Porsche-Taycan-4-Cross-Turismo',
    drive: 'AWD',
    power: 420,
    timeToCharge10T080: 19,
  },
  {
    make: 'Porsche',
    model: 'Taycan',
    subModel: '4S Cross Turismo',
    heroImageName: 'porsche-taycan-cross-turismo',
    price: 18990000,
    sellerURL: 'https://dealer.porsche.com/is/island/is-IS/nyir-bilar/Taycan',
    acceleration: 4.1,
    capacity: 93.4,
    range: 452,
    evDatabaseURL:
      'https://ev-database.org/car/1437/Porsche-Taycan-4S-Cross-Turismo',
    drive: 'AWD',
    power: 420,
    timeToCharge10T080: 19,
  },
  {
    make: 'Renault',
    model: 'Megane E-Tech',
    subModel: 'EV40',
    heroImageName: 'renault-megane-etech',
    price: 5990000,
    sellerURL:
      'https://www.renault.is/cars/megane-e-tech/megane-e-tech-electric.html',
    acceleration: 10.0,
    capacity: 40,
    range: 300,
    evDatabaseURL:
      'https://ev-database.org/car/1536/Renault-Megane-E-Tech-EV40-130hp',
    drive: 'FWD',
    power: 96,
    timeToCharge10T080: 29,
  },
  {
    make: 'Renault',
    model: 'Megane E-Tech',
    subModel: 'EV60',
    heroImageName: 'renault-megane-etech-alt',
    price: 7490000,
    sellerURL:
      'https://www.renault.is/cars/megane-e-tech/megane-e-tech-electric.html',
    acceleration: 7.4,
    capacity: 60,
    range: 470,
    evDatabaseURL:
      'https://ev-database.org/car/1521/Renault-Megane-E-Tech-EV60-220hp',
    drive: 'FWD',
    power: 160,
    timeToCharge10T080: 29,
  },
  {
    make: 'Renault',
    model: 'Zoe',
    subModel: 'R110',
    heroImageName: 'zoe-r110',
    price: 5990000,
    sellerURL: 'https://www.renault.is/cars/zoe/yfirlit.html',
    acceleration: 11.4,
    capacity: 52,
    range: 395,
    evDatabaseURL: 'https://ev-database.org/car/1164/Renault-Zoe-ZE50-R110',
    drive: 'FWD',
    power: 80,
    timeToCharge10T080: 56,
  },
  {
    make: 'Renault',
    model: 'Zoe',
    subModel: 'R135',
    heroImageName: 'zoe-r135',
    price: 6590000,
    sellerURL: 'https://www.renault.is/cars/zoe/yfirlit.html',
    acceleration: 9.5,
    capacity: 52,
    range: 385,
    evDatabaseURL: 'https://ev-database.org/car/1205/Renault-Zoe-ZE50-R135',
    drive: 'FWD',
    power: 100,
    timeToCharge10T080: 56,
  },
  {
    make: 'Skoda',
    model: 'Enyaq',
    subModel: 'iV 60',
    heroImageName: 'skoda-enyaq',
    price: 7290000,
    sellerURL: 'https://www.skoda.is/models/enyaq/enyaq',
    acceleration: 8.7,
    capacity: 58,
    range: 412,
    evDatabaseURL: 'https://ev-database.org/car/1279/Skoda-Enyaq-iV-60',
    drive: 'RWD',
    power: 132,
    timeToCharge10T080: 33,
  },
  {
    make: 'Skoda',
    model: 'Enyaq',
    subModel: 'iV 80',
    heroImageName: 'skoda-enyaq-alt',
    price: 8090000,
    sellerURL: 'https://www.skoda.is/models/enyaq/enyaq',
    acceleration: 8.5,
    capacity: 77,
    range: 544,
    evDatabaseURL: 'https://ev-database.org/car/1280/Skoda-Enyaq-iV-80',
    drive: 'RWD',
    power: 150,
    timeToCharge10T080: 33,
  },
  {
    make: 'Skoda',
    model: 'Enyaq',
    subModel: 'iV 80 Coupé',
    heroImageName: 'skoda-enyaq-coupe',
    price: 8690000,
    sellerURL: 'https://www.skoda.is/models/enyaq/enyaq',
    acceleration: 8.5,
    capacity: 77,
    range: 536,
    evDatabaseURL: 'https://ev-database.org/car/1629/Skoda-Enyaq-Coupe-iV-80',
    drive: 'RWD',
    power: 150,
    timeToCharge10T080: 33,
  },
  {
    make: 'Skoda',
    model: 'Enyaq',
    subModel: 'iV 80X',
    heroImageName: 'skoda-enyaq-alt3',
    price: 8390000,
    sellerURL: 'https://www.skoda.is/models/enyaq/enyaq',
    acceleration: 6.9,
    capacity: 77,
    range: 506,
    evDatabaseURL: 'https://ev-database.org/car/1281/Skoda-Enyaq-iV-80X',
    drive: 'AWD',
    power: 195,
    timeToCharge10T080: 34,
  },
  {
    make: 'Skoda',
    model: 'Enyaq',
    subModel: 'iV 80X Coupé',
    heroImageName: 'skoda-enyaq-coupe-alt',
    price: 9090000,
    sellerURL: 'https://www.skoda.is/models/enyaq/enyaq',
    acceleration: 6.9,
    capacity: 77,
    range: 496,
    evDatabaseURL: 'https://ev-database.org/car/1630/Skoda-Enyaq-Coupe-iV-80x',
    drive: 'AWD',
    power: 195,
    timeToCharge10T080: 34,
  },
  {
    make: 'Skoda',
    model: 'Enyaq',
    subModel: 'RS',
    heroImageName: 'skoda-enyaq',
    price: 9290000,
    sellerURL: 'https://www.skoda.is/models/enyaq/enyaq',
    acceleration: 6.2,
    capacity: 77,
    range: 460,
    evDatabaseURL: 'https://ev-database.org/car/1282/Skoda-Enyaq-iV-RS',
    drive: 'AWD',
    power: 220,
    timeToCharge10T080: 30,
  },
  {
    make: 'Skoda',
    model: 'Enyaq',
    subModel: 'Coupé RS',
    heroImageName: 'skoda-enyaq-coupe-rs',
    price: 9590000,
    sellerURL: 'https://www.skoda.is/models/enyaq/enyaq',
    acceleration: 6.5,
    capacity: 77,
    range: 505,
    evDatabaseURL: 'https://ev-database.org/car/1631/Skoda-Enyaq-Coupe-iV-RS',
    drive: 'AWD',
    power: 220,
    timeToCharge10T080: 30,
  },
  {
    make: 'Smart',
    model: '#1',
    heroImageName: 'smart-one',
    price: 6600000,
    sellerURL: 'https://smart.askja.is/',
    acceleration: 6.0,
    capacity: 66,
    range: 440,
    evDatabaseURL: 'https://ev-database.org/car/1667/Smart-1',
    drive: 'RWD',
    power: 200,
    timeToCharge10T080: 27,
    expectedDelivery: 'Júní 2023',
  },
  {
    make: 'Smart',
    model: '#1',
    subModel: 'Brabus',
    heroImageName: 'smart-one-brabus',
    price: 8000000,
    sellerURL: 'https://smart.askja.is/',
    acceleration: 3.9,
    capacity: 66,
    range: 400,
    evDatabaseURL: 'https://ev-database.org/car/1748/Smart-1-Brabus',
    drive: 'AWD',
    power: 315,
    timeToCharge10T080: 27,
    expectedDelivery: 'September 2023',
  },
  {
    make: 'Subaru',
    model: 'Solterra',
    heroImageName: 'subaru-solterra',
    price: 7590000,
    sellerURL: 'https://www.subaru.is/solterra.html',
    acceleration: 7.7,
    capacity: 71.4,
    range: 415,
    evDatabaseURL: 'https://ev-database.org/car/1567/Subaru-Solterra-AWD',
    drive: 'AWD',
    power: 160,
    timeToCharge10T080: 32,
  },
  {
    make: 'Tesla',
    model: 'Model 3',
    heroImageName: 'tesla-model-3-alt',
    price: 6119988,
    sellerURL: 'https://www.tesla.com/is_IS/model3/design',
    acceleration: 6.1,
    capacity: 60.0,
    range: 491,
    evDatabaseURL: 'https://ev-database.org/car/1555/Tesla-Model-3',
    drive: 'RWD',
    power: 239,
    timeToCharge10T080: 27,
  },
  {
    make: 'Tesla',
    model: 'Model 3',
    subModel: 'Long Range',
    heroImageName: 'tesla-model-3',
    price: 7359988,
    sellerURL: 'https://www.tesla.com/is_IS/model3/design',
    acceleration: 4.4,
    capacity: 82,
    range: 602,
    evDatabaseURL:
      'https://ev-database.org/car/1591/Tesla-Model-3-Long-Range-Dual-Motor',
    drive: 'AWD',
    power: 324,
    timeToCharge10T080: 30,
  },
  {
    make: 'Tesla',
    model: 'Model 3',
    subModel: 'Performance',
    heroImageName: 'tesla-model-3-performance',
    price: 7531418,
    sellerURL: 'https://www.tesla.com/is_IS/model3/design',
    acceleration: 3.3,
    capacity: 82,
    range: 547,
    evDatabaseURL: 'https://ev-database.org/car/1620/Tesla-Model-3-Performance',
    drive: 'AWD',
    power: 413,
    timeToCharge10T080: 30,
  },
  {
    make: 'Tesla',
    model: 'Model S',
    subModel: 'Long Range',
    heroImageName: 'tesla-model-s',
    price: 15299379,
    sellerURL: 'https://www.tesla.com/is_IS/models/design',
    acceleration: 3.2,
    capacity: 100,
    range: 634,
    evDatabaseURL: 'https://ev-database.org/car/1404/Tesla-Model-S-Long-Range',
    drive: 'AWD',
    power: 500,
    timeToCharge10T080: 23,
  },
  {
    make: 'Tesla',
    model: 'Model S',
    subModel: 'Plaid',
    heroImageName: 'tesla-model-s-alt',
    price: 18948699,
    sellerURL: 'https://www.tesla.com/is_IS/models/design',
    acceleration: 2.1,
    capacity: 100,
    range: 600,
    evDatabaseURL: 'https://ev-database.org/car/1405/Tesla-Model-S-Plaid',
    drive: 'AWD',
    power: 760,
    timeToCharge10T080: 30,
  },
  {
    make: 'Tesla',
    model: 'Model Y',
    subModel: 'Standard Range',
    heroImageName: 'tesla-model-y',
    price: 6491988,
    sellerURL: 'https://www.tesla.com/is_is/modely/design',
    acceleration: 6.9,
    capacity: 60,
    range: 455,
    evDatabaseURL: 'https://ev-database.org/car/1743/Tesla-Model-Y',
    drive: 'RWD',
    power: 239,
    timeToCharge10T080: 30,
  },
  {
    make: 'Tesla',
    model: 'Model Y',
    subModel: 'Long Range',
    heroImageName: 'tesla-model-y-alt',
    price: 7731988,
    sellerURL: 'https://www.tesla.com/is_is/modely/design',
    acceleration: 5.0,
    capacity: 82,
    range: 533,
    evDatabaseURL:
      'https://ev-database.org/car/1619/Tesla-Model-Y-Long-Range-Dual-Motor',
    drive: 'AWD',
    power: 324,
    timeToCharge10T080: 30,
  },
  {
    make: 'Tesla',
    model: 'Model Y',
    subModel: 'Performance',
    heroImageName: 'tesla-model-y-performance',
    price: 8477228,
    sellerURL: 'https://www.tesla.com/is_is/modely/design',
    acceleration: 3.7,
    capacity: 82,
    range: 514,
    evDatabaseURL: 'https://ev-database.org/car/1183/Tesla-Model-Y-Performance',
    drive: 'AWD',
    power: 413,
    timeToCharge10T080: 30,
  },
  {
    make: 'Tesla',
    model: 'Model X',
    subModel: 'Long Range',
    heroImageName: 'tesla-model-x',
    price: 16551779,
    sellerURL: 'https://www.tesla.com/is_IS/modelx/design',
    acceleration: 3.9,
    capacity: 100,
    range: 576,
    evDatabaseURL: 'https://ev-database.org/car/1407/Tesla-Model-X-Long-Range',
    drive: 'AWD',
    power: 500,
    timeToCharge10T080: 23,
  },
  {
    make: 'Tesla',
    model: 'Model X',
    subModel: 'Plaid',
    heroImageName: 'tesla-model-x-alt',
    price: 19444699,
    sellerURL: 'https://www.tesla.com/is_IS/modelx/design',
    acceleration: 2.6,
    capacity: 100,
    range: 528,
    evDatabaseURL: 'https://ev-database.org/car/1408/Tesla-Model-X-Plaid',
    drive: 'AWD',
    power: 760,
    timeToCharge10T080: 30,
  },
  {
    make: 'Toyota',
    model: 'bZ4X',
    heroImageName: 'toyota-bz4x',
    price: 7350000,
    sellerURL: 'https://www.toyota.is/new-cars/bz4x',
    acceleration: 8.4,
    capacity: 71.4,
    range: 450,
    evDatabaseURL: 'https://ev-database.org/car/1564/Toyota-bZ4X-FWD',
    drive: 'FWD',
    power: 150,
    timeToCharge10T080: 32,
  },
  {
    make: 'Toyota',
    model: 'bZ4X',
    heroImageName: 'toyota-bz4x-alt',
    price: 7860000,
    sellerURL: 'https://www.toyota.is/new-cars/bz4x',
    acceleration: 7.7,
    capacity: 71.4,
    range: 400,
    evDatabaseURL: 'https://ev-database.org/car/1565/Toyota-bZ4X-AWD',
    drive: 'AWD',
    power: 160,
    timeToCharge10T080: 32,
  },
  {
    make: 'Toyota',
    model: 'Proace City Verso',
    heroImageName: 'toyota-proace-city-verso',
    price: 7250000,
    sellerURL: 'https://www.toyota.is/new-cars/proace-city-verso-ev',
    acceleration: 11.2,
    capacity: 50,
    range: 284,
    evDatabaseURL:
      'https://ev-database.org/car/1779/Toyota-Proace-City-Verso-Electric-L1-50-kWh',
    drive: 'FWD',
    power: 100,
    timeToCharge10T080: 26,
  },
  {
    make: 'Toyota',
    model: 'Proace Verso',
    heroImageName: 'toyota-proace-verso',
    price: 9490000,
    sellerURL: 'https://www.toyota.is/new-cars/proace-verso-ev',
    acceleration: 13.1,
    capacity: 75,
    range: 330,
    evDatabaseURL:
      'https://ev-database.org/car/1514/Toyota-PROACE-Verso-M-75-kWh',
    drive: 'FWD',
    power: 100,
    timeToCharge10T080: 36,
  },
  {
    make: 'Volkswagen',
    model: 'e-Up!',
    heroImageName: 'e-up',
    price: 4290000,
    sellerURL: 'https://www.volkswagen.is/is/bilar/e-up.html',
    acceleration: 11.9,
    capacity: 36.8,
    range: 260,
    evDatabaseURL: 'https://ev-database.org/car/1189/Volkswagen-e-Up',
    drive: 'FWD',
    power: 61,
    timeToCharge10T080: 48,
  },
  {
    make: 'Volkswagen',
    model: 'ID. Buzz',
    heroImageName: 'vw-id-buzz',
    price: 8790000,
    sellerURL: 'https://www.volkswagen.is/is/bilar/id-buzz.html',
    acceleration: 10.2,
    capacity: 77,
    range: 423,
    evDatabaseURL: 'https://ev-database.org/car/1651/Volkswagen-ID-Buzz-Pro',
    expectedDelivery: '2023',
    drive: 'RWD',
    power: 150,
    timeToCharge10T080: 28,
  },
  {
    make: 'Volkswagen',
    model: 'ID.3',
    subModel: 'Pro',
    heroImageName: 'vw-id-3-alt',
    price: 5590000,
    sellerURL: 'https://www.volkswagen.is/is/bilar/id3.html',
    acceleration: 9.6,
    capacity: 58,
    range: 420,
    evDatabaseURL: 'https://ev-database.org/car/1531/Volkswagen-ID3-Pro',
    drive: 'RWD',
    power: 107,
    timeToCharge10T080: 30,
  },
  {
    make: 'Volkswagen',
    model: 'ID.3',
    subModel: 'Pro Performance',
    heroImageName: 'vw-id-3',
    price: 6390000,
    sellerURL: 'https://www.volkswagen.is/is/bilar/id3.html',
    acceleration: 7.3,
    capacity: 58,
    range: 420,
    evDatabaseURL:
      'https://ev-database.org/car/1532/Volkswagen-ID3-Pro-Performance',
    drive: 'RWD',
    power: 150,
    timeToCharge10T080: 30,
  },
  {
    make: 'Volkswagen',
    model: 'ID.4',
    subModel: 'Pure',
    heroImageName: 'vw-id-4',
    price: 6390000,
    sellerURL: 'https://www.volkswagen.is/is/bilar/ID4.html',
    acceleration: 10.9,
    capacity: 52,
    range: 346,
    evDatabaseURL: 'https://ev-database.org/car/1489/Volkswagen-ID4-Pure',
    drive: 'RWD',
    power: 109,
    timeToCharge10T080: 34,
  },
  {
    make: 'Volkswagen',
    model: 'ID.4',
    subModel: 'Pro',
    heroImageName: 'vw-id-4-alt',
    price: 7490000,
    sellerURL: 'https://www.volkswagen.is/is/bilar/ID4.html',
    acceleration: 10.4,
    capacity: 77,
    range: 513,
    evDatabaseURL: 'https://ev-database.org/car/1627/Volkswagen-ID4-Pro',
    drive: 'RWD',
    power: 128,
    timeToCharge10T080: 34,
  },
  {
    make: 'Volkswagen',
    model: 'ID.4',
    subModel: 'Pro 4MOTION',
    heroImageName: 'vw-id-4-alt2',
    price: 8290000,
    sellerURL: 'https://www.volkswagen.is/is/bilar/ID4.html',
    acceleration: 6.9,
    capacity: 77,
    range: 517,
    evDatabaseURL:
      'https://ev-database.org/car/1702/Volkswagen-ID4-Pro-4MOTION',
    drive: 'AWD',
    power: 195,
    timeToCharge10T080: 34,
  },
  {
    make: 'Volkswagen',
    model: 'ID.4',
    subModel: 'GTX',
    heroImageName: 'vw-id-4-gtx',
    price: 8790000,
    sellerURL: 'https://www.volkswagen.is/is/bilar/id4-gtx.html',
    acceleration: 6.2,
    capacity: 77,
    evDatabaseURL: 'https://ev-database.org/car/1494/Volkswagen-ID4-GTX',
    range: 480,
    drive: 'AWD',
    power: 220,
    timeToCharge10T080: 34,
  },
  {
    make: 'Volkswagen',
    model: 'ID.5',
    subModel: 'Pro',
    heroImageName: 'vw-id-5',
    price: 7890000,
    sellerURL: 'https://www.volkswagen.is/is/bilar/id5.html',
    acceleration: 10.4,
    capacity: 77,
    range: 522,
    evDatabaseURL: 'https://ev-database.org/car/1556/Volkswagen-ID5-Pro',
    drive: 'RWD',
    power: 128,
    timeToCharge10T080: 33,
  },
  {
    make: 'Volkswagen',
    model: 'ID.5',
    subModel: 'GTX',
    heroImageName: 'vw-id-5-gtx',
    price: 9190000,
    sellerURL: 'https://www.volkswagen.is/is/bilar/id5.html',
    acceleration: 6.3,
    capacity: 77,
    evDatabaseURL: 'https://ev-database.org/car/1558/Volkswagen-ID5-GTX',
    range: 493,
    drive: 'AWD',
    power: 220,
    timeToCharge10T080: 33,
  },
  {
    make: 'Volvo',
    model: 'C40',
    subModel: 'Recharge',
    heroImageName: 'volvo-c40',
    price: 8430000,
    sellerURL: 'https://www.volvocars.com/is/v/cars/c40-electric',
    acceleration: 7.4,
    capacity: 69,
    range: 436,
    evDatabaseURL:
      'https://ev-database.org/car/1655/Volvo-C40-Recharge-Pure-Electric',
    drive: 'FWD',
    power: 170,
    timeToCharge10T080: 31,
  },
  {
    make: 'Volvo',
    model: 'C40',
    subModel: 'Recharge Twin',
    heroImageName: 'volvo-c40',
    price: 9450000,
    sellerURL: 'https://www.volvocars.com/is/v/cars/c40-electric',
    acceleration: 4.7,
    capacity: 78,
    range: 448,
    evDatabaseURL: 'https://ev-database.org/car/1421/Volvo-C40-Recharge',
    drive: 'AWD',
    power: 300,
    timeToCharge10T080: 33,
  },
  {
    make: 'Volvo',
    model: 'XC40',
    subModel: 'Recharge',
    heroImageName: 'volvo-xc40-alt',
    price: 8230000,
    sellerURL: 'https://www.volvocars.com/is/v/cars/xc40-electric',
    acceleration: 7.4,
    capacity: 69,
    range: 424,
    evDatabaseURL:
      'https://ev-database.org/car/1592/Volvo-XC40-Recharge-Pure-Electric',
    drive: 'FWD',
    power: 170,
    timeToCharge10T080: 31,
  },
  {
    make: 'Volvo',
    model: 'XC40',
    subModel: 'Recharge Twin',
    heroImageName: 'volvo-xc40',
    price: 9260000,
    sellerURL: 'https://www.volvocars.com/is/v/cars/xc40-electric',
    acceleration: 4.9,
    capacity: 78,
    range: 437,
    evDatabaseURL:
      'https://ev-database.org/car/1593/Volvo-XC40-Recharge-Twin-Pure-Electric',
    drive: 'AWD',
    power: 300,
    timeToCharge10T080: 33,
  },
  {
    make: 'Volvo',
    model: 'EX90',
    subModel: 'Twin Motor',
    heroImageName: 'volvo-ex90',
    price: 15790000,
    sellerURL: 'https://www.volvocars.com/is/cars/ex90-electric/',
    acceleration: 5.9,
    capacity: 111,
    range: 585,
    evDatabaseURL: 'https://ev-database.org/car/1775/Volvo-EX90-Twin-Motor',
    drive: 'AWD',
    power: 300,
    timeToCharge10T080: 32,
    expectedDelivery: 'Byrjun 2024',
  },
  {
    make: 'Volvo',
    model: 'EX90',
    subModel: 'Twin Motor Performance',
    heroImageName: 'volvo-ex90-alt',
    price: 16290000,
    sellerURL: 'https://www.volvocars.com/is/cars/ex90-electric/',
    acceleration: 4.9,
    capacity: 111,
    range: 580,
    evDatabaseURL:
      'https://ev-database.org/car/1776/Volvo-EX90-Twin-Motor-Performance',
    drive: 'AWD',
    power: 380,
    timeToCharge10T080: 32,
    expectedDelivery: 'Byrjun 2024',
  },
]

export default newCars
