import { NewCar } from '../types'

const newCars: Array<NewCar> = [
  {
    make: 'Aiways',
    model: 'U5',
    heroImageName: 'aiways-u5',
    price: 6_690_000,
    sellerURL: 'https://aiwaysaislandi.is',
    acceleration: 7.5,
    capacity: 63,
    range: 410,
    evDatabaseURL: 'https://ev-database.org/car/1678/Aiways-U5',
    drive: 'FWD',
    timeToCharge10T080: 35,
    power: 150,
  },
  {
    make: 'Audi',
    model: 'e-tron GT',
    subModel: 'quattro',
    heroImageName: 'audi-etron-gt',
    price: 16_990_000,
    sellerURL: 'https://www.audi.is/is/web/is/models/e-tron-gt/e-tron-gt.html',
    acceleration: 4.1,
    capacity: 93.4,
    range: 487,
    evDatabaseURL: 'https://ev-database.org/car/1420/Audi-e-tron-GT-quattro',
    drive: 'AWD',
    power: 390,
    timeToCharge10T080: 17,
  },
  {
    make: 'Audi',
    model: 'e-tron GT RS',
    subModel: 'quattro',
    heroImageName: 'audi-etron-gt-alt',
    price: 21790000,
    sellerURL: 'https://www.audi.is/is/web/is/models/e-tron-gt/e-tron-gt.html',
    acceleration: 3.3,
    capacity: 93.4,
    range: 472,
    evDatabaseURL: 'https://ev-database.org/car/1153/Audi-e-tron-GT-RS',
    drive: 'AWD',
    power: 475,
    timeToCharge10T080: 17,
    discontinued: '2024-07-13',
  },
  {
    make: 'Audi',
    model: 'Q4 e-tron',
    subModel: '40',
    heroImageName: 'audi-q4-alt',
    price: 9090000,
    sellerURL: 'http://www.audi.is/is/web/is/models/q4-e-tron/q4-e-tron.html',
    acceleration: 8.5,
    capacity: 82,
    range: 522,
    evDatabaseURL: 'https://ev-database.org/car/1490/Audi-Q4-e-tron-40',
    drive: 'RWD',
    timeToCharge10T080: 27,
    power: 150,
    discontinued: '2024-02-21',
  },
  {
    make: 'Audi',
    model: 'Q4 e-tron',
    subModel: '45 quattro',
    heroImageName: 'audi-q4-alt2',
    price: 9_690_000,
    sellerURL: 'http://www.audi.is/is/web/is/models/q4-e-tron/q4-e-tron.html',
    acceleration: 6.6,
    capacity: 82,
    range: 524,
    evDatabaseURL: 'https://ev-database.org/car/2014/Audi-Q4-e-tron-45-quattro',
    drive: 'AWD',
    timeToCharge10T080: 28,
    power: 210,
  },
  {
    make: 'Audi',
    model: 'Q4 e-tron',
    subModel: '50 quattro',
    heroImageName: 'audi-q4',
    price: 11090000,
    sellerURL: 'http://www.audi.is/is/web/is/models/q4-e-tron/q4-e-tron.html',
    acceleration: 6.2,
    capacity: 82,
    range: 488,
    evDatabaseURL: 'https://ev-database.org/car/1491/Audi-Q4-e-tron-50-quattro',
    drive: 'AWD',
    timeToCharge10T080: 29,
    power: 220,
    discontinued: '2024-02-21',
  },
  {
    make: 'Audi',
    model: 'Q4 Sportback e-tron',
    subModel: '50 quattro',
    heroImageName: 'audi-q4-sportback-alt2',
    price: 11490000,
    sellerURL: 'http://www.audi.is/is/web/is/models/q4-e-tron/q4-e-tron.html',
    acceleration: 6.2,
    capacity: 82,
    range: 488,
    evDatabaseURL:
      'https://ev-database.org/car/1492/Audi-Q4-Sportback-e-tron-50-quattro',
    drive: 'AWD',
    power: 220,
    timeToCharge10T080: 33,
    discontinued: '2024-02-21',
  },
  {
    make: 'Audi',
    model: 'Q4 Sportback e-tron',
    subModel: '45 quattro',
    heroImageName: 'audi-q4-sportback',
    price: 9_890_000,
    sellerURL: 'http://www.audi.is/is/web/is/models/q4-e-tron/q4-e-tron.html',
    acceleration: 6.6,
    capacity: 82,
    range: 541,
    evDatabaseURL:
      'https://ev-database.org/car/2017/Audi-Q4-Sportback-e-tron-45-quattro',
    drive: 'AWD',
    power: 210,
    timeToCharge10T080: 28,
  },
  {
    make: 'Audi',
    model: 'Q6 e-tron',
    heroImageName: 'audi-q6',
    price: 13_690_000,
    sellerURL: 'https://www.audi.is/is/web/is/models/q6-e-tron/q6etron.html',
    acceleration: 5.9,
    capacity: 94.9,
    range: 616,
    evDatabaseURL: 'https://ev-database.org/car/2146/Audi-Q6-e-tron-quattro',
    drive: 'AWD',
    timeToCharge10T080: 21,
    power: 285,
    expectedDelivery: 'Seinni helming 2024',
  },
  {
    make: 'Audi',
    model: 'SQ6 e-tron',
    heroImageName: 'audi-q6-alt',
    price: 16_000_000,
    sellerURL:
      'https://www.audi.co.uk/uk/web/en/models/q6-e-tron/sq6-e-tron.html',
    acceleration: 4.3,
    capacity: 100,
    range: 598,
    evDatabaseURL: 'https://ev-database.org/car/2147/Audi-SQ6-e-tron',
    drive: 'AWD',
    timeToCharge10T080: 21,
    power: 380,
    expectedDelivery: 'Seinni helming 2024',
  },
  {
    make: 'Audi',
    model: 'Q8 e-tron',
    subModel: '50 quattro',
    heroImageName: 'audi-q8',
    price: 12790000,
    sellerURL:
      'https://www.audi.is/is/web/is/models/q8-e-tron/q8-e-tron-2023.html',
    acceleration: 6.0,
    capacity: 95,
    range: 453,
    evDatabaseURL: 'https://ev-database.org/car/1769/Audi-Q8-e-tron-50-quattro',
    drive: 'AWD',
    timeToCharge10T080: 30,
    power: 250,
  },
  {
    make: 'Audi',
    model: 'Q8 e-tron',
    subModel: '55 quattro',
    heroImageName: 'audi-q8-alt',
    price: 14290000,
    sellerURL:
      'https://www.audi.is/is/web/is/models/q8-e-tron/q8-e-tron-2023.html',
    acceleration: 5.6,
    capacity: 114,
    range: 532,
    evDatabaseURL: 'https://ev-database.org/car/1770/Audi-Q8-e-tron-55-quattro',
    drive: 'AWD',
    timeToCharge10T080: 31,
    power: 300,
  },
  {
    make: 'Audi',
    model: 'Q8 e-tron Sportback',
    subModel: '50 quattro',
    heroImageName: 'audi-q8-sportback',
    price: 13190000,
    sellerURL:
      'https://www.audi.is/is/web/is/models/q8-e-tron/q8-e-tron-2023.html',
    acceleration: 6.0,
    capacity: 95,
    range: 465,
    evDatabaseURL:
      'https://ev-database.org/car/1771/Audi-Q8-e-tron-Sportback-50-quattro',
    drive: 'AWD',
    timeToCharge10T080: 30,
    power: 250,
  },
  {
    make: 'Audi',
    model: 'Q8 e-tron Sportback',
    subModel: '55 quattro',
    heroImageName: 'audi-q8-sportback-alt',
    price: 14690000,
    sellerURL:
      'https://www.audi.is/is/web/is/models/q8-e-tron/q8-e-tron-2023.html',
    acceleration: 5.6,
    capacity: 114,
    range: 548,
    evDatabaseURL:
      'https://ev-database.org/car/1772/Audi-Q8-e-tron-Sportback-55-quattro',
    drive: 'AWD',
    timeToCharge10T080: 31,
    power: 300,
  },
  {
    make: 'Audi',
    model: 'SQ8 e-tron',
    subModel: '55 quattro',
    heroImageName: 'audi-sq8',
    price: 19000000,
    sellerURL:
      'https://www.audi.is/is/web/is/models/q8-e-tron/q8-e-tron-2023.html',
    acceleration: 4.5,
    capacity: 114,
    range: 494,
    evDatabaseURL: 'https://ev-database.org/car/1773/Audi-SQ8-e-tron',
    drive: 'AWD',
    timeToCharge10T080: 31,
    power: 370,
    discontinued: '2024-01-15',
  },
  {
    make: 'Audi',
    model: 'SQ8 e-tron Sportback',
    subModel: '55 quattro',
    heroImageName: 'audi-sq8-sportback',
    price: 19500000,
    sellerURL:
      'https://www.audi.is/is/web/is/models/q8-e-tron/q8-e-tron-2023.html',
    acceleration: 4.5,
    capacity: 114,
    range: 513,
    evDatabaseURL: 'https://ev-database.org/car/1774/Audi-SQ8-e-tron-Sportback',
    drive: 'AWD',
    timeToCharge10T080: 31,
    power: 370,
    discontinued: '2024-01-15',
  },
  {
    make: 'BMW',
    model: 'i4',
    subModel: 'eDrive 35',
    heroImageName: 'bmw-i4-alt',
    price: 10790000,
    sellerURL:
      'https://www.bmw.is/is/all-models/bmw-i/i4/2021/bmw-i4-highlights.html',
    acceleration: 6.0,
    capacity: 70.2,
    range: 483,
    evDatabaseURL: 'https://ev-database.org/car/1785/BMW-i4-eDrive35',
    drive: 'RWD',
    power: 210,
    timeToCharge10T080: 31,
  },
  {
    make: 'BMW',
    model: 'i4',
    subModel: 'eDrive 40',
    heroImageName: 'bmw-i4',
    price: 11890000,
    sellerURL:
      'https://www.bmw.is/is/all-models/bmw-i/i4/2021/bmw-i4-highlights.html',
    acceleration: 5.7,
    capacity: 83.9,
    range: 590,
    evDatabaseURL: 'https://ev-database.org/car/1252/BMW-i4-eDrive40',
    drive: 'RWD',
    power: 250,
    timeToCharge10T080: 30,
  },
  {
    make: 'BMW',
    model: 'i4',
    subModel: 'M50',
    heroImageName: 'bmw-i4-m50',
    price: 13590000,
    sellerURL:
      'https://www.bmw.is/is/all-models/m-series/i4-m50/2021/bmw-i4-m50-highlights.html',
    acceleration: 3.9,
    capacity: 83.9,
    range: 510,
    evDatabaseURL: 'https://ev-database.org/car/1519/BMW-i4-M50',
    drive: 'AWD',
    power: 400,
    timeToCharge10T080: 30,
  },
  {
    make: 'BMW',
    model: 'i5',
    subModel: 'eDrive40',
    heroImageName: 'bmw-i5',
    price: 13500000,
    sellerURL: 'https://www.bmw.is/is/all-models/bmw-i/i5/bmw-i5-overview.html',
    acceleration: 6.0,
    capacity: 84.4,
    range: 582,
    evDatabaseURL: 'https://ev-database.org/car/1906/BMW-i5-eDrive40-Sedan',
    drive: 'RWD',
    power: 250,
    timeToCharge10T080: 28,
    expectedDelivery: 'Sumar 2024',
  },
  {
    make: 'BMW',
    model: 'i5',
    subModel: 'M60',
    heroImageName: 'bmw-i5-m',
    price: 19890000,
    sellerURL:
      'https://www.bmw.is/is/all-models/m-series/bmw-i5-m60/bmw-i5-m60xdrive-overview.html',
    acceleration: 3.8,
    capacity: 84.4,
    range: 516,
    evDatabaseURL: 'https://ev-database.org/car/1907/BMW-i5-M60-xDrive-Sedan',
    drive: 'AWD',
    power: 442,
    timeToCharge10T080: 28,
  },
  {
    make: 'BMW',
    model: 'i7',
    heroImageName: 'bmw-i7',
    price: 23790000,
    sellerURL:
      'https://www.bmw.is/is/all-models/bmw-i/i7/2022/bmw-i7-sedan-highlights.html',
    acceleration: 4.7,
    capacity: 105,
    range: 625,
    evDatabaseURL: 'https://ev-database.org/car/1676/BMW-i7-xDrive60',
    drive: 'AWD',
    power: 400,
    timeToCharge10T080: 35,
  },
  {
    make: 'BMW',
    model: 'iX',
    subModel: 'xDrive 40',
    heroImageName: 'bmw-ix',
    price: 14990000,
    sellerURL: 'https://www.bmw.is/is/all-models/bmw-i/bmw-ix/2021/bmw-ix.html',
    acceleration: 6.1,
    capacity: 75,
    range: 422,
    evDatabaseURL: 'https://ev-database.org/car/1472/BMW-iX-xDrive-40',
    drive: 'AWD',
    power: 240,
    timeToCharge10T080: 30,
  },
  {
    make: 'BMW',
    model: 'iX',
    subModel: 'xDrive 50',
    heroImageName: 'bmw-ix-alt',
    price: 16490000,
    sellerURL: 'https://www.bmw.is/is/all-models/bmw-i/bmw-ix/2021/bmw-ix.html',
    acceleration: 4.6,
    capacity: 110,
    range: 607,
    evDatabaseURL: 'https://ev-database.org/car/1473/BMW-iX-xDrive-50',
    drive: 'AWD',
    power: 385,
    timeToCharge10T080: 31,
  },
  {
    make: 'BMW',
    model: 'iX',
    subModel: 'xDrive M60',
    heroImageName: 'bmw-ix-alt2',
    price: 20990000,
    sellerURL: 'https://www.bmw.is/is/all-models/bmw-i/bmw-ix/2021/bmw-ix.html',
    acceleration: 3.8,
    capacity: 110,
    range: 561,
    evDatabaseURL: 'https://ev-database.org/car/1590/BMW-iX-M60',
    drive: 'AWD',
    power: 455,
    timeToCharge10T080: 31,
  },
  {
    make: 'BMW',
    model: 'iX1',
    subModel: 'eDrive 20',
    heroImageName: 'bmw-ix1',
    price: 9890000,
    sellerURL: 'https://www.bmw.is/is/all-models/bmw-i/iX1/2022/bmw-ix1.html',
    acceleration: 8.3,
    capacity: 66.5,
    range: 475,
    evDatabaseURL: 'https://ev-database.org/car/1996/BMW-iX1-eDrive20',
    drive: 'FWD',
    power: 150,
    timeToCharge10T080: 29,
  },
  {
    make: 'BMW',
    model: 'iX1',
    subModel: 'xDrive 30',
    heroImageName: 'bmw-ix1',
    price: 10990000,
    sellerURL: 'https://www.bmw.is/is/all-models/bmw-i/iX1/2022/bmw-ix1.html',
    acceleration: 5.6,
    capacity: 66.5,
    range: 438,
    evDatabaseURL: 'https://ev-database.org/car/1701/BMW-iX1-xDrive30',
    drive: 'AWD',
    power: 230,
    timeToCharge10T080: 29,
  },
  {
    make: 'BMW',
    model: 'iX2',
    heroImageName: 'bmw-ix2',
    price: 9_890_000,
    sellerURL: 'https://www.bmw.com/en-au/models/bmw-i/bmw-ix2.html',
    acceleration: 5.6,
    capacity: 66.5,
    range: 449,
    evDatabaseURL: 'https://ev-database.org/car/2040/BMW-iX2-xDrive30',
    drive: 'AWD',
    power: 230,
    timeToCharge10T080: 29,
    expectedDelivery: '2024',
  },
  {
    make: 'BMW',
    model: 'iX3',
    heroImageName: 'bmw-ix3',
    price: 9_490_000,
    sellerURL:
      'https://www.bmw.is/is/all-models/x-series/iX3/2021/bmw-ix3-highlights.html',
    acceleration: 6.8,
    capacity: 80,
    range: 461,
    evDatabaseURL: 'https://ev-database.org/car/1535/BMW-iX3',
    drive: 'RWD',
    power: 210,
    timeToCharge10T080: 33,
  },
  {
    make: 'BYD',
    model: 'Atto3',
    heroImageName: 'byd-atto3',
    price: 6490000,
    sellerURL: 'https://byd.is/typur/byd-atto-3/',
    acceleration: 7.3,
    capacity: 60,
    range: 420,
    evDatabaseURL: 'https://ev-database.org/car/1782/BYD-ATTO-3',
    drive: 'FWD',
    power: 150,
    timeToCharge10T080: 44,
  },
  {
    make: 'BYD',
    model: 'Dolphin',
    heroImageName: 'byd-dolphin',
    price: 5490000,
    sellerURL: 'https://byd.is/typur/byd-dolphin/',
    acceleration: 7.0,
    capacity: 60.5,
    range: 427,
    evDatabaseURL: 'https://ev-database.org/car/1919/BYD-DOLPHIN-604-kWh',
    drive: 'FWD',
    power: 150,
    timeToCharge10T080: 41,
  },
  {
    make: 'BYD',
    model: 'Han',
    heroImageName: 'byd-han',
    price: 9980000,
    sellerURL: 'https://byd.is/typur/han-4x4/',
    acceleration: 3.9,
    capacity: 85.4,
    range: 521,
    evDatabaseURL: 'https://ev-database.org/car/1784/BYD-HAN',
    drive: 'AWD',
    power: 380,
    timeToCharge10T080: 43,
  },
  {
    make: 'BYD',
    model: 'Seal',
    heroImageName: 'byd-seal',
    price: 8_490_000,
    sellerURL: 'https://byd.is/typur/byd-seal/',
    acceleration: 3.8,
    capacity: 82.5,
    range: 520,
    evDatabaseURL:
      'https://ev-database.org/car/2002/BYD-SEAL-825-kWh-AWD-Excellence',
    drive: 'AWD',
    power: 390,
    timeToCharge10T080: 38,
  },
  {
    make: 'BYD',
    model: 'Seal U',
    heroImageName: 'byd-seal-u',
    price: 7_490_000,
    sellerURL: 'https://byd.is/typur/byd-seal-u/',
    acceleration: 9.3,
    capacity: 87,
    range: 500,
    evDatabaseURL: 'https://ev-database.org/car/2067/BYD-SEAL-U-87-kWh-Design',
    drive: 'FWD',
    power: 160,
    timeToCharge10T080: 45,
  },
  {
    make: 'BYD',
    model: 'Tang',
    heroImageName: 'byd-tang',
    price: 11998000,
    sellerURL: 'https://byd.is/typur/tang-4x4-sportjeppi/',
    acceleration: 4.6,
    capacity: 86.4,
    range: 400,
    evDatabaseURL: 'https://ev-database.org/car/1783/BYD-TANG',
    drive: 'AWD',
    power: 380,
    timeToCharge10T080: 44,
  },
  {
    make: 'Citroën',
    model: 'ë-Berlingo',
    heroImageName: 'citroen-e-berlingo',
    price: 7_370_000,
    sellerURL: 'https://www.citroen.is/tegundir/e-berlingo.html',
    acceleration: 11.7,
    capacity: 50,
    range: 282,
    evDatabaseURL:
      'https://ev-database.org/car/1546/Citroen-e-Berlingo-M-50-kWh',
    drive: 'FWD',
    timeToCharge10T080: 26,
    power: 100,
  },
  {
    make: 'Citroën',
    model: 'ë-C4',
    heroImageName: 'citroen-ec4',
    price: 6_590_000,
    sellerURL: 'https://www.citroen.is/tegundir/c4-e/e-c4.html',
    acceleration: 9.2,
    capacity: 54,
    range: 415,
    evDatabaseURL: 'https://ev-database.org/car/1938/Citroen-e-C4-54-kWh',
    drive: 'FWD',
    timeToCharge10T080: 29,
    power: 115,
  },
  {
    make: 'Citroën',
    model: 'ë-C4 X',
    heroImageName: 'citroen-ec4x',
    price: 6_890_000,
    sellerURL: 'https://www.citroen.is/urval-citroen-bila.html#',
    acceleration: 9.3,
    capacity: 54,
    range: 418,
    evDatabaseURL: 'https://ev-database.org/car/1939/Citroen-e-C4-X-54-kWh',
    drive: 'FWD',
    timeToCharge10T080: 29,
    power: 115,
  },
  {
    make: 'Fiat',
    model: '500e',
    heroImageName: 'fiat-500e',
    price: 5_890_000,
    sellerURL: 'https://www.fiat.is/model/500e-la-prima/',
    acceleration: 9.0,
    capacity: 42,
    range: 305,
    evDatabaseURL:
      'https://ev-database.org/car/1285/Fiat-500e-Hatchback-42-kWh',
    drive: 'FWD',
    timeToCharge10T080: 25,
    power: 87,
  },
  {
    make: 'Fiat',
    model: '600e',
    heroImageName: 'fiat-600e',
    price: 5_890_000,
    sellerURL: 'https://www.fiat.is/600-electric',
    acceleration: 9.0,
    capacity: 54,
    range: 400,
    evDatabaseURL: 'https://ev-database.org/car/1945/Fiat-600e',
    drive: 'FWD',
    timeToCharge10T080: 26,
    power: 115,
  },
  {
    make: 'Ford',
    model: 'Capri',
    heroImageName: 'ford-capri',
    price: 8_890_000,
    sellerURL: 'https://www.ford.is/is/nyir-bilar/capri',
    acceleration: 5.3,
    capacity: 79,
    range: 592,
    evDatabaseURL:
      'https://ev-database.org/car/2242/Ford-Capri-Extended-Range-AWD',
    drive: 'AWD',
    timeToCharge10T080: 26,
    power: 250,
    expectedDelivery: '2024',
  },
  {
    make: 'Ford',
    model: 'Explorer',
    subModel: 'ER RWD',
    heroImageName: 'ford-explorer',
    price: 7_590_000,
    sellerURL: 'https://www.ford.is/is/nyir-bilar/explorer-rafmagnsjeppi',
    acceleration: 6.4,
    capacity: 77,
    range: 602,
    evDatabaseURL:
      'https://ev-database.org/car/2168/Ford-Explorer-Extended-Range-RWD',
    drive: 'RWD',
    timeToCharge10T080: 28,
    power: 210,
    expectedDelivery: '2024',
  },
  {
    make: 'Ford',
    model: 'Explorer',
    subModel: 'ER AWD',
    heroImageName: 'ford-explorer-alt',
    price: 8_490_000,
    sellerURL: 'https://www.ford.is/is/nyir-bilar/explorer-rafmagnsjeppi',
    acceleration: 5.3,
    capacity: 79,
    range: 566,
    evDatabaseURL:
      'https://ev-database.org/car/2169/Ford-Explorer-Extended-Range-AWD',
    drive: 'AWD',
    timeToCharge10T080: 28,
    power: 250,
  },
  {
    make: 'Ford',
    model: 'Mustang Mach-E',
    subModel: 'SR RWD',
    heroImageName: 'ford-mach-e',
    price: 8490000,
    sellerURL: 'https://www.ford.is/is/nyir-bilar/Mustang-Mach-E',
    acceleration: 7.3,
    capacity: 76,
    range: 440,
    evDatabaseURL:
      'https://ev-database.org/car/2034/Ford-Mustang-Mach-E-SR-RWD',
    drive: 'RWD',
    timeToCharge10T080: 34,
    power: 198,
  },
  {
    make: 'Ford',
    model: 'Mustang Mach-E',
    subModel: 'LR RWD',
    heroImageName: 'ford-mach-e-alt',
    price: 9890000,
    sellerURL: 'https://www.ford.is/is/nyir-bilar/Mustang-Mach-E',
    acceleration: 7.0,
    capacity: 99,
    range: 600,
    evDatabaseURL:
      'https://ev-database.org/car/2035/Ford-Mustang-Mach-E-ER-RWD',
    drive: 'RWD',
    power: 216,
    timeToCharge10T080: 47,
  },
  {
    make: 'Ford',
    model: 'Mustang Mach-E',
    subModel: 'SR AWD',
    heroImageName: 'ford-mach-e-alt2',
    price: 9890000,
    sellerURL: 'https://www.ford.is/is/nyir-bilar/Mustang-Mach-E',
    acceleration: 6.2,
    capacity: 76,
    range: 400,
    evDatabaseURL:
      'https://ev-database.org/car/2036/Ford-Mustang-Mach-E-SR-AWD',
    drive: 'AWD',
    timeToCharge10T080: 34,
    power: 198,
  },
  {
    make: 'Ford',
    model: 'Mustang Mach-E',
    subModel: 'LR AWD',
    heroImageName: 'ford-mach-e-alt3',
    price: 10190000,
    sellerURL: 'https://www.ford.is/is/nyir-bilar/Mustang-Mach-E',
    acceleration: 5.8,
    capacity: 99,
    range: 550,
    evDatabaseURL:
      'https://ev-database.org/car/2037/Ford-Mustang-Mach-E-ER-AWD',
    drive: 'AWD',
    power: 258,
    timeToCharge10T080: 47,
  },
  {
    make: 'Ford',
    model: 'Mustang Mach-E',
    subModel: 'GT',
    heroImageName: 'ford-mach-e-alt',
    price: 11490000,
    sellerURL: 'https://www.ford.is/is/nyir-bilar/Mustang-Mach-E',
    acceleration: 3.7,
    capacity: 99,
    range: 490,
    evDatabaseURL: 'https://ev-database.org/car/2038/Ford-Mustang-Mach-E-GT',
    drive: 'AWD',
    power: 358,
    timeToCharge10T080: 47,
  },
  {
    make: 'Honda',
    model: 'e',
    subModel: 'Advance',
    heroImageName: 'honda-e',
    price: 4990000,
    sellerURL: 'https://www.honda.is/voruflokkar/bilar/honda-e/',
    acceleration: 8.3,
    capacity: 32.0,
    range: 220,
    evDatabaseURL: 'https://ev-database.org/car/1233/Honda-e-Advance',
    drive: 'RWD',
    power: 113,
    timeToCharge10T080: 36,
    discontinued: '2023-08-19',
  },
  {
    make: 'Honda',
    model: 'e:Ny1',
    heroImageName: 'honda-eny1',
    price: 5_500_000,
    sellerURL: 'https://www.honda.is/honda-eny1',
    acceleration: 7.6,
    capacity: 68.8,
    range: 412,
    evDatabaseURL: 'https://ev-database.org/car/1940/Honda-eNy1',
    drive: 'FWD',
    power: 150,
    timeToCharge10T080: 46,
    expectedDelivery: '2025',
  },
  {
    make: 'Hongqi',
    model: 'E-HS9',
    heroImageName: 'hongqi-ehs9',
    price: 10_290_000,
    sellerURL: 'https://www.hongqi.is/ehs9.html',
    acceleration: 6.5,
    capacity: 84.0,
    range: 380,
    evDatabaseURL: 'https://ev-database.org/car/1746/Hongqi-E-HS9-84-kWh',
    drive: 'AWD',
    power: 320,
    timeToCharge10T080: 30,
    discontinued: '2024-09-29',
  },
  {
    make: 'Hongqi',
    model: 'E-HS9',
    heroImageName: 'hongqi-ehs9-alt',
    price: 12_290_000,
    sellerURL: 'https://www.hongqi.is/ehs9.html',
    acceleration: 4.9,
    capacity: 99.0,
    range: 441,
    evDatabaseURL: 'https://ev-database.org/car/1747/Hongqi-E-HS9-99-kWh',
    drive: 'AWD',
    power: 405,
    timeToCharge10T080: 36,
  },
  {
    make: 'Hongqi',
    model: 'E-HS9',
    heroImageName: 'hongqi-ehs9',
    price: 15_290_000,
    sellerURL: 'https://www.hongqi.is/ehs9.html',
    acceleration: 5.1,
    capacity: 120.0,
    range: 520,
    drive: 'AWD',
    power: 405,
    timeToCharge10T080: 36,
  },
  {
    make: 'Hyundai',
    model: 'IONIQ 5',
    subModel: 'Standard Range 2WD',
    heroImageName: 'hyundai-ioniq-5',
    price: 7_790_000,
    sellerURL: 'https://hyundai.is/bilarnir/ioniq-5/',
    acceleration: 8.5,
    capacity: 58,
    range: 384,
    evDatabaseURL:
      'https://ev-database.org/car/1476/Hyundai-IONIQ-5-Standard-Range-2WD',
    drive: 'RWD',
    power: 125,
    timeToCharge10T080: 17,
  },
  {
    make: 'Hyundai',
    model: 'IONIQ 5',
    subModel: 'Long Range 2WD',
    heroImageName: 'hyundai-ioniq-5-alt',
    price: 8_390_000,
    sellerURL: 'https://hyundai.is/bilarnir/ioniq-5/',
    acceleration: 7.4,
    capacity: 77.4,
    range: 507,
    evDatabaseURL:
      'https://ev-database.org/car/1662/Hyundai-IONIQ-5-Long-Range-2WD',
    drive: 'RWD',
    power: 168,
    timeToCharge10T080: 17,
  },
  {
    make: 'Hyundai',
    model: 'IONIQ 5',
    subModel: 'Long Range AWD',
    heroImageName: 'hyundai-ioniq-5-alt2',
    price: 8_890_000,
    sellerURL: 'https://hyundai.is/bilarnir/ioniq-5/',
    acceleration: 5.2,
    capacity: 77.4,
    range: 481,
    evDatabaseURL:
      'https://ev-database.org/car/1663/Hyundai-IONIQ-5-Long-Range-AWD',
    drive: 'AWD',
    power: 239,
    timeToCharge10T080: 17,
  },
  {
    make: 'Hyundai',
    model: 'IONIQ 6',
    subModel: 'Long Range 2WD',
    heroImageName: 'hyundai-ioniq-6',
    price: 8_490_000,
    sellerURL: 'https://hyundai.is/bilarnir/nyr-ioniq-6/',
    acceleration: 7.4,
    capacity: 77.4,
    range: 614,
    evDatabaseURL:
      'https://ev-database.org/car/1718/Hyundai-IONIQ-6-Long-Range-2WD',
    drive: 'RWD',
    power: 168,
    timeToCharge10T080: 16,
  },
  {
    make: 'Hyundai',
    model: 'IONIQ 6',
    subModel: 'Long Range 4WD',
    heroImageName: 'hyundai-ioniq-6-alt',
    price: 8_990_000,
    sellerURL: 'https://hyundai.is/bilarnir/nyr-ioniq-6/',
    acceleration: 5.1,
    capacity: 77.4,
    range: 583,
    evDatabaseURL:
      'https://ev-database.org/car/1719/Hyundai-IONIQ-6-Long-Range-AWD',
    drive: 'AWD',
    power: 239,
    timeToCharge10T080: 16,
  },
  {
    make: 'Hyundai',
    model: 'Kona Electric',
    subModel: '64 kWh',
    heroImageName: 'kona',
    price: 7_890_000,
    sellerURL: 'https://hyundai.is/bilarnir/kona-ev/',
    acceleration: 7.6,
    capacity: 64,
    range: 484,
    evDatabaseURL:
      'https://ev-database.org/car/1423/Hyundai-Kona-Electric-64-kWh',
    drive: 'FWD',
    power: 150,
    timeToCharge10T080: 44,
  },
  {
    make: 'Hyundai',
    model: 'Kona Electric',
    subModel: '48 kWh',
    heroImageName: 'hyundai-kona-2024',
    price: 7_190_000,
    sellerURL: 'https://hyundai.is/bilarnir/kona-sx2-ev/',
    acceleration: 7.8,
    capacity: 48.4,
    range: 377,
    evDatabaseURL:
      'https://ev-database.org/car/1829/Hyundai-Kona-Electric-48-kWh',
    drive: 'FWD',
    power: 115,
    timeToCharge10T080: 43,
  },
  {
    make: 'Hyundai',
    model: 'Kona Electric',
    subModel: '65 kWh',
    heroImageName: 'hyundai-kona-2024-alt',
    price: 7_890_000,
    sellerURL: 'https://hyundai.is/bilarnir/kona-sx2-ev/',
    acceleration: 7.8,
    capacity: 65.4,
    range: 514,
    evDatabaseURL:
      'https://ev-database.org/car/1830/Hyundai-Kona-Electric-65-kWh',
    drive: 'FWD',
    power: 160,
    timeToCharge10T080: 41,
  },
  {
    make: 'Jaguar',
    model: 'I-PACE',
    heroImageName: 'jaguar-i-pace',
    price: 13_290_000,
    sellerURL: 'https://www.jaguarisland.is/jaguar-range-i-pace',
    acceleration: 4.8,
    capacity: 90,
    range: 470,
    evDatabaseURL: 'https://ev-database.org/car/1812/Jaguar-I-Pace-EV400',
    drive: 'AWD',
    power: 294,
    timeToCharge10T080: 44,
  },
  {
    make: 'Jeep',
    model: 'Avenger',
    heroImageName: 'jeep-avenger',
    price: 6890000,
    sellerURL: 'https://www.jeep.com/is/jeep-avenger/new-jeep-avenger.html',
    acceleration: 9,
    capacity: 54,
    range: 400,
    evDatabaseURL: 'https://ev-database.org/car/1816/Jeep-Avenger-Electric',
    drive: 'FWD',
    power: 115,
    timeToCharge10T080: 44,
  },
  {
    make: 'Kia',
    model: 'Niro EV',
    heroImageName: 'kia-niro-2023',
    price: 6_590_777,
    sellerURL: 'https://www.kia.com/is/nyir-bilar/niro-sg2/',
    acceleration: 7.8,
    capacity: 64.8,
    range: 463,
    evDatabaseURL: 'https://ev-database.org/car/1666/Kia-Niro-EV',
    drive: 'FWD',
    power: 150,
    timeToCharge10T080: 43,
  },
  {
    make: 'Kia',
    model: 'e-Soul',
    subModel: '64 kWh',
    heroImageName: 'e-soul',
    price: 7590777,
    sellerURL: 'https://www.kia.com/is/nyir-bilar/e-soul/upplifdu/',
    acceleration: 7.9,
    capacity: 64,
    range: 452,
    evDatabaseURL: 'https://ev-database.org/car/1288/Kia-e-Soul-64-kWh',
    drive: 'FWD',
    power: 150,
    timeToCharge10T080: 44,
    discontinued: '2024-08-12',
  },
  {
    make: 'Kia',
    model: 'EV3',
    subModel: 'Standard Range',
    heroImageName: 'kia-ev3',
    price: 6_190_777,
    sellerURL: 'https://www.kia.com/is/nyir-bilar/ev-3/premiere/',
    acceleration: 7.5,
    capacity: 58.3,
    range: 436,
    evDatabaseURL: 'https://ev-database.org/car/2211/Kia-EV3-Standard-Range',
    drive: 'RWD',
    power: 150,
    timeToCharge10T080: 29,
  },
  {
    make: 'Kia',
    model: 'EV3',
    subModel: 'Long Range',
    heroImageName: 'kia-ev3-alt',
    price: 6_890_777,
    sellerURL: 'https://www.kia.com/is/nyir-bilar/ev-3/premiere/',
    acceleration: 7.7,
    capacity: 81.4,
    range: 605,
    evDatabaseURL: 'https://ev-database.org/car/2212/Kia-EV3-Long-Range',
    drive: 'RWD',
    power: 150,
    timeToCharge10T080: 31,
  },
  {
    make: 'Kia',
    model: 'EV6',
    subModel: 'Standard Range RWD',
    heroImageName: 'kia-ev6',
    price: 6_690_777,
    sellerURL: 'https://www.kia.com/is/nyir-bilar/ev6/upplifdu/',
    acceleration: 8.5,
    capacity: 58,
    range: 397,
    evDatabaseURL:
      'https://ev-database.org/car/1480/Kia-EV6-Standard-Range-2WD',
    drive: 'RWD',
    power: 125,
    timeToCharge10T080: 18,
  },
  {
    make: 'Kia',
    model: 'EV6',
    subModel: 'Long Range RWD',
    heroImageName: 'kia-ev6-alt2',
    price: 7_490_777,
    sellerURL: 'https://www.kia.com/is/nyir-bilar/ev6/upplifdu/',
    acceleration: 7.3,
    capacity: 77.4,
    range: 528,
    evDatabaseURL: 'https://ev-database.org/car/1481/Kia-EV6-Long-Range-2WD',
    drive: 'RWD',
    power: 168,
    timeToCharge10T080: 18,
  },
  {
    make: 'Kia',
    model: 'EV6',
    subModel: 'Long Range AWD',
    heroImageName: 'kia-ev6-alt3',
    price: 8490777,
    sellerURL: 'https://www.kia.com/is/nyir-bilar/ev6/upplifdu/',
    acceleration: 5.2,
    capacity: 77.4,
    range: 506,
    evDatabaseURL: 'https://ev-database.org/car/1482/Kia-EV6-Long-Range-AWD',
    drive: 'AWD',
    power: 239,
    timeToCharge10T080: 18,
  },
  {
    make: 'Kia',
    model: 'EV6',
    subModel: 'GT',
    heroImageName: 'kia-ev6-alt2',
    price: 10990777,
    sellerURL: 'https://www.kia.com/is/nyir-bilar/ev6/upplifdu/',
    acceleration: 3.5,
    capacity: 77.4,
    range: 406,
    evDatabaseURL: 'https://ev-database.org/car/1471/Kia-EV6-GT',
    drive: 'AWD',
    power: 430,
    timeToCharge10T080: 16,
  },
  {
    make: 'Kia',
    model: 'EV9',
    heroImageName: 'kia-ev9',
    price: 13490777,
    sellerURL: 'https://www.kia.com/is/new-cars/ev9/premiere/',
    acceleration: 5.3,
    capacity: 105,
    range: 450,
    evDatabaseURL: 'https://ev-database.org/car/1835/Kia-EV9-998-kWh-AWD',
    drive: 'AWD',
    power: 283,
    timeToCharge10T080: 23,
  },
  {
    make: 'Lexus',
    model: 'RZ',
    subModel: '450e',
    heroImageName: 'lexus-rz',
    price: 13760000,
    sellerURL: 'https://www.lexus.is/new-cars/rz',
    acceleration: 5.3,
    capacity: 71.4,
    range: 440,
    evDatabaseURL: 'https://ev-database.org/car/1677/Lexus-RZ-450e',
    drive: 'AWD',
    power: 230,
    timeToCharge10T080: 28,
  },
  {
    make: 'Lexus',
    model: 'UX',
    subModel: '300e',
    heroImageName: 'lexus-ux-300e',
    price: 11990000,
    sellerURL: 'https://www.lexus.is/car-models/ux-300e/',
    acceleration: 7.5,
    capacity: 72.8,
    range: 450,
    evDatabaseURL: 'https://ev-database.org/car/1943/Lexus-UX-300e',
    drive: 'FWD',
    power: 150,
    timeToCharge10T080: 81,
  },
  {
    make: 'Maxus',
    model: 'EUNIQ 5',
    heroImageName: 'maxus-euniq-5',
    price: 8_590_000,
    sellerURL: 'https://maxus.is/typur/euniq5-6-saeta/',
    acceleration: 9.5,
    capacity: 52.5,
    range: 356,
    drive: 'FWD',
    power: 130,
    timeToCharge10T080: 38,
  },
  {
    make: 'Maxus',
    model: 'EUNIQ 6',
    heroImageName: 'maxus-euniq-6',
    price: 7_980_000,
    sellerURL: 'https://maxus.is/typur/euniq6/',
    acceleration: 9.5,
    capacity: 70,
    range: 354,
    drive: 'FWD',
    power: 130,
    timeToCharge10T080: 38,
  },
  {
    make: 'Maxus',
    model: 'eT90',
    heroImageName: 'maxus-et90',
    price: 9_980_000,
    sellerURL: 'https://maxus.is/typur/t90-ev-rafknuinn-pallbill',
    acceleration: 10,
    capacity: 88.5,
    range: 330,
    drive: 'RWD',
    power: 150,
    timeToCharge10T080: 45,
  },
  {
    make: 'Mazda',
    model: 'MX-30',
    heroImageName: 'mazda-mx-30',
    price: 4_790_000,
    sellerURL: 'https://www.mazda.is/is/nyir-bilar/mazda-mx-30',
    acceleration: 9.0,
    capacity: 35.5,
    range: 200,
    evDatabaseURL: 'https://ev-database.org/car/1680/Mazda-MX-30',
    drive: 'FWD',
    power: 105,
    timeToCharge10T080: 39,
  },
  {
    make: 'Mercedes-Benz',
    model: 'EQA SUV',
    subModel: '250',
    heroImageName: 'mercedes-eqa',
    price: 8990000,
    sellerURL: 'https://www.mercedes-benz.is/models/eqa-fl/',
    acceleration: 8.6,
    capacity: 66.5,
    range: 528,
    evDatabaseURL: 'https://ev-database.org/car/1984/Mercedes-EQA-250',
    drive: 'FWD',
    power: 140,
    timeToCharge10T080: 29,
  },
  {
    make: 'Mercedes-Benz',
    model: 'EQA SUV',
    subModel: '300 4MATIC',
    heroImageName: 'mercedes-eqa-alt',
    price: 9490000,
    sellerURL: 'https://www.mercedes-benz.is/models/eqa-fl/',
    acceleration: 7.7,
    capacity: 66.5,
    range: 459,
    evDatabaseURL:
      'https://ev-database.org/car/1986/Mercedes-Benz-EQA-300-4MATIC',
    drive: 'AWD',
    power: 168,
    timeToCharge10T080: 35,
  },
  {
    make: 'Mercedes-Benz',
    model: 'EQA SUV',
    subModel: '350 4MATIC',
    heroImageName: 'mercedes-eqa-alt2',
    price: 10790000,
    sellerURL: 'https://www.mercedes-benz.is/models/eqa-fl/',
    acceleration: 6.0,
    capacity: 66.5,
    range: 438,
    evDatabaseURL: 'https://ev-database.org/car/1496/Mercedes-EQA-350-4MATIC',
    drive: 'AWD',
    power: 215,
    timeToCharge10T080: 35,
    discontinued: '2023-08-24',
  },
  {
    make: 'Mercedes-Benz',
    model: 'EQB SUV',
    subModel: '250',
    heroImageName: 'mercedes-eqb',
    price: 7990000,
    sellerURL:
      'https://www.mercedes-benz.is/passengercars/mercedes-benz-cars/models/eqb/',
    acceleration: 8.9,
    capacity: 66.5,
    range: 473,
    evDatabaseURL: 'https://ev-database.org/car/1664/Mercedes-EQB-250',
    drive: 'FWD',
    power: 140,
    timeToCharge10T080: 29,
    discontinued: '2024-02-28',
  },
  {
    make: 'Mercedes-Benz',
    model: 'EQB SUV',
    subModel: '300 4MATIC',
    heroImageName: 'mercedes-eqb',
    price: 9590000,
    sellerURL: 'https://www.mercedes-benz.is/models/eqb-fl/',
    acceleration: 8.0,
    capacity: 66.5,
    range: 423,
    evDatabaseURL:
      'https://ev-database.org/car/1989/Mercedes-Benz-EQB-300-4MATIC',
    drive: 'AWD',
    power: 168,
    timeToCharge10T080: 29,
  },
  {
    make: 'Mercedes-Benz',
    model: 'EQB SUV',
    subModel: '350 4MATIC',
    heroImageName: 'mercedes-eqb',
    price: 11290000,
    sellerURL:
      'https://www.mercedes-benz.is/passengercars/mercedes-benz-cars/models/eqb/',
    acceleration: 6.2,
    capacity: 66.5,
    range: 423,
    evDatabaseURL: 'https://ev-database.org/car/1493/Mercedes-EQB-350-4MATIC',
    drive: 'AWD',
    power: 215,
    timeToCharge10T080: 29,
    discontinued: '2023-08-24',
  },
  {
    make: 'Mercedes-Benz',
    model: 'EQC',
    subModel: '400 4MATIC',
    heroImageName: 'eqc',
    price: 10990000,
    sellerURL: 'https://www.mercedes-benz.is/models/eqc/',
    acceleration: 5.1,
    capacity: 80,
    range: 437,
    evDatabaseURL: 'https://ev-database.org/car/1337/Mercedes-EQC-400-4MATIC',
    drive: 'AWD',
    power: 300,
    timeToCharge10T080: 35,
  },
  {
    make: 'Mercedes-Benz',
    model: 'EQE',
    subModel: '300',
    heroImageName: 'mercedes-eqe',
    price: 12290000,
    sellerURL: 'https://www.mercedes-benz.is/models/eqe/',
    acceleration: 7.3,
    capacity: 90.6,
    range: 621,
    evDatabaseURL: 'https://ev-database.org/car/2204/Mercedes-Benz-EQE-300',
    drive: 'RWD',
    power: 180,
    timeToCharge10T080: 33,
  },
  {
    make: 'Mercedes-Benz',
    model: 'EQE',
    subModel: '350 4MATIC',
    heroImageName: 'mercedes-eqe-alt',
    price: 13490000,
    sellerURL: 'https://www.mercedes-benz.is/models/eqe/',
    acceleration: 6.3,
    capacity: 90.6,
    range: 614,
    evDatabaseURL:
      'https://ev-database.org/car/2206/Mercedes-Benz-EQE-350-4MATIC',
    drive: 'AWD',
    power: 215,
    timeToCharge10T080: 28,
  },
  {
    make: 'Mercedes-Benz',
    model: 'EQE',
    subModel: 'AMG 43 4MATIC',
    heroImageName: 'mercedes-eqe-amg',
    price: 18290000,
    sellerURL: 'https://www.mercedes-benz.is/models/eqe/',
    acceleration: 4.2,
    capacity: 90.6,
    range: 535,
    evDatabaseURL:
      'https://ev-database.org/car/1652/Mercedes-EQE-AMG-43-4MATIC',
    drive: 'AWD',
    power: 350,
    timeToCharge10T080: 28,
    discontinued: '2024-01-01',
  },
  {
    make: 'Mercedes-Benz',
    model: 'EQE',
    subModel: 'AMG 53 4MATIC+',
    heroImageName: 'mercedes-eqe-alt',
    price: 22450000,
    sellerURL: 'https://www.mercedes-benz.is/models/eqe/',
    acceleration: 3.5,
    capacity: 90.6,
    range: 527,
    evDatabaseURL:
      'https://ev-database.org/car/2209/Mercedes-Benz-EQE-AMG-53-4MATICplus',
    drive: 'AWD',
    power: 504,
    timeToCharge10T080: 28,
  },
  {
    make: 'Mercedes-Benz',
    model: 'EQE SUV',
    subModel: '350 4MATIC',
    heroImageName: 'mercedes-eqe-suv-alt',
    price: 13_890_000,
    sellerURL: 'https://www.mercedes-benz.is/models/eqe-suv/',
    acceleration: 6.6,
    capacity: 90.6,
    range: 551,
    evDatabaseURL:
      'https://ev-database.org/car/2047/Mercedes-Benz-EQE-SUV-350-4MATIC',
    drive: 'AWD',
    power: 215,
    timeToCharge10T080: 33,
  },
  {
    make: 'Mercedes-Benz',
    model: 'EQE SUV',
    subModel: '500 4MATIC',
    heroImageName: 'mercedes-eqe-suv-alt2',
    price: 15_990_000,
    sellerURL: 'https://www.mercedes-benz.is/models/eqe-suv/',
    acceleration: 4.9,
    capacity: 90.6,
    range: 552,
    evDatabaseURL:
      'https://ev-database.org/car/2048/Mercedes-Benz-EQE-SUV-500-4MATIC',
    drive: 'AWD',
    power: 300,
    timeToCharge10T080: 28,
  },
  {
    make: 'Mercedes-Benz',
    model: 'EQE SUV',
    subModel: 'AMG 43 4MATIC',
    heroImageName: 'mercedes-eqe-suv-amg',
    price: 20_990_000,
    sellerURL: 'https://www.mercedes-benz.is/models/eqe-suv/',
    acceleration: 4.3,
    capacity: 90.6,
    range: 476,
    evDatabaseURL:
      'https://ev-database.org/car/1763/Mercedes-EQE-SUV-AMG-43-4MATIC',
    drive: 'AWD',
    power: 350,
    timeToCharge10T080: 28,
  },
  {
    make: 'Mercedes-Benz',
    model: 'EQE SUV',
    subModel: 'AMG 53 4MATIC',
    heroImageName: 'mercedes-eqe-suv-amg-alt',
    price: 25_490_000,
    sellerURL: 'https://www.mercedes-benz.is/models/eqe-suv/',
    acceleration: 3.7,
    capacity: 90.6,
    range: 450,
    evDatabaseURL:
      'https://ev-database.org/car/1764/Mercedes-EQE-SUV-AMG-53-4MATICplus',
    drive: 'AWD',
    power: 460,
    timeToCharge10T080: 28,
  },
  {
    make: 'Mercedes-Benz',
    model: 'EQS',
    subModel: '450+',
    heroImageName: 'mercedes-eqs',
    price: 19890000,
    sellerURL:
      'https://www.mercedes-benz.is/passengercars/mercedes-benz-cars/models/eqs',
    acceleration: 6.2,
    capacity: 108,
    range: 780,
    evDatabaseURL: 'https://ev-database.org/car/1483/Mercedes-EQS-450plus',
    drive: 'RWD',
    power: 245,
    timeToCharge10T080: 32,
    discontinued: '2024-07-13',
  },
  {
    make: 'Mercedes-Benz',
    model: 'EQS',
    subModel: '450 4MATIC',
    heroImageName: 'mercedes-eqs-alt',
    price: 20490000,
    sellerURL:
      'https://www.mercedes-benz.is/passengercars/mercedes-benz-cars/models/eqs',
    acceleration: 5.6,
    capacity: 108,
    range: 719,
    evDatabaseURL: 'https://ev-database.org/car/1699/Mercedes-EQS-450-4MATIC',
    drive: 'AWD',
    power: 265,
    timeToCharge10T080: 32,
    discontinued: '2024-07-13',
  },
  {
    make: 'Mercedes-Benz',
    model: 'EQS',
    subModel: '580 4MATIC',
    heroImageName: 'mercedes-eqs',
    price: 25990000,
    sellerURL:
      'https://www.mercedes-benz.is/passengercars/mercedes-benz-cars/models/eqs',
    acceleration: 4.3,
    capacity: 108,
    range: 717,
    evDatabaseURL: 'https://ev-database.org/car/1483/Mercedes-EQS-450plus',
    drive: 'AWD',
    power: 385,
    timeToCharge10T080: 32,
    discontinued: '2024-07-13',
  },
  {
    make: 'Mercedes-Benz',
    model: 'EQS',
    subModel: 'AMG 53 4MATIC',
    heroImageName: 'mercedes-eqs-alt',
    price: 29990000,
    sellerURL:
      'https://www.mercedes-benz.is/passengercars/mercedes-benz-cars/models/eqs',
    acceleration: 3.4,
    capacity: 108,
    range: 574,
    evDatabaseURL:
      'https://ev-database.org/car/1537/Mercedes-EQS-AMG-53-4MATICplus',
    drive: 'AWD',
    power: 560,
    timeToCharge10T080: 32,
    discontinued: '2024-07-13',
  },
  {
    make: 'Mercedes-Benz',
    model: 'EQS SUV',
    subModel: '450 4MATIC',
    heroImageName: 'mercedes-eqs-suv',
    price: 18_490_000,
    sellerURL: 'https://www.mercedes-benz.is/models/eqs-suv/',
    acceleration: 5.8,
    capacity: 108,
    range: 616,
    evDatabaseURL:
      'https://ev-database.org/car/1674/Mercedes-EQS-SUV-450-4MATIC',
    drive: 'AWD',
    power: 265,
    timeToCharge10T080: 32,
  },
  {
    make: 'Mercedes-Benz',
    model: 'EQS SUV',
    subModel: '580 4MATIC',
    heroImageName: 'mercedes-eqs-suv',
    price: 24_990_000,
    sellerURL: 'https://www.mercedes-benz.is/models/eqs-suv/',
    acceleration: 4.7,
    capacity: 108,
    range: 615,
    evDatabaseURL:
      'https://ev-database.org/car/2090/Mercedes-Benz-EQS-SUV-580-4MATIC',
    drive: 'AWD',
    power: 400,
    timeToCharge10T080: 32,
  },
  {
    make: 'Mercedes-Benz',
    model: 'EQT',
    subModel: '200',
    heroImageName: 'mercedes-eqt',
    price: 7_890_000,
    sellerURL: 'https://www.mercedes-benz.is/models/eqt/',
    acceleration: 12.6,
    capacity: 48.0,
    range: 282,
    evDatabaseURL:
      'https://ev-database.org/car/1908/Mercedes-Benz-EQT-200-Standard',
    drive: 'FWD',
    power: 90,
    timeToCharge10T080: 40,
  },
  {
    make: 'Mercedes-Benz',
    model: 'EQV',
    subModel: '300',
    heroImageName: 'eqv',
    price: 14_890_000,
    sellerURL:
      'https://www.mercedes-benz.is/passengercars/mercedes-benz-cars/models/v-class/v-class-447/eqv/labeling.module.html',
    acceleration: 12.1,
    capacity: 90,
    range: 363,
    evDatabaseURL: 'https://ev-database.org/car/1240/Mercedes-EQV-300-Long',
    drive: 'FWD',
    power: 150,
    timeToCharge10T080: 47,
  },
  {
    make: 'Mercedes-Benz',
    model: 'eVito',
    subModel: 'Tourer',
    heroImageName: 'mercedes-evito-tourer',
    price: 13_390_000,
    sellerURL:
      'https://www.mercedes-benz.is/passengercars/mercedes-benz-cars/brochures-pricelists/teaser/_jcr_content/par/productinfotextimage/interactions.attachments.16.eVito_verdlisti.pdf',
    acceleration: 12.1,
    capacity: 90,
    range: 361,
    evDatabaseURL:
      'https://ev-database.org/car/1615/Mercedes-eVito-Tourer-Long-90-kWh',
    drive: 'FWD',
    power: 150,
    timeToCharge10T080: 47,
  },
  {
    make: 'MG',
    model: 'Marvel R',
    heroImageName: 'mg-marvel-r',
    price: 6_590_000,
    sellerURL: 'https://mgmotor.eu/is-IS/model/marvel-r',
    acceleration: 7.9,
    capacity: 70,
    range: 402,
    evDatabaseURL: 'https://ev-database.org/car/1524/MG-Marvel-R',
    drive: 'RWD',
    power: 132,
    timeToCharge10T080: 36,
  },
  {
    make: 'MG',
    model: 'Marvel R',
    subModel: 'Performance',
    heroImageName: 'mg-marvel-r-alt',
    price: 7_390_000,
    sellerURL: 'https://mgmotor.eu/is-IS/model/marvel-r',
    acceleration: 4.9,
    capacity: 70,
    range: 370,
    evDatabaseURL: 'https://ev-database.org/car/1475/MG-Marvel-R-Performance',
    drive: 'AWD',
    power: 212,
    timeToCharge10T080: 36,
  },
  {
    make: 'MG',
    model: 'MG4',
    subModel: 'Standard',
    heroImageName: 'mg-mg4',
    price: 5490000,
    sellerURL: 'https://www.mgmotor.eu/is-IS/model/mg4',
    acceleration: 7.7,
    capacity: 51,
    range: 350,
    evDatabaseURL: 'https://ev-database.org/car/1707/MG-MG4-Electric-51-kWh',
    drive: 'RWD',
    power: 125,
    timeToCharge10T080: 32,
  },
  {
    make: 'MG',
    model: 'MG4',
    subModel: 'Luxury',
    heroImageName: 'mg-mg4-alt',
    price: 6790000,
    sellerURL: 'https://www.mgmotor.eu/is-IS/model/mg4',
    acceleration: 7.9,
    capacity: 64,
    range: 435,
    evDatabaseURL: 'https://ev-database.org/car/1708/MG-MG4-Electric-64-kWh',
    drive: 'RWD',
    power: 150,
    timeToCharge10T080: 24,
  },
  {
    make: 'MG',
    model: 'MG4',
    subModel: 'Trophy Extended Range',
    heroImageName: 'mg-mg4-alt2',
    price: 7390000,
    sellerURL: 'https://www.mgmotor.eu/is-IS/model/mg4',
    acceleration: 6.5,
    capacity: 77,
    range: 520,
    evDatabaseURL: 'https://ev-database.org/car/1973/MG-MG4-Electric-77-kWh',
    drive: 'RWD',
    power: 180,
    timeToCharge10T080: 41,
  },
  {
    make: 'MG',
    model: 'MG4',
    subModel: 'XPOWER',
    heroImageName: 'mg-mg4-xpower',
    price: 7690000,
    sellerURL: 'https://www.mgmotor.eu/is-IS/model/mg4',
    acceleration: 3.8,
    capacity: 64,
    range: 435,
    evDatabaseURL: 'https://ev-database.org/car/1944/MG-MG4-Electric-XPOWER',
    drive: 'AWD',
    power: 320,
    timeToCharge10T080: 24,
  },
  {
    make: 'MG',
    model: 'MG5',
    subModel: 'Long Range',
    heroImageName: 'mg-mg5',
    price: 7290000,
    sellerURL: 'https://mgmotor.eu/is-IS/model/mg5',
    acceleration: 8.3,
    capacity: 61.1,
    range: 400,
    evDatabaseURL: 'https://ev-database.org/car/1474/MG-MG5-Electric',
    drive: 'FWD',
    power: 115,
    timeToCharge10T080: 42,
  },
  {
    make: 'MG',
    model: 'ZS',
    subModel: 'Standard Range',
    heroImageName: 'mg-zs-ev-2022',
    price: 5990000,
    sellerURL: 'https://mgmotor.eu/is-IS/model/zs-ev',
    acceleration: 8.6,
    capacity: 50.3,
    range: 320,
    evDatabaseURL: 'https://ev-database.org/car/1540/MG-ZS-EV-Standard-Range',
    drive: 'FWD',
    power: 130,
    timeToCharge10T080: 43,
  },
  {
    make: 'MG',
    model: 'ZS',
    subModel: 'Long Range',
    heroImageName: 'mg-zs-ev-2022-alt',
    price: 7_190_000,
    sellerURL: 'https://mgmotor.eu/is-IS/model/zs-ev',
    acceleration: 8.4,
    capacity: 73,
    range: 440,
    evDatabaseURL: 'https://ev-database.org/car/1541/MG-ZS-EV-Long-Range',
    drive: 'FWD',
    power: 115,
    timeToCharge10T080: 43,
  },
  {
    make: 'Mini Cooper',
    model: 'SE',
    heroImageName: 'mini',
    price: 5990000,
    sellerURL: 'https://www.mini.is/is_IS/home/range/electric.html',
    acceleration: 7.3,
    capacity: 33.0,
    range: 232,
    evDatabaseURL: 'https://ev-database.org/car/1409/Mini-Cooper-SE',
    drive: 'FWD',
    power: 135,
    timeToCharge10T080: 29,
    discontinued: '2024-04-01',
  },
  {
    make: 'Mini',
    model: 'Countryman',
    subModel: 'E',
    heroImageName: 'mini-countryman-e',
    price: 8_890_000,
    sellerURL:
      'https://issuu.com/hallih/docs/mini_ver__listi_09.10.2017lr?e=5814949/54144288',
    acceleration: 8.6,
    capacity: 66.5,
    range: 462,
    evDatabaseURL: 'https://ev-database.org/car/1994/Mini-Countryman-E',
    drive: 'FWD',
    power: 150,
    timeToCharge10T080: 30,
  },
  {
    make: 'Mini',
    model: 'Countryman',
    subModel: 'SE 4x4',
    heroImageName: 'mini-countryman-se',
    price: 9_690_000,
    sellerURL:
      'https://issuu.com/hallih/docs/mini_ver__listi_09.10.2017lr?e=5814949/54144288',
    acceleration: 5.6,
    capacity: 66.5,
    range: 432,
    evDatabaseURL: 'https://ev-database.org/car/1995/Mini-Countryman-SE-ALL4',
    drive: 'AWD',
    power: 230,
    timeToCharge10T080: 30,
  },
  {
    make: 'Nissan',
    model: 'Ariya',
    subModel: '63 kWh',
    heroImageName: 'nissan-ariya',
    price: 7_790_000,
    sellerURL: 'https://www.nissan.is/vehicles/new-vehicles/ariya.html',
    acceleration: 7.5,
    capacity: 63,
    range: 403,
    evDatabaseURL: 'https://ev-database.org/car/1301/Nissan-Ariya-63kWh',
    drive: 'FWD',
    power: 160,
    timeToCharge10T080: 31,
  },
  {
    make: 'Nissan',
    model: 'Ariya',
    subModel: '87 kWh',
    heroImageName: 'nissan-ariya-alt',
    price: 8_990_000,
    sellerURL: 'https://www.nissan.is/vehicles/new-vehicles/ariya.html',
    acceleration: 7.6,
    capacity: 87,
    range: 530,
    evDatabaseURL: 'https://ev-database.org/car/1302/Nissan-Ariya-87kWh',
    drive: 'FWD',
    power: 178,
    timeToCharge10T080: 35,
  },
  {
    make: 'Nissan',
    model: 'Ariya',
    subModel: 'e-4ORCE',
    heroImageName: 'nissan-ariya',
    price: 9_490_000,
    sellerURL: 'https://www.nissan.is/vehicles/new-vehicles/ariya.html',
    acceleration: 5.7,
    capacity: 87,
    range: 500,
    evDatabaseURL:
      'https://ev-database.org/car/1304/Nissan-Ariya-e-4ORCE-87kWh',
    drive: 'AWD',
    power: 225,
    timeToCharge10T080: 35,
  },
  {
    make: 'Nissan',
    model: 'Leaf',
    heroImageName: 'leaf',
    price: 5990000,
    sellerURL: 'https://www.nissan.is/vehicles/new-vehicles/leaf-vlp-2022.html',
    acceleration: 7.9,
    capacity: 40,
    range: 270,
    evDatabaseURL: 'https://ev-database.org/car/1106/Nissan-Leaf',
    drive: 'FWD',
    power: 110,
    timeToCharge10T080: 40,
  },
  {
    make: 'Nissan',
    model: 'Leaf',
    subModel: 'e+',
    heroImageName: 'leaf-eplus',
    price: 7990000,
    sellerURL: 'https://www.nissan.is/vehicles/new-vehicles/leaf-vlp-2022.html',
    acceleration: 7.3,
    capacity: 62,
    range: 385,
    evDatabaseURL: 'https://ev-database.org/car/1144/Nissan-Leaf-eplus',
    drive: 'FWD',
    power: 160,
    timeToCharge10T080: 35,
  },
  {
    make: 'Opel',
    model: 'Corsa',
    subModel: '50 kWh',
    heroImageName: 'opel-corsa',
    price: 5_690_000,
    sellerURL:
      'https://www.opelisland.is/bilar/corsa-tegundir/corsa-e/yfirsyn.html',
    acceleration: 8.7,
    capacity: 50,
    range: 354,
    evDatabaseURL:
      'https://ev-database.org/car/1941/Opel-Corsa-Electric-50-kWh',
    drive: 'FWD',
    power: 100,
    timeToCharge10T080: 26,
  },
  {
    make: 'Opel',
    model: 'Corsa',
    subModel: '51 kWh',
    heroImageName: 'opel-corsa-alt',
    price: 6_590_000,
    sellerURL:
      'https://www.opelisland.is/bilar/corsa-tegundir/corsa-e/yfirsyn.html',
    acceleration: 8.1,
    capacity: 51,
    range: 406,
    evDatabaseURL:
      'https://ev-database.org/car/1942/Opel-Corsa-Electric-51-kWh',
    drive: 'FWD',
    power: 115,
    timeToCharge10T080: 27,
  },
  {
    make: 'Opel',
    model: 'Mokka-e',
    heroImageName: 'opel-mokka-e',
    price: 6_390_000,
    sellerURL:
      'https://www.opelisland.is/cars/mokka-models/mokka-e/Yfirsyn.html',
    acceleration: 9.0,
    capacity: 54,
    range: 406,
    evDatabaseURL: 'https://ev-database.org/car/2051/Opel-Mokka-e-54-kWh',
    drive: 'FWD',
    power: 115,
    timeToCharge10T080: 26,
  },
  {
    make: 'Opel',
    model: 'Combo-e',
    heroImageName: 'opel-combo',
    price: 6990000,
    sellerURL:
      'https://www.opelisland.is/bilar/Combo-e-Life-tegundir/combo-e-life/yfirsyn.html',
    acceleration: 11.7,
    capacity: 50,
    range: 285,
    evDatabaseURL: 'https://ev-database.org/car/1544/Opel-Combo-e-Life-50-kWh',
    drive: 'FWD',
    power: 100,
    timeToCharge10T080: 26,
  },
  {
    make: 'Opel',
    model: 'Zafira-e',
    heroImageName: 'opel-zafira',
    price: 9490000,
    sellerURL: 'https://www.opelisland.is/bilar/zafira-tegundir/yfirsyn.html',
    acceleration: 13.3,
    capacity: 75,
    range: 330,
    evDatabaseURL:
      'https://ev-database.org/car/1349/Opel-Zafira-e-Life-L-75-kWh',
    drive: 'FWD',
    power: 100,
    timeToCharge10T080: 38,
    discontinued: '2024-09-29',
  },
  {
    make: 'GWM',
    model: 'Ora 3',
    subModel: '48 kWh',
    heroImageName: 'ora-funky-cat',
    price: 5890000,
    sellerURL: 'https://www.gwmora.is/',
    acceleration: 8.3,
    capacity: 48,
    range: 310,
    evDatabaseURL: 'https://ev-database.org/car/2091/GWM-ORA-3-48-kWh',
    drive: 'FWD',
    power: 126,
    timeToCharge10T080: 45,
  },
  {
    make: 'Peugeot',
    model: 'e-2008',
    subModel: '50 kWh',
    heroImageName: 'peugeot-2008',
    price: 6_390_000,
    sellerURL: 'https://www.peugeotisland.is/tegundir/Nyr-e-2008.html',
    acceleration: 9.9,
    capacity: 50,
    range: 345,
    evDatabaseURL: 'https://ev-database.org/car/1946/Peugeot-e-2008-50-kWh',
    drive: 'FWD',
    power: 100,
    timeToCharge10T080: 26,
  },
  {
    make: 'Peugeot',
    model: 'e-2008',
    subModel: '54 kWh',
    heroImageName: 'peugeot-2008-alt',
    price: 6_630_000,
    sellerURL: 'https://www.peugeotisland.is/tegundir/Nyr-e-2008.html',
    acceleration: 9.1,
    capacity: 54,
    range: 406,
    evDatabaseURL: 'https://ev-database.org/car/1947/Peugeot-e-2008-54-kWh',
    drive: 'FWD',
    power: 115,
    timeToCharge10T080: 26,
  },
  {
    make: 'Peugeot',
    model: 'e-208',
    subModel: '50 kWh',
    heroImageName: 'peugeot-208',
    price: 5790000,
    sellerURL: 'https://www.peugeotisland.is/tegundir/E-208.html',
    acceleration: 9.0,
    capacity: 46.3,
    range: 362,
    evDatabaseURL: 'https://ev-database.org/car/1948/Peugeot-e-208-50-kWh',
    drive: 'FWD',
    power: 100,
    timeToCharge10T080: 26,
  },
  {
    make: 'Peugeot',
    model: 'e-208',
    subModel: '51 kWh',
    heroImageName: 'peugeot-208',
    price: 5990000,
    sellerURL: 'https://www.peugeotisland.is/tegundir/E-208.html',
    acceleration: 8.2,
    capacity: 51,
    range: 409,
    evDatabaseURL: 'https://ev-database.org/car/1949/Peugeot-e-208-51-kWh',
    drive: 'FWD',
    power: 115,
    timeToCharge10T080: 27,
  },
  {
    make: 'Peugeot',
    model: 'e-3008',
    heroImageName: 'peugeot-e-3008',
    price: 8_190_000,
    sellerURL: 'https://www.peugeotisland.is/tegundir/e-3008.html',
    acceleration: 7.0,
    capacity: 73,
    range: 525,
    evDatabaseURL: 'https://ev-database.org/car/2003/Peugeot-e-3008-73-kWh',
    drive: 'FWD',
    power: 157,
    timeToCharge10T080: 36,
  },
  {
    make: 'Peugeot',
    model: 'e-3008',
    subModel: 'Dual Motor',
    heroImageName: 'peugeot-e-3008-alt',
    price: 9_000_000,
    sellerURL: 'https://www.peugeotisland.is/tegundir/e-3008.html',
    acceleration: 6.0,
    capacity: 73,
    range: 525,
    evDatabaseURL:
      'https://ev-database.org/car/2004/Peugeot-e-3008-73-kWh-Dual-Motor',
    drive: 'AWD',
    power: 240,
    timeToCharge10T080: 36,
    expectedDelivery: '2025',
  },
  {
    make: 'Peugeot',
    model: 'e-3008',
    heroImageName: 'peugeot-e-3008',
    subModel: 'Long Range',
    price: 9500000,
    sellerURL: 'https://www.peugeotisland.is/tegundir/e-3008.html',
    acceleration: 7.0,
    capacity: 98,
    range: 700,
    evDatabaseURL:
      'https://ev-database.org/car/2005/Peugeot-e-3008-98-kWh-Long-Range',
    drive: 'FWD',
    power: 170,
    timeToCharge10T080: 32,
    expectedDelivery: '2025',
  },
  {
    make: 'Peugeot',
    model: 'e-Rifter',
    heroImageName: 'peugeot-e-rifter',
    price: 7_190_000,
    sellerURL: 'https://www.peugeotisland.is/tegundir/E-Rifter.html',
    acceleration: 11.7,
    capacity: 54,
    range: 343,
    evDatabaseURL: 'https://ev-database.org/car/2163/Peugeot-e-Rifter-M-50-kWh',
    drive: 'FWD',
    power: 100,
    timeToCharge10T080: 28,
  },
  {
    make: 'Peugeot',
    model: 'e-Traveller',
    heroImageName: 'peugeot-e-traveller',
    price: 9490000,
    sellerURL: 'https://www.peugeotisland.is/nyir-bilar/sko/e-traveller/',
    acceleration: 13.3,
    capacity: 75,
    range: 330,
    evDatabaseURL:
      'https://ev-database.org/car/1353/Peugeot-e-Traveller-Standard-75-kWh',
    drive: 'FWD',
    power: 100,
    timeToCharge10T080: 38,
    discontinued: '2024-07-13',
  },
  {
    make: 'Polestar',
    model: '2',
    subModel: 'Long Range Dual Motor',
    heroImageName: 'polestar-2-alt2',
    price: 7590000,
    sellerURL: 'https://www.polestar.com/en-is/polestar-2/',
    acceleration: 4.7,
    capacity: 78,
    range: 482,
    evDatabaseURL:
      'https://ev-database.org/car/1488/Polestar-2-Long-Range-Dual-Motor',
    drive: 'AWD',
    power: 300,
    timeToCharge10T080: 32,
    discontinued: '2024-01-01',
  },
  {
    make: 'Polestar',
    model: '2',
    subModel: 'Long Range Dual Motor Performance',
    heroImageName: 'polestar-2',
    price: 8590000,
    sellerURL: 'https://www.polestar.com/en-is/polestar-2/',
    acceleration: 4.4,
    capacity: 78,
    range: 468,
    evDatabaseURL:
      'https://ev-database.org/car/1777/Polestar-2-Long-Range-Performance',
    drive: 'AWD',
    power: 350,
    timeToCharge10T080: 32,
    discontinued: '2024-01-01',
  },
  // {
  //   make: 'Polestar',
  //   model: '2',
  //   subModel: '2024 Standard Range Single Motor',
  //   heroImageName: 'polestar-2-2024',
  //   price: 9000000,
  //   sellerURL: 'https://www.polestar.com/en-is/polestar-2/',
  //   acceleration: 6.4,
  //   capacity: 69,
  //   range: 518,
  //   evDatabaseURL:
  //     'https://ev-database.org/car/1817/Polestar-2-Standard-Range-Single-Motor',
  //   drive: 'RWD',
  //   power: 200,
  //   timeToCharge10T080: 26,
  //   expectedDelivery: '2024',
  // },
  {
    make: 'Polestar',
    model: '2',
    subModel: '2024 Long Range Single Motor',
    heroImageName: 'polestar-2-2024-alt',
    price: 9_290_000,
    sellerURL: 'https://www.polestar.com/en-is/polestar-2/',
    acceleration: 6.2,
    capacity: 82,
    range: 655,
    evDatabaseURL:
      'https://ev-database.org/car/1818/Polestar-2-Long-Range-Single-Motor',
    drive: 'RWD',
    power: 220,
    timeToCharge10T080: 27,
  },
  {
    make: 'Polestar',
    model: '2',
    subModel: '2024 Long Range Dual Motor',
    heroImageName: 'polestar-2-2024-alt2',
    price: 9_890_000,
    sellerURL: 'https://www.polestar.com/en-is/polestar-2/',
    acceleration: 4.5,
    capacity: 82,
    range: 592,
    evDatabaseURL:
      'https://ev-database.org/car/1819/Polestar-2-Long-Range-Dual-Motor',
    drive: 'AWD',
    power: 310,
    timeToCharge10T080: 27,
  },
  {
    make: 'Polestar',
    model: '2',
    subModel: '2024 Long Range Dual Motor Performance',
    heroImageName: 'polestar-2-2024',
    price: 10_790_000,
    sellerURL: 'https://www.polestar.com/en-is/polestar-2/',
    acceleration: 4.2,
    capacity: 82,
    range: 568,
    evDatabaseURL:
      'https://ev-database.org/car/1820/Polestar-2-Long-Range-Performance',
    drive: 'AWD',
    power: 350,
    timeToCharge10T080: 27,
  },
  {
    make: 'Polestar',
    model: '3',
    heroImageName: 'polestar-3',
    price: 15_790_000,
    sellerURL: 'https://www.polestar.com/en-is/polestar-3/',
    acceleration: 5,
    capacity: 111,
    range: 610,
    evDatabaseURL:
      'https://ev-database.org/car/1758/Polestar-3-Long-Range-Dual-motor',
    drive: 'AWD',
    power: 360,
    timeToCharge10T080: 32,
  },
  {
    make: 'Polestar',
    model: '3',
    subModel: 'Performance',
    heroImageName: 'polestar-3-alt',
    price: 16_590_000,
    sellerURL: 'https://www.polestar.com/en-is/polestar-3/',
    acceleration: 4.7,
    capacity: 111,
    range: 560,
    evDatabaseURL:
      'https://ev-database.org/car/1759/Polestar-3-Long-Range-Performance',
    drive: 'AWD',
    power: 380,
    timeToCharge10T080: 32,
  },
  // {
  //   make: 'Polestar',
  //   model: '4',
  //   subModel: 'Long Range Single Motor',
  //   heroImageName: 'polestar-4',
  //   price: 10_000_000,
  //   sellerURL: 'https://www.polestar.com/en-is/polestar-4/',
  //   acceleration: 7.4,
  //   capacity: 100,
  //   range: 610,
  //   evDatabaseURL:
  //     'https://ev-database.org/car/1841/Polestar-4-Long-Range-Single-Motor',
  //   drive: 'RWD',
  //   power: 200,
  //   timeToCharge10T080: 31,
  //   expectedDelivery: 'Lok 2024',
  // },
  {
    make: 'Polestar',
    model: '4',
    subModel: 'Long Range Dual Motor',
    heroImageName: 'polestar-4-alt',
    price: 12_490_000,
    sellerURL: 'https://www.polestar.com/en-is/polestar-4/',
    acceleration: 3.8,
    capacity: 100,
    range: 580,
    evDatabaseURL:
      'https://ev-database.org/car/1842/Polestar-4-Long-Range-Dual-Motor',
    drive: 'AWD',
    power: 400,
    timeToCharge10T080: 31,
  },
  {
    make: 'Porsche',
    model: 'Macan',
    subModel: '4 Electric',
    heroImageName: 'porsche-macan',
    price: 14_950_000,
    sellerURL: 'https://www.benni.is/porsche-macan',
    acceleration: 5.2,
    capacity: 100.0,
    range: 613,
    evDatabaseURL: 'https://ev-database.org/car/2084/Porsche-Macan-4-Electric',
    drive: 'AWD',
    power: 300,
    timeToCharge10T080: 21,
  },
  {
    make: 'Porsche',
    model: 'Macan',
    subModel: '4S',
    heroImageName: 'porsche-macan',
    price: 16_790_000,
    sellerURL: 'https://www.benni.is/porsche-macan',
    acceleration: 4.1,
    capacity: 100.0,
    range: 606,
    evDatabaseURL: 'https://ev-database.org/car/2244/Porsche-Macan-4S-Electric',
    drive: 'AWD',
    power: 330,
    timeToCharge10T080: 21,
  },
  {
    make: 'Porsche',
    model: 'Macan',
    subModel: 'Turbo Electric',
    heroImageName: 'porsche-macan-turbo',
    price: 21_750_000,
    sellerURL: 'https://www.benni.is/porsche-macan',
    acceleration: 3.3,
    capacity: 100.0,
    range: 591,
    evDatabaseURL:
      'https://ev-database.org/car/2085/Porsche-Macan-Turbo-Electric',
    drive: 'AWD',
    power: 470,
    timeToCharge10T080: 21,
  },
  {
    make: 'Porsche',
    model: 'Taycan',
    heroImageName: 'porsche-taycan',
    price: 16_950_000,
    sellerURL: 'https://dealer.porsche.com/is/island/is-IS/nyir-bilar/Taycan',
    acceleration: 4.8,
    capacity: 82.3,
    range: 590,
    evDatabaseURL: 'https://ev-database.org/car/2098/Porsche-Taycan',
    drive: 'RWD',
    power: 300,
    timeToCharge10T080: 19,
  },
  {
    make: 'Porsche',
    model: 'Taycan',
    subModel: '4S',
    heroImageName: 'porsche-taycan-4s',
    price: 19_950_000,
    sellerURL: 'https://dealer.porsche.com/is/island/is-IS/nyir-bilar/Taycan',
    acceleration: 3.7,
    capacity: 82.3,
    range: 557,
    evDatabaseURL: 'https://ev-database.org/car/2100/Porsche-Taycan-4S',
    drive: 'AWD',
    power: 400,
    timeToCharge10T080: 19,
  },
  {
    make: 'Porsche',
    model: 'Taycan',
    subModel: 'Sport Turismo',
    heroImageName: 'porsche-taycan-sport-turismo-alt',
    price: 11990000,
    sellerURL: 'https://dealer.porsche.com/is/island/is-IS/nyir-bilar/Taycan',
    acceleration: 5.4,
    capacity: 79.2,
    range: 433,
    evDatabaseURL:
      'https://ev-database.org/car/1621/Porsche-Taycan-Sport-Turismo',
    drive: 'RWD',
    power: 300,
    timeToCharge10T080: 19,
    discontinued: '2024-07-11',
  },
  {
    make: 'Porsche',
    model: 'Taycan',
    subModel: '4 Cross Turismo',
    heroImageName: 'porsche-taycan-cross-turismo',
    price: 18_950_000,
    sellerURL: 'https://dealer.porsche.com/is/island/is-IS/nyir-bilar/Taycan',
    acceleration: 4.7,
    capacity: 97,
    range: 613,
    evDatabaseURL:
      'https://ev-database.org/car/2110/Porsche-Taycan-4-Cross-Turismo',
    drive: 'AWD',
    power: 320,
    timeToCharge10T080: 18,
  },
  {
    make: 'Porsche',
    model: 'Taycan',
    subModel: '4S Cross Turismo',
    heroImageName: 'porsche-taycan-cross-turismo',
    price: 20_950_000,
    sellerURL: 'https://dealer.porsche.com/is/island/is-IS/nyir-bilar/Taycan',
    acceleration: 3.8,
    capacity: 97,
    range: 610,
    evDatabaseURL:
      'https://ev-database.org/car/2111/Porsche-Taycan-4S-Cross-Turismo',
    drive: 'AWD',
    power: 440,
    timeToCharge10T080: 19,
  },
  {
    make: 'Renault',
    model: 'Megane E-Tech',
    subModel: 'EV40',
    heroImageName: 'renault-megane-etech',
    price: 6790000,
    sellerURL:
      'https://www.renault.is/cars/megane-e-tech/megane-e-tech-electric.html',
    acceleration: 10.0,
    capacity: 40,
    range: 300,
    evDatabaseURL:
      'https://ev-database.org/car/1536/Renault-Megane-E-Tech-EV40-130hp',
    drive: 'FWD',
    power: 96,
    timeToCharge10T080: 29,
    discontinued: '2024-04-21',
  },
  {
    make: 'Renault',
    model: 'Megane E-Tech',
    subModel: 'EV60 130hp',
    heroImageName: 'renault-megane-etech',
    price: 7090000,
    sellerURL:
      'https://www.renault.is/cars/megane-e-tech/megane-e-tech-electric.html',
    acceleration: 10.5,
    capacity: 60,
    range: 470,
    evDatabaseURL:
      'https://ev-database.org/car/1588/Renault-Megane-E-Tech-EV60-130hp',
    drive: 'FWD',
    power: 96,
    timeToCharge10T080: 29,
  },
  {
    make: 'Renault',
    model: 'Megane E-Tech',
    subModel: 'EV60 220hp',
    heroImageName: 'renault-megane-etech-alt',
    price: 6990000,
    sellerURL:
      'https://www.renault.is/cars/megane-e-tech/megane-e-tech-electric.html',
    acceleration: 7.4,
    capacity: 60,
    range: 450,
    evDatabaseURL:
      'https://ev-database.org/car/1521/Renault-Megane-E-Tech-EV60-220hp',
    drive: 'FWD',
    power: 160,
    timeToCharge10T080: 29,
  },
  {
    make: 'Renault',
    model: 'Zoe',
    subModel: 'R110',
    heroImageName: 'zoe-r110',
    price: 6890000,
    sellerURL: 'https://www.renault.is/cars/zoe/yfirlit.html',
    acceleration: 11.4,
    capacity: 52,
    range: 395,
    evDatabaseURL: 'https://ev-database.org/car/1164/Renault-Zoe-ZE50-R110',
    drive: 'FWD',
    power: 80,
    timeToCharge10T080: 56,
    discontinued: '2024-08-07',
  },
  {
    make: 'Renault',
    model: 'Zoe',
    subModel: 'R135',
    heroImageName: 'zoe-r135',
    price: 6890000,
    sellerURL: 'https://www.renault.is/cars/zoe/yfirlit.html',
    acceleration: 9.5,
    capacity: 52,
    range: 385,
    evDatabaseURL: 'https://ev-database.org/car/1205/Renault-Zoe-ZE50-R135',
    drive: 'FWD',
    power: 100,
    timeToCharge10T080: 56,
  },
  {
    make: 'Renault',
    model: 'Scenic E-Tech',
    subModel: 'EV60',
    heroImageName: 'renault-scenic',
    price: 8_290_000,
    sellerURL:
      'https://www.renault.is/cars/renault-scenic-e-tech-100-rafmagn/yfirlit.html',
    acceleration: 8.6,
    capacity: 65,
    range: 430,
    evDatabaseURL:
      'https://ev-database.org/car/2068/Renault-Scenic-E-Tech-EV60-170hp',
    drive: 'FWD',
    power: 125,
    timeToCharge10T080: 35,
    expectedDelivery: '2024',
  },
  {
    make: 'Renault',
    model: 'Scenic E-Tech',
    subModel: 'EV87',
    heroImageName: 'renault-scenic-alt',
    price: 9_190_000,
    sellerURL:
      'https://www.renault.is/cars/renault-scenic-e-tech-100-rafmagn/yfirlit.html',
    acceleration: 7.9,
    capacity: 92,
    range: 625,
    evDatabaseURL:
      'https://ev-database.org/car/2069/Renault-Scenic-E-Tech-EV87-220hp',
    drive: 'FWD',
    power: 160,
    timeToCharge10T080: 40,
    expectedDelivery: '2024',
  },
  {
    make: 'Skoda',
    model: 'Enyaq',
    subModel: 'iV 80',
    heroImageName: 'skoda-enyaq-alt',
    price: 8490000,
    sellerURL: 'https://www.skoda.is/models/enyaq/enyaq',
    acceleration: 8.5,
    capacity: 77,
    range: 548,
    evDatabaseURL: 'https://ev-database.org/car/1280/Skoda-Enyaq-iV-80',
    drive: 'RWD',
    power: 150,
    timeToCharge10T080: 33,
    discontinued: '2024-02-04',
  },
  {
    make: 'Skoda',
    model: 'Enyaq',
    subModel: 'iV 85X',
    heroImageName: 'skoda-enyaq',
    price: 8890000,
    sellerURL: 'https://www.skoda.is/models/enyaq/enyaq',
    acceleration: 6.6,
    capacity: 82,
    range: 536,
    evDatabaseURL: 'https://ev-database.org/car/2021/Skoda-Enyaq-85x',
    drive: 'AWD',
    power: 210,
    timeToCharge10T080: 28,
  },
  {
    make: 'Skoda',
    model: 'Enyaq',
    subModel: 'iV 80X Coupé',
    heroImageName: 'skoda-enyaq-coupe-alt',
    price: 9290000,
    sellerURL: 'https://www.skoda.is/models/enyaq/enyaq',
    acceleration: 6.9,
    capacity: 77,
    range: 515,
    evDatabaseURL: 'https://ev-database.org/car/1630/Skoda-Enyaq-Coupe-iV-80x',
    drive: 'AWD',
    power: 195,
    timeToCharge10T080: 34,
    discontinued: '2024-02-04',
  },
  {
    make: 'Skoda',
    model: 'Enyaq',
    subModel: 'Coupé RS',
    heroImageName: 'skoda-enyaq-coupe-rs',
    price: 9590000,
    sellerURL: 'https://www.skoda.is/models/enyaq/enyaq',
    acceleration: 6.5,
    capacity: 77,
    range: 520,
    evDatabaseURL: 'https://ev-database.org/car/1631/Skoda-Enyaq-Coupe-iV-RS',
    drive: 'AWD',
    power: 220,
    timeToCharge10T080: 30,
    discontinued: '2024-02-04',
  },
  {
    make: 'Smart',
    model: '#1',
    subModel: 'Pure',
    heroImageName: 'smart-one',
    price: 5_890_000,
    sellerURL: 'https://smart.askja.is/hashtag-one',
    acceleration: 6.7,
    capacity: 49,
    range: 310,
    evDatabaseURL: 'https://ev-database.org/car/2217/Smart-1-Pure',
    drive: 'RWD',
    power: 200,
    timeToCharge10T080: 27,
    discontinued: '2024-08-07',
  },
  {
    make: 'Smart',
    model: '#1',
    subModel: 'Pro+',
    heroImageName: 'smart-one-alt2',
    price: 5_890_000,
    sellerURL: 'https://smart.askja.is/hashtag-one',
    acceleration: 6.7,
    capacity: 66,
    range: 440,
    evDatabaseURL: 'https://ev-database.org/car/1667/Smart-1',
    drive: 'RWD',
    power: 200,
    timeToCharge10T080: 27,
  },
  {
    make: 'Smart',
    model: '#1',
    subModel: 'Pulse',
    heroImageName: 'smart-one-alt',
    price: 7_290_000,
    sellerURL: 'https://smart.askja.is/hashtag-one',
    acceleration: 4.5,
    capacity: 66,
    range: 400,
    drive: 'AWD',
    power: 315,
    timeToCharge10T080: 27,
    evDatabaseURL: 'https://ev-database.org/car/1920/Smart-1-Pulse',
  },
  {
    make: 'Smart',
    model: '#1',
    subModel: 'Brabus',
    heroImageName: 'smart-one-brabus',
    price: 7_890_000,
    sellerURL: 'https://smart.askja.is/hashtag-one',
    acceleration: 3.9,
    capacity: 66,
    range: 400,
    evDatabaseURL: 'https://ev-database.org/car/1748/Smart-1-Brabus',
    drive: 'AWD',
    power: 315,
    timeToCharge10T080: 27,
  },
  {
    make: 'Smart',
    model: '#3',
    subModel: 'Pro+',
    heroImageName: 'smart-three',
    price: 7_890_000,
    sellerURL: 'https://smart.askja.is/hashtag-three',
    acceleration: 5.8,
    capacity: 66,
    range: 455,
    evDatabaseURL: 'https://ev-database.org/car/1999/Smart-3-Proplus',
    drive: 'RWD',
    power: 200,
    timeToCharge10T080: 27,
    discontinued: '2024-08-07',
  },
  {
    make: 'Smart',
    model: '#3',
    subModel: 'Pulse',
    heroImageName: 'smart-three-alt',
    price: 8_290_000,
    sellerURL: 'https://smart.askja.is/hashtag-three',
    acceleration: 4.7,
    capacity: 66,
    range: 415,
    drive: 'AWD',
    power: 315,
    timeToCharge10T080: 27,
  },
  {
    make: 'Smart',
    model: '#3',
    subModel: 'Brabus',
    heroImageName: 'smart-three-brabus',
    price: 8_890_000,
    sellerURL: 'https://smart.askja.is/hashtag-three',
    acceleration: 3.7,
    capacity: 66,
    range: 415,
    evDatabaseURL: 'https://ev-database.org/car/2000/Smart-3-Brabus',
    drive: 'AWD',
    power: 315,
    timeToCharge10T080: 27,
  },
  {
    make: 'Subaru',
    model: 'Solterra',
    heroImageName: 'subaru-solterra',
    price: 8_190_000,
    sellerURL: 'https://www.subaru.is/solterra.html',
    acceleration: 6.9,
    capacity: 71.4,
    range: 466,
    evDatabaseURL: 'https://ev-database.org/car/1567/Subaru-Solterra-AWD',
    drive: 'AWD',
    power: 160,
    timeToCharge10T080: 28,
  },
  {
    make: 'Tesla',
    model: 'Model 3',
    subModel: 'Afturhjóladrif',
    heroImageName: 'tesla-model-3',
    price: 5_990_000,
    sellerURL: 'https://www.tesla.com/is_IS/model3/design',
    acceleration: 6.1,
    capacity: 60.0,
    range: 513,
    evDatabaseURL: 'https://ev-database.org/car/1991/Tesla-Model-3',
    drive: 'RWD',
    power: 208,
    timeToCharge10T080: 24,
  },
  {
    make: 'Tesla',
    model: 'Model 3',
    subModel: 'Long Range Afturhjóladrif',
    heroImageName: 'tesla-model-3-alt',
    price: 6_690_000,
    sellerURL: 'https://www.tesla.com/is_IS/model3/design',
    acceleration: 5.2,
    capacity: 78.1,
    range: 702,
    evDatabaseURL:
      'https://ev-database.org/car/3034/Tesla-Model-3-Long-Range-RWD',
    drive: 'RWD',
    power: 208,
    timeToCharge10T080: 27,
  },
  {
    make: 'Tesla',
    model: 'Model 3',
    subModel: 'Long Range Fjórhjóladrif',
    heroImageName: 'tesla-model-3',
    price: 7_290_000,
    sellerURL: 'https://www.tesla.com/is_IS/model3/design',
    acceleration: 4.4,
    capacity: 78.1,
    range: 629,
    evDatabaseURL:
      'https://ev-database.org/car/1992/Tesla-Model-3-Long-Range-Dual-Motor',
    drive: 'AWD',
    power: 366,
    timeToCharge10T080: 27,
  },
  {
    make: 'Tesla',
    model: 'Model 3',
    subModel: 'Performance',
    heroImageName: 'tesla-model-3-performance',
    price: 8_167_502,
    sellerURL: 'https://www.tesla.com/is_IS/model3/design',
    acceleration: 3.1,
    capacity: 78.1,
    range: 528,
    evDatabaseURL: 'https://ev-database.org/car/2188/Tesla-Model-3-Performance',
    drive: 'AWD',
    power: 461,
    timeToCharge10T080: 27,
  },
  {
    make: 'Tesla',
    model: 'Model S',
    subModel: 'Long Range',
    heroImageName: 'tesla-model-s',
    price: 14_590_740,
    sellerURL: 'https://www.tesla.com/is_IS/models/design',
    acceleration: 3.2,
    capacity: 100,
    range: 634,
    evDatabaseURL: 'https://ev-database.org/car/1404/Tesla-Model-S-Long-Range',
    drive: 'AWD',
    power: 500,
    timeToCharge10T080: 23,
  },
  {
    make: 'Tesla',
    model: 'Model S',
    subModel: 'Plaid',
    heroImageName: 'tesla-model-s-alt',
    price: 16_711_140,
    sellerURL: 'https://www.tesla.com/is_IS/models/design',
    acceleration: 2.1,
    capacity: 100,
    range: 600,
    evDatabaseURL: 'https://ev-database.org/car/1405/Tesla-Model-S-Plaid',
    drive: 'AWD',
    power: 760,
    timeToCharge10T080: 30,
  },
  {
    make: 'Tesla',
    model: 'Model Y',
    subModel: 'Standard Range',
    heroImageName: 'tesla-model-y',
    price: 6_890_000,
    sellerURL: 'https://www.tesla.com/is_is/modely/design',
    acceleration: 6.9,
    capacity: 60,
    range: 455,
    evDatabaseURL: 'https://ev-database.org/car/1743/Tesla-Model-Y',
    drive: 'RWD',
    power: 220,
    timeToCharge10T080: 25,
  },
  {
    make: 'Tesla',
    model: 'Model Y',
    subModel: 'Long Range',
    heroImageName: 'tesla-model-y-alt',
    price: 7_490_001,
    sellerURL: 'https://www.tesla.com/is_is/modely/design',
    acceleration: 5.9,
    capacity: 78,
    range: 600,
    evDatabaseURL:
      'https://ev-database.org/car/2186/Tesla-Model-Y-Long-Range-RWD',
    drive: 'RWD',
    power: 250,
    timeToCharge10T080: 27,
  },
  {
    make: 'Tesla',
    model: 'Model Y',
    subModel: 'Long Range Dual Motor',
    heroImageName: 'tesla-model-y',
    price: 7_890_000,
    sellerURL: 'https://www.tesla.com/is_is/modely/design',
    acceleration: 5.0,
    capacity: 78,
    range: 533,
    evDatabaseURL:
      'https://ev-database.org/car/1619/Tesla-Model-Y-Long-Range-Dual-Motor',
    drive: 'AWD',
    power: 324,
    timeToCharge10T080: 27,
  },
  {
    make: 'Tesla',
    model: 'Model Y',
    subModel: 'Performance',
    heroImageName: 'tesla-model-y-performance',
    price: 8_390_000,
    sellerURL: 'https://www.tesla.com/is_is/modely/design',
    acceleration: 3.7,
    capacity: 78,
    range: 514,
    evDatabaseURL: 'https://ev-database.org/car/1183/Tesla-Model-Y-Performance',
    drive: 'AWD',
    power: 413,
    timeToCharge10T080: 27,
  },
  {
    make: 'Tesla',
    model: 'Model X',
    subModel: 'Long Range',
    heroImageName: 'tesla-model-x',
    price: 15_371_940,
    sellerURL: 'https://www.tesla.com/is_IS/modelx/design',
    acceleration: 3.9,
    capacity: 100,
    range: 576,
    evDatabaseURL: 'https://ev-database.org/car/1407/Tesla-Model-X-Long-Range',
    drive: 'AWD',
    power: 500,
    timeToCharge10T080: 23,
  },
  {
    make: 'Tesla',
    model: 'Model X',
    subModel: 'Plaid',
    heroImageName: 'tesla-model-x-alt',
    price: 17_517_140,
    sellerURL: 'https://www.tesla.com/is_IS/modelx/design',
    acceleration: 2.6,
    capacity: 100,
    range: 528,
    evDatabaseURL: 'https://ev-database.org/car/1408/Tesla-Model-X-Plaid',
    drive: 'AWD',
    power: 760,
    timeToCharge10T080: 30,
  },
  {
    make: 'Toyota',
    model: 'bZ4X',
    heroImageName: 'toyota-bz4x',
    price: 8690000,
    sellerURL: 'https://www.toyota.is/new-cars/bz4x',
    acceleration: 7.5,
    capacity: 71.4,
    range: 516,
    evDatabaseURL: 'https://ev-database.org/car/1564/Toyota-bZ4X-FWD',
    drive: 'FWD',
    power: 150,
    timeToCharge10T080: 28,
  },
  {
    make: 'Toyota',
    model: 'bZ4X',
    heroImageName: 'toyota-bz4x-alt',
    price: 9190000,
    sellerURL: 'https://www.toyota.is/new-cars/bz4x',
    acceleration: 6.9,
    capacity: 71.4,
    range: 461,
    evDatabaseURL: 'https://ev-database.org/car/1565/Toyota-bZ4X-AWD',
    drive: 'AWD',
    power: 160,
    timeToCharge10T080: 28,
  },
  {
    make: 'Toyota',
    model: 'Proace City Verso',
    heroImageName: 'toyota-proace-city-verso',
    price: 8_960_000,
    sellerURL: 'https://www.toyota.is/new-cars/proace-city-verso',
    acceleration: 11.7,
    capacity: 50,
    range: 345,
    evDatabaseURL:
      'https://ev-database.org/car/2165/Toyota-Proace-City-Verso-Electric-L1-50-kWh',
    drive: 'FWD',
    power: 100,
    timeToCharge10T080: 30,
  },
  {
    make: 'Toyota',
    model: 'Proace Verso',
    heroImageName: 'toyota-proace-verso',
    price: 11_490_000,
    sellerURL: 'https://www.toyota.is/new-cars/proace-verso',
    acceleration: 13.3,
    capacity: 75,
    range: 351,
    evDatabaseURL:
      'https://ev-database.org/car/2266/Toyota-PROACE-Verso-M-75-kWh',
    drive: 'FWD',
    power: 100,
    timeToCharge10T080: 36,
  },
  {
    make: 'Volkswagen',
    model: 'e-Up!',
    heroImageName: 'e-up',
    price: 4_890_000,
    sellerURL: 'https://www.volkswagen.is/is/bilar/e-Up-new.html',
    acceleration: 11.9,
    capacity: 32.3,
    range: 260,
    evDatabaseURL: 'https://ev-database.org/car/1189/Volkswagen-e-Up',
    drive: 'FWD',
    power: 61,
    timeToCharge10T080: 48,
  },
  {
    make: 'Volkswagen',
    model: 'ID. Buzz',
    heroImageName: 'vw-id-buzz',
    price: 8990000,
    sellerURL: 'https://www.volkswagen.is/is/bilar/id-buzz.html',
    acceleration: 10.2,
    capacity: 77,
    range: 423,
    evDatabaseURL: 'https://ev-database.org/car/1651/Volkswagen-ID-Buzz-Pro',
    drive: 'RWD',
    power: 150,
    timeToCharge10T080: 28,
  },
  {
    make: 'Volkswagen',
    model: 'ID.3',
    subModel: 'Pro',
    heroImageName: 'vw-id-3-01',
    price: 6790000,
    sellerURL: 'https://www.volkswagen.is/is/bilar/the-new-id3.html',
    acceleration: 7.4,
    capacity: 58,
    range: 425,
    evDatabaseURL: 'https://ev-database.org/car/1831/Volkswagen-ID3-Pro',
    drive: 'RWD',
    power: 150,
    timeToCharge10T080: 32,
  },
  {
    make: 'Volkswagen',
    model: 'ID.4',
    subModel: 'Pure',
    heroImageName: 'vw-id-4',
    price: 7690000,
    sellerURL: 'https://www.volkswagen.is/is/bilar/ID4.html',
    acceleration: 10.9,
    capacity: 52,
    range: 340,
    evDatabaseURL: 'https://ev-database.org/car/1489/Volkswagen-ID4-Pure',
    drive: 'RWD',
    power: 109,
    timeToCharge10T080: 33,
    discontinued: '2024-02-04',
  },
  {
    make: 'Volkswagen',
    model: 'ID.4',
    subModel: 'Pro',
    heroImageName: 'vw-id-4-alt',
    price: 8790000,
    sellerURL: 'https://www.volkswagen.is/is/bilar/ID4.html',
    acceleration: 10.4,
    capacity: 77,
    range: 511,
    evDatabaseURL: 'https://ev-database.org/car/1627/Volkswagen-ID4-Pro',
    drive: 'RWD',
    power: 128,
    timeToCharge10T080: 27,
    discontinued: '2024-02-04',
  },
  {
    make: 'Volkswagen',
    model: 'ID.4',
    subModel: 'Pro 4MOTION',
    heroImageName: 'vw-id-4-alt2',
    price: 8_990_000,
    sellerURL: 'https://www.volkswagen.is/is/bilar/ID4.html',
    acceleration: 6.6,
    capacity: 82,
    range: 517,
    evDatabaseURL:
      'https://ev-database.org/car/2029/Volkswagen-ID4-Pro-4MOTION',
    drive: 'AWD',
    power: 210,
    timeToCharge10T080: 28,
  },
  {
    make: 'Volkswagen',
    model: 'ID.4',
    subModel: 'GTX',
    heroImageName: 'vw-id-4-gtx',
    price: 9990000,
    sellerURL: 'https://www.volkswagen.is/is/bilar/ID4.html',
    acceleration: 6.3,
    capacity: 77,
    evDatabaseURL: 'https://ev-database.org/car/1828/Volkswagen-ID4-GTX',
    range: 500,
    drive: 'AWD',
    power: 220,
    timeToCharge10T080: 30,
    discontinued: '2024-02-04',
  },
  {
    make: 'Volkswagen',
    model: 'ID.5',
    subModel: 'Pro',
    heroImageName: 'vw-id-5',
    price: 8390000,
    sellerURL: 'https://www.volkswagen.is/is/bilar/id5.html',
    acceleration: 10.4,
    capacity: 77,
    range: 534,
    evDatabaseURL: 'https://ev-database.org/car/1912/Volkswagen-ID5-Pro',
    drive: 'RWD',
    power: 128,
    timeToCharge10T080: 27,
  },
  {
    make: 'Volkswagen',
    model: 'ID.5',
    subModel: 'GTX',
    heroImageName: 'vw-id-5-gtx',
    price: 9490000,
    sellerURL: 'https://www.volkswagen.is/is/bilar/id5.html',
    acceleration: 6.3,
    capacity: 77,
    evDatabaseURL: 'https://ev-database.org/car/1914/Volkswagen-ID5-GTX',
    range: 512,
    drive: 'AWD',
    power: 220,
    timeToCharge10T080: 30,
  },
  {
    make: 'Volkswagen',
    model: 'ID.7',
    subModel: 'Pro',
    heroImageName: 'vw-id-7',
    price: 9900000,
    sellerURL: 'https://www.volkswagen.is/is/bilar/id7.html',
    acceleration: 6.5,
    capacity: 82,
    evDatabaseURL: 'https://ev-database.org/car/1839/Volkswagen-ID7-Pro',
    range: 615,
    drive: 'RWD',
    power: 210,
    timeToCharge10T080: 28,
    expectedDelivery: 'Snemma 2024',
  },
  {
    make: 'Volkswagen',
    model: 'ID.7',
    subModel: 'Pro S',
    heroImageName: 'vw-id-7-alt',
    price: 11000000,
    sellerURL: 'https://www.volkswagen.is/is/bilar/id7.html',
    acceleration: 7.0,
    capacity: 91,
    evDatabaseURL: 'https://ev-database.org/car/1840/Volkswagen-ID7-Pro-S',
    range: 700,
    drive: 'RWD',
    power: 210,
    timeToCharge10T080: 27,
    expectedDelivery: '2024',
  },
  {
    make: 'Volvo',
    model: 'EC40',
    subModel: 'Recharge',
    heroImageName: 'volvo-c40',
    price: 9_990_000,
    sellerURL: 'https://www.volvocars.com/is/v/cars/c40-electric',
    acceleration: 7.3,
    capacity: 69,
    range: 436,
    evDatabaseURL: 'https://ev-database.org/car/2123/Volvo-EC40-Single-Motor',
    drive: 'RWD',
    power: 175,
    timeToCharge10T080: 34,
    discontinued: '2024-09-29',
  },
  {
    make: 'Volvo',
    model: 'EC40',
    subModel: 'Recharge Twin',
    heroImageName: 'volvo-c40',
    price: 9_890_000,
    sellerURL: 'https://www.volvocars.com/is/v/cars/c40-electric',
    acceleration: 4.7,
    capacity: 82,
    range: 551,
    evDatabaseURL: 'https://ev-database.org/car/2137/Volvo-EC40-Twin-Motor',
    drive: 'AWD',
    power: 300,
    timeToCharge10T080: 28,
  },
  {
    make: 'Volvo',
    model: 'EX40',
    subModel: 'Recharge',
    heroImageName: 'volvo-xc40-alt',
    price: 9_890_000,
    sellerURL: 'https://www.volvocars.com/is/v/cars/xc40-electric',
    acceleration: 7.4,
    capacity: 69,
    range: 424,
    evDatabaseURL: 'https://ev-database.org/car/2120/Volvo-EX40-Single-Motor',
    drive: 'RWD',
    power: 175,
    timeToCharge10T080: 34,
    discontinued: '2024-09-29',
  },
  {
    make: 'Volvo',
    model: 'EX40',
    subModel: 'Recharge Twin',
    heroImageName: 'volvo-xc40',
    price: 9_890_000,
    sellerURL: 'https://www.volvocars.com/is/v/cars/xc40-electric',
    acceleration: 4.8,
    capacity: 82,
    range: 536,
    evDatabaseURL: 'https://ev-database.org/car/2136/Volvo-EX40-Twin-Motor',
    drive: 'AWD',
    power: 300,
    timeToCharge10T080: 28,
  },
  {
    make: 'Volvo',
    model: 'EX30',
    subModel: 'Single Motor',
    heroImageName: 'volvo-ex30',
    price: 6_390_000,
    sellerURL: 'https://www.volvocars.com/is/cars/ex30-electric/',
    acceleration: 5.7,
    capacity: 51,
    range: 344,
    evDatabaseURL: 'https://ev-database.org/car/1909/Volvo-EX30-Single-Motor',
    drive: 'RWD',
    power: 200,
    timeToCharge10T080: 27,
  },
  {
    make: 'Volvo',
    model: 'EX30',
    subModel: 'Single Motor Extended Range',
    heroImageName: 'volvo-ex30-alt',
    price: 7_490_000,
    sellerURL: 'https://www.volvocars.com/is/cars/ex30-electric/',
    acceleration: 5.3,
    capacity: 69,
    range: 480,
    evDatabaseURL:
      'https://ev-database.org/car/1910/Volvo-EX30-Single-Motor-ER',
    drive: 'RWD',
    power: 200,
    timeToCharge10T080: 27,
  },
  {
    make: 'Volvo',
    model: 'EX30',
    subModel: 'Twin Motor Performance',
    heroImageName: 'volvo-ex30-alt2',
    price: 7_790_000,
    sellerURL: 'https://www.volvocars.com/is/cars/ex30-electric/',
    acceleration: 3.6,
    capacity: 69,
    range: 460,
    evDatabaseURL:
      'https://ev-database.org/car/1911/Volvo-EX30-Twin-Motor-Performance',
    drive: 'AWD',
    power: 315,
    timeToCharge10T080: 27,
  },
  {
    make: 'Volvo',
    model: 'EX90',
    subModel: 'Twin Motor',
    heroImageName: 'volvo-ex90',
    price: 16_490_000,
    sellerURL: 'https://www.volvocars.com/is/cars/ex90-electric/',
    acceleration: 5.9,
    capacity: 111,
    range: 614,
    evDatabaseURL: 'https://ev-database.org/car/1775/Volvo-EX90-Twin-Motor',
    drive: 'AWD',
    power: 300,
    timeToCharge10T080: 32,
    expectedDelivery: '2024',
  },
  {
    make: 'Volvo',
    model: 'EX90',
    subModel: 'Twin Motor Performance',
    heroImageName: 'volvo-ex90-alt',
    price: 17_290_000,
    sellerURL: 'https://www.volvocars.com/is/cars/ex90-electric/',
    acceleration: 4.9,
    capacity: 111,
    range: 614,
    evDatabaseURL:
      'https://ev-database.org/car/1776/Volvo-EX90-Twin-Motor-Performance',
    drive: 'AWD',
    power: 380,
    timeToCharge10T080: 32,
    expectedDelivery: '2024',
  },
  {
    make: 'XPENG',
    model: 'G6',
    subModel: 'RWD Standard Range',
    heroImageName: 'xpeng-g6',
    price: 6_890_000,
    sellerURL: 'https://www.xpeng.com/is/g6',
    acceleration: 6.9,
    capacity: 69,
    range: 435,
    evDatabaseURL:
      'https://ev-database.org/car/2181/XPENG-G6-RWD-Standard-Range',
    drive: 'RWD',
    power: 190,
    timeToCharge10T080: 21,
    expectedDelivery: '2024',
  },
  {
    make: 'XPENG',
    model: 'G6',
    subModel: 'RWD Long Range',
    heroImageName: 'xpeng-g6-alt',
    price: 7_490_000,
    sellerURL: 'https://www.xpeng.com/is/g6',
    acceleration: 6.7,
    capacity: 92,
    range: 570,
    evDatabaseURL: 'https://ev-database.org/car/2182/XPENG-G6-RWD-Long-Range',
    drive: 'RWD',
    power: 210,
    timeToCharge10T080: 21,
    expectedDelivery: '2024',
  },
  {
    make: 'XPENG',
    model: 'G6',
    subModel: 'AWD Performance',
    heroImageName: 'xpeng-g6-alt2',
    price: 7_890_000,
    sellerURL: 'https://www.xpeng.com/is/g6',
    acceleration: 4.1,
    capacity: 92,
    range: 550,
    evDatabaseURL: 'https://ev-database.org/car/2183/XPENG-G6-AWD-Performance',
    drive: 'AWD',
    power: 350,
    timeToCharge10T080: 21,
    expectedDelivery: '2024',
  },
]

export default newCars
