import { UsedCarModel } from '../types'

const usedCarModels: Array<UsedCarModel> = [
  {
    id: 'audi-etron-50',
    make: 'Audi',
    model: 'e-tron 50',
    acceleration: 7,
    capacity: 71,
    range: 328,
    evDatabaseURL: 'https://ev-database.org/car/1209/Audi-e-tron-50-quattro',
  },
  {
    id: 'audi-etron-55',
    make: 'Audi',
    model: 'e-tron 55',
    acceleration: 5.7,
    capacity: 95,
    range: 417,
    evDatabaseURL: 'https://ev-database.org/car/1092/Audi-e-tron',
  },
  {
    make: 'Audi',
    model: 'e-tron Sportback 50',
    id: 'e-tron-50-sportback',
    sellerURL:
      'http://www.audi.is/is/web/is/models/tron/audi-e-tron-sportback-2021.html',
    acceleration: 6.8,
    capacity: 71,
    range: 350,
    evDatabaseURL:
      'https://ev-database.org/car/1661/Audi-e-tron-Sportback-50-quattro',
  },
  {
    make: 'Audi',
    model: 'e-tron Sportback 55',
    id: 'e-tron-55-sportback',
    price: 11590000,
    sellerURL:
      'http://www.audi.is/is/web/is/models/tron/audi-e-tron-sportback-2021.html',
    acceleration: 5.7,
    capacity: 95,
    range: 446,
    evDatabaseURL:
      'https://ev-database.org/car/1107/Audi-e-tron-Sportback-55-quattro',
  },
  {
    id: 'mitsubishi-imiev',
    make: 'Mitsubishi',
    model: 'i-MiEV',
    acceleration: 15.9,
    capacity: 16,
    rangeNEDC: 160,
    evDatabaseURL: 'https://ev-database.org/car/1096/Mitsubishi-iMiEV',
  },
  {
    id: 'renault-kangoo-ze',
    make: 'Renault',
    model: 'Kangoo Z.E.',
    acceleration: 22.4,
    capacity: 22.0,
    rangeNEDC: 170,
  },
  {
    id: 'nissan-leaf-24',
    make: 'Nissan',
    model: 'Leaf',
    acceleration: 11.5,
    capacity: 24.0,
    rangeNEDC: 199,
    evDatabaseURL: 'https://ev-database.org/car/1019/Nissan-Leaf-24-kWh',
  },
  {
    id: 'nissan-leaf-30',
    make: 'Nissan',
    model: 'Leaf',
    acceleration: 11.5,
    capacity: 30.0,
    rangeNEDC: 250,
    evDatabaseURL: 'https://ev-database.org/car/1020/Nissan-Leaf-30-kWh',
  },
  {
    id: 'nissan-leaf-40',
    make: 'Nissan',
    model: 'Leaf',
    acceleration: 7.9,
    capacity: 40.0,
    range: 270,
    evDatabaseURL: 'https://ev-database.org/car/1106/Nissan-Leaf',
    price: 4390000,
    sellerURL: 'https://www.nissan.is/vehicles/new-vehicles/leaf.html',
  },
  {
    id: 'nissan-leaf-e+',
    make: 'Nissan',
    model: 'Leaf e+',
    acceleration: 7.3,
    capacity: 62.0,
    range: 385,
    evDatabaseURL: 'https://ev-database.org/car/1144/Nissan-Leaf-eplus',
    price: 4390000,
    sellerURL: 'https://www.nissan.is/vehicles/new-vehicles/leaf.html',
  },
  {
    id: 'nissan-e-nv200-24',
    make: 'Nissan',
    model: 'e-NV200 Evalia',
    acceleration: 14,
    capacity: 24.0,
    rangeNEDC: 170,
    evDatabaseURL: 'https://ev-database.org/car/1021/Nissan-e-NV200-Evalia',
  },
  {
    id: 'nissan-e-nv200-40',
    make: 'Nissan',
    model: 'e-NV200 Evalia',
    acceleration: 14,
    capacity: 40.0,
    rangeNEDC: 280,
    range: 200,
    evDatabaseURL: 'https://ev-database.org/car/1117/Nissan-e-NV200-Evalia',
  },
  {
    id: 'vw-eup-18',
    make: 'Volkswagen',
    model: 'e-Up!',
    acceleration: 12.4,
    capacity: 18.7,
    range: 133,
    rangeNEDC: 160,
    evDatabaseURL: 'https://ev-database.org/car/1081/Volkswagen-e-Up',
  },
  {
    id: 'vw-eup-37',
    make: 'Volkswagen',
    model: 'e-Up!',
    acceleration: 11.9,
    capacity: 36.8,
    range: 260,
    evDatabaseURL: 'https://ev-database.org/car/1189/Volkswagen-e-Up',
  },
  {
    id: 'volkswagen-egolf-24',
    make: 'Volkswagen',
    model: 'e-Golf',
    acceleration: 10.4,
    capacity: 24.2,
    rangeNEDC: 190,
    evDatabaseURL: 'https://ev-database.org/car/1040/Volkswagen-e-Golf',
  },
  {
    id: 'volkswagen-egolf-35',
    make: 'Volkswagen',
    model: 'e-Golf',
    acceleration: 9.6,
    capacity: 35.8,
    range: 230,
    evDatabaseURL: 'https://ev-database.org/car/1087/Volkswagen-e-Golf',
  },
  {
    id: 'vw-id-3-first',
    make: 'Volkswagen',
    model: 'ID.3 1.st edition',
    sellerURL: 'https://www.volkswagen.is/is/bilar/id3.html',
    acceleration: 7.3,
    capacity: 58,
    range: 420,
    evDatabaseURL: 'https://ev-database.org/car/1300/Volkswagen-ID3-1st',
  },
  {
    id: 'kia-soul-ev-2014',
    make: 'Kia',
    model: 'Soul EV',
    acceleration: 11.2,
    capacity: 30.5,
    rangeNEDC: 212,
    evDatabaseURL: 'https://ev-database.org/car/1012/Kia-Soul-EV',
  },
  {
    id: 'kia-soul-ev-2017',
    make: 'Kia',
    model: 'Soul EV',
    acceleration: 11.2,
    capacity: 33,
    rangeNEDC: 250,
    evDatabaseURL: 'https://ev-database.org/car/1122/Kia-Soul-EV',
  },
  {
    id: 'kia-e-soul-39kwh',
    make: 'Kia',
    model: 'e-Soul',
    price: 5490777,
    sellerURL:
      'https://issuu.com/askja/docs/kia_verdlisti_19012018/20?e=6076164/57534189',
    acceleration: 9.6,
    capacity: 39,
    range: 277,
    evDatabaseURL: 'https://ev-database.org/car/1169/Kia-e-Soul-39-kWh',
  },
  {
    id: 'kia-e-soul-64kwh',
    make: 'Kia',
    model: 'e-Soul',
    price: 6290777,
    sellerURL: 'https://www.kia.com/is/nyir-bilar/e-soul/upplifdu/',
    acceleration: 7.9,
    capacity: 64,
    range: 452,
    evDatabaseURL: 'https://ev-database.org/car/1154/Kia-e-Soul-64-kWh',
  },
  {
    id: 'kia-e-niro-39',
    make: 'Kia',
    model: 'e-Niro',
    acceleration: 9.8,
    capacity: 39,
    range: 289,
    evDatabaseURL: 'https://ev-database.org/car/1137/Kia-e-Niro-39-kWh',
  },
  {
    id: 'kia-e-niro-64',
    make: 'Kia',
    model: 'e-Niro',
    acceleration: 7.8,
    capacity: 64,
    range: 455,
    evDatabaseURL: 'https://ev-database.org/car/1125/Kia-e-Niro-64-kWh',
  },
  {
    make: 'Kia',
    model: 'EV6',
    id: 'kia-ev6-sr-rwd',
    price: 7990777,
    sellerURL: 'https://www.kia.com/is/nyir-bilar/ev6/upplifdu/',
    acceleration: 8.5,
    capacity: 58,
    range: 400,
    evDatabaseURL:
      'https://ev-database.org/car/1480/Kia-EV6-Standard-Range-2WD',
  },
  {
    make: 'Kia',
    model: 'EV6',
    id: 'kia-ev6-lr-rwd',
    price: 8690777,
    sellerURL: 'https://www.kia.com/is/nyir-bilar/ev6/upplifdu/',
    acceleration: 7.3,
    capacity: 77.4,
    range: 528,
    evDatabaseURL: 'https://ev-database.org/car/1481/Kia-EV6-Long-Range-2WD',
  },
  {
    make: 'Kia',
    model: 'EV6',
    id: 'kia-ev6-lr-awd',
    price: 9390777,
    sellerURL: 'https://www.kia.com/is/nyir-bilar/ev6/upplifdu/',
    acceleration: 5.2,
    capacity: 77.4,
    range: 506,
    evDatabaseURL: 'https://ev-database.org/car/1482/Kia-EV6-Long-Range-AWD',
  },
  {
    id: 'renault-zoe-ze20',
    make: 'Renault',
    model: 'Zoe',
    acceleration: 13.5,
    capacity: 25,
    rangeNEDC: 210,
    evDatabaseURL: 'https://ev-database.org/car/1026/Renault-Zoe-Q210',
  },
  {
    id: 'renault-zoe-ze40',
    make: 'Renault',
    model: 'Zoe',
    acceleration: 11.4,
    capacity: 44.1,
    range: 300,
    evDatabaseURL: 'https://ev-database.org/car/1128/Renault-Zoe-R110',
  },
  {
    id: 'renault-zoe-ze50',
    make: 'Renault',
    model: 'Zoe',
    acceleration: 11.4,
    capacity: 52,
    range: 395,
    evDatabaseURL: 'https://ev-database.org/car/1164/Renault-Zoe-ZE50-R110',
  },
  {
    id: 'renault-kangoo-maxi-ze-33',
    make: 'Renault',
    model: 'Kangoo Maxi Z.E.',
    acceleration: 22.4,
    capacity: 33,
    rangeNEDC: 270,
    evDatabaseURL: 'https://ev-database.org/car/1101/Renault-Kangoo-Maxi-ZE-33',
  },
  {
    id: 'bmw-i3-60',
    make: 'BMW',
    model: 'i3',
    acceleration: 7.2,
    capacity: 21.6,
    rangeNEDC: 190,
    evDatabaseURL: 'https://ev-database.org/car/1004/BMW-i3-60-Ah',
  },
  {
    id: 'bmw-i3-94',
    make: 'BMW',
    model: 'i3',
    acceleration: 7.3,
    capacity: 33.2,
    rangeNEDC: 312,
    evDatabaseURL: 'https://ev-database.org/car/1068/BMW-i3-94-Ah',
  },
  {
    id: 'bmw-i3-120',
    make: 'BMW',
    model: 'i3',
    acceleration: 7.3,
    capacity: 42.8,
    range: 310,
    evDatabaseURL: 'https://ev-database.org/car/1145/BMW-i3-120-Ah',
  },
  {
    make: 'BMW',
    model: 'iX xDrive 40',
    id: 'bmw-ix-40',
    price: 13990000,
    sellerURL: 'https://www.bmw.is/is/all-models/bmw-i/bmw-ix/2021/bmw-ix.html',
    acceleration: 6.1,
    capacity: 75,
    range: 425,
    evDatabaseURL: 'https://ev-database.org/car/1472/BMW-iX-xDrive-40',
  },
  {
    id: 'hyundai-ioniq',
    make: 'Hyundai',
    model: 'IONIQ Electric',
    acceleration: 9.9,
    capacity: 30.5,
    rangeNEDC: 280,
    evDatabaseURL: 'https://ev-database.org/car/1057/Hyundai-IONIQ-Electric',
  },
  {
    id: 'hyundai-ioniq-2020',
    make: 'Hyundai',
    model: 'IONIQ Electric',
    price: 4790000,
    sellerURL: 'https://www.hyundai.is/nyir/ioniq/yfirlit',
    acceleration: 9.7,
    capacity: 38.3,
    range: 311,
    evDatabaseURL: 'https://ev-database.org/car/1165/Hyundai-IONIQ-Electric',
  },
  {
    id: 'hyundai-kona-39',
    make: 'Hyundai',
    model: 'Kona Electric',
    acceleration: 9.7,
    capacity: 42.0,
    range: 280,
    evDatabaseURL:
      'https://ev-database.org/car/1129/Hyundai-Kona-Electric-39-kWh',
  },
  {
    id: 'hyundai-kona-64',
    make: 'Hyundai',
    model: 'Kona Electric',
    acceleration: 7.6,
    capacity: 67.1,
    range: 449,
    evDatabaseURL:
      'https://ev-database.org/car/1126/Hyundai-Kona-Electric-64-kWh',
  },
  {
    id: 'hyundai-kona-39-2022',
    make: 'Hyundai',
    model: 'Kona Electric',
    acceleration: 9.9,
    capacity: 39,
    range: 305,
    evDatabaseURL:
      'https://ev-database.org/car/1422/Hyundai-Kona-Electric-39-kWh',
  },
  {
    id: 'hyundai-kona-64-2022',
    make: 'Hyundai',
    model: 'Kona Electric',
    acceleration: 7.6,
    capacity: 64,
    range: 484,
    evDatabaseURL:
      'https://ev-database.org/car/1423/Hyundai-Kona-Electric-64-kW',
  },
  {
    id: 'tesla-model-s-60',
    make: 'Tesla',
    model: 'Model S 60',
    acceleration: 5.8,
    capacity: 60,
    rangeNEDC: 375,
    evDatabaseURL: 'https://ev-database.org/car/1072/Tesla-Model-S-60',
  },
  {
    id: 'tesla-model-s-60d',
    make: 'Tesla',
    model: 'Model S 60D',
    acceleration: 5.2,
    capacity: 60,
    rangeNEDC: 375,
    evDatabaseURL: 'https://ev-database.org/car/1073/Tesla-Model-S-60D',
  },
  {
    id: 'tesla-model-s-70d',
    make: 'Tesla',
    model: 'Model S 70D',
    acceleration: 5.4,
    capacity: 70,
    rangeNEDC: 442,
    evDatabaseURL: 'https://ev-database.org/car/1033/Tesla-Model-S-70D',
  },
  {
    id: 'tesla-model-s-75',
    make: 'Tesla',
    model: 'Model S 75',
    acceleration: 5.4,
    capacity: 75,
    rangeNEDC: 480,
    evDatabaseURL: 'https://ev-database.org/car/1071/Tesla-Model-S-75',
  },
  {
    id: 'tesla-model-s-85',
    make: 'Tesla',
    model: 'Model S 85',
    acceleration: 5.6,
    capacity: 85,
    rangeNEDC: 502,
    evDatabaseURL: 'https://ev-database.org/car/1031/Tesla-Model-S-85',
  },
  {
    id: 'tesla-model-s-85d',
    make: 'Tesla',
    model: 'Model S 85D',
    acceleration: 4,
    capacity: 85,
    rangeNEDC: 528,
    evDatabaseURL: 'https://ev-database.org/car/1034/Tesla-Model-S-85D',
  },
  {
    id: 'tesla-model-s-p85',
    make: 'Tesla',
    model: 'Model S P85',
    acceleration: 4.4,
    capacity: 85,
    rangeNEDC: 502,
  },
  {
    id: 'tesla-model-s-p85d',
    make: 'Tesla',
    model: 'Model S P85D',
    acceleration: 3.3,
    capacity: 85,
    rangeNEDC: 491,
    evDatabaseURL: 'https://ev-database.org/car/1036/Tesla-Model-S-P85D',
  },
  {
    id: 'tesla-model-s-90d',
    make: 'Tesla',
    model: 'Model S 90D',
    acceleration: 4.4,
    capacity: 90,
    rangeNEDC: 557,
    evDatabaseURL: 'https://ev-database.org/car/1063/Tesla-Model-S-90D',
  },
  {
    id: 'tesla-model-s-100d',
    make: 'Tesla',
    model: 'Model S 100D',
    acceleration: 4.3,
    capacity: 100,
    rangeNEDC: 632,
    evDatabaseURL: 'https://ev-database.org/car/1088/Tesla-Model-S-100D',
  },
  {
    id: 'tesla-model-s-p100d',
    make: 'Tesla',
    model: 'Model S P100D',
    acceleration: 2.7,
    capacity: 100,
    rangeNEDC: 613,
    evDatabaseURL: 'https://ev-database.org/car/1075/Tesla-Model-S-P100D',
  },
  {
    id: 'tesla-model-x-90d',
    make: 'Tesla',
    model: 'Model X 90D',
    acceleration: 5,
    capacity: 90,
    rangeNEDC: 489,
    evDatabaseURL: 'https://ev-database.org/car/1053/Tesla-Model-X-90D',
  },
  {
    id: 'tesla-model-x-p90d',
    make: 'Tesla',
    model: 'Model X P90D',
    acceleration: 4,
    capacity: 90,
    rangeNEDC: 467,
    evDatabaseURL: 'https://ev-database.org/car/1054/Tesla-Model-X-P90D',
  },
  {
    id: 'tesla-model-3-srplus',
    make: 'Tesla',
    model: 'Model 3 Standard Range Plus',
    price: 5683335,
    sellerURL: 'https://www.tesla.com/is_IS/model3/design',
    acceleration: 5.6,
    capacity: 55,
    range: 409,
    evDatabaseURL:
      'https://ev-database.org/car/1177/Tesla-Model-3-Standard-Range-Plus',
  },
  {
    id: 'tesla-model-3-long-range',
    make: 'Tesla',
    model: 'Model 3 Long Range',
    acceleration: 4.6,
    capacity: 79,
    range: 560,
    evDatabaseURL:
      'https://ev-database.org/car/1138/Tesla-Model-3-Long-Range-Dual-Motor',
  },
  {
    id: 'tesla-model-3-performance',
    make: 'Tesla',
    model: 'Model 3 Performance',
    acceleration: 3.4,
    capacity: 75,
    range: 530,
    evDatabaseURL:
      'https://ev-database.org/car/1139/Tesla-Model-3-Long-Range-Performance',
  },
  {
    make: 'Tesla',
    model: 'Model Y Long Range',
    id: 'tesla-model-y-long-range',
    price: 7904579,
    sellerURL: 'https://www.tesla.com/is_is/modely/design',
    acceleration: 5.0,
    capacity: 75,
    range: 567,
    evDatabaseURL:
      'https://ev-database.org/car/1619/Tesla-Model-Y-Long-Range-Dual-Motor',
  },
  {
    make: 'Tesla',
    model: 'Model Y Performance',
    id: 'tesla-model-y-performance',
    price: 9020591,
    sellerURL: 'https://www.tesla.com/is_is/modely/design',
    acceleration: 3.7,
    capacity: 75,
    range: 514,
    evDatabaseURL: 'https://ev-database.org/car/1183/Tesla-Model-Y-Performance',
  },
  {
    make: 'Fiat',
    model: '500e',
    id: 'fiat-500e',
    price: 5650000,
    sellerURL: 'https://www.fiat.is/model/500e-la-prima/',
    acceleration: 9.0,
    capacity: 42,
    range: 320,
    evDatabaseURL:
      'https://ev-database.org/car/1285/Fiat-500e-Hatchback-42-kWh',
  },
  {
    id: 'ford-focus-electric-23',
    make: 'Ford',
    model: 'Focus Electric',
    acceleration: 11.4,
    capacity: 23,
    rangeNEDC: 162,
    evDatabaseURL: 'https://ev-database.org/car/1010/Ford-Focus-Electric',
  },
  {
    id: 'ford-focus-electric-2017',
    make: 'Ford',
    model: 'Focus Electric',
    acceleration: 11.4,
    capacity: 33.5,
    rangeNEDC: 225,
  },
  {
    make: 'Ford',
    model: 'Mustang Mach-E SR AWD',
    id: 'ford-mach-e-sr-awd',
    price: 9590000,
    sellerURL: 'https://www.ford.is/is/nyir-bilar/Mustang-Mach-E',
    acceleration: 5.6,
    capacity: 75,
    range: 400,
    evDatabaseURL:
      'https://ev-database.org/car/1244/Ford-Mustang-Mach-E-SR-AWD',
  },
  {
    make: 'Ford',
    model: 'Mustang Mach-E LR AWD',
    id: 'ford-mach-e-lr-awd',
    price: 10590000,
    sellerURL: 'https://www.ford.is/is/nyir-bilar/Mustang-Mach-E',
    acceleration: 5.1,
    capacity: 98,
    range: 550,
    evDatabaseURL:
      'https://ev-database.org/car/1245/Ford-Mustang-Mach-E-ER-AWD',
  },
  {
    id: 'jaguar-i-pace',
    make: 'Jaguar',
    model: 'I-PACE',
    acceleration: 4.8,
    capacity: 90,
    range: 470,
    evDatabaseURL: 'https://ev-database.org/car/1097/Jaguar-I-Pace',
  },
  {
    id: 'jaguar-i-pace-ev-320',
    make: 'Jaguar',
    model: 'I-PACE',
    acceleration: 6.4,
    capacity: 90,
    range: 470,
    evDatabaseURL: 'https://ev-database.org/car/1307/Jaguar-I-Pace-EV320',
  },
  {
    make: 'Mazda',
    model: 'MX-30',
    id: 'mazda-mx-30',
    price: 4470000,
    sellerURL: 'https://www.mazda.is/is/nyir-bilar/mazda-mx-30',
    acceleration: 9.0,
    capacity: 35.5,
    range: 200,
    evDatabaseURL: 'https://ev-database.org/car/1680/Mazda-MX-30',
  },
  {
    id: 'mercedes-b-250e',
    make: 'Mercedes-Benz',
    model: 'B 250e',
    acceleration: 7.9,
    capacity: 28,
    rangeNEDC: 200,
    evDatabaseURL: 'https://ev-database.org/car/1013/Mercedes-B-250e',
  },
  {
    make: 'Mercedes-Benz',
    model: 'EQA SUV',
    id: 'mercedes-eqa-250',
    price: 7990000,
    sellerURL:
      'https://www.mercedes-benz.is/passengercars/mercedes-benz-cars/models/eqa/',
    acceleration: 8.9,
    capacity: 66.5,
    range: 426,
    evDatabaseURL: 'https://ev-database.org/car/1147/Mercedes-EQA-250',
  },
  {
    make: 'Mercedes-Benz',
    model: 'EQA SUV',
    id: 'mercedes-eqa-300-4matic',
    price: 8490000,
    sellerURL:
      'https://www.mercedes-benz.is/passengercars/mercedes-benz-cars/models/eqa/',
    acceleration: 6.9,
    capacity: 66.5,
    range: 423,
    evDatabaseURL: 'https://ev-database.org/car/1495/Mercedes-EQA-300-4MATIC',
  },
  {
    make: 'Mercedes-Benz',
    model: 'EQA SUV',
    id: 'mercedes-eqa-350-4matic',
    price: 9190000,
    sellerURL:
      'https://www.mercedes-benz.is/passengercars/mercedes-benz-cars/models/eqa/',
    acceleration: 5.8,
    capacity: 66.5,
    range: 423,
    evDatabaseURL: 'https://ev-database.org/car/1496/Mercedes-EQA-350-4MATIC',
  },
  {
    make: 'Mercedes-Benz',
    model: 'EQB SUV',
    id: 'mercedes-eqb-250',
    price: 8490000,
    sellerURL:
      'https://www.mercedes-benz.is/passengercars/mercedes-benz-cars/models/eqb/',
    acceleration: 9.2,
    capacity: 66.5,
    range: 474,
    evDatabaseURL: 'https://ev-database.org/car/1664/Mercedes-EQB-250',
  },
  {
    make: 'Mercedes-Benz',
    model: 'EQB SUV',
    id: 'mercedes-eqb-300-4matic',
    price: 8990000,
    sellerURL:
      'https://www.mercedes-benz.is/passengercars/mercedes-benz-cars/models/eqb/',
    acceleration: 8.0,
    capacity: 66.5,
    range: 419,
    evDatabaseURL: 'https://ev-database.org/car/1559/Mercedes-EQB-300-4MATIC',
  },
  {
    make: 'Mercedes-Benz',
    model: 'EQB SUV',
    id: 'mercedes-eqb-350-4matic',
    price: 9690000,
    sellerURL:
      'https://www.mercedes-benz.is/passengercars/mercedes-benz-cars/models/eqb/',
    acceleration: 6.2,
    capacity: 66.5,
    range: 419,
    evDatabaseURL: 'https://ev-database.org/car/1493/Mercedes-EQB-350-4MATIC',
  },
  {
    id: 'mercedes-eqc',
    make: 'Mercedes-Benz',
    model: 'EQC',
    acceleration: 5.1,
    capacity: 80,
    range: 417,
    evDatabaseURL: 'https://ev-database.org/car/1135/Mercedes-EQC-400-4MATIC',
  },
  {
    id: 'mercedes-e-vito-tourer',
    make: 'Mercedes-Benz',
    model: 'eVito Tourer',
    acceleration: 12.1,
    capacity: 41,
    range: 150,
  },
  {
    id: 'mercedes-eqv',
    make: 'Mercedes-Benz',
    model: 'EQV',
    acceleration: 12.1,
    capacity: 90,
    range: 363,
  },
  {
    id: 'open-ampera-e',
    make: 'Opel',
    model: 'Ampera-e',
    price: 4990000,
    sellerURL: 'https://ampera-e.opel.is/',
    acceleration: 7.3,
    capacity: 60,
    range: 380,
    evDatabaseURL: 'https://ev-database.org/car/1051/Opel-Ampera-e',
  },
  {
    id: 'chevrolet-bolt',
    make: 'Chevrolet',
    model: 'Bolt',
    price: 4990000,
    sellerURL: 'https://ampera-e.opel.is/',
    acceleration: 7.3,
    capacity: 60,
    range: 380,
    evDatabaseURL: 'https://ev-database.org/car/1051/Opel-Ampera-e',
  },
  {
    id: 'mg-zs-ev',
    make: 'MG',
    model: 'ZS EV',
    price: 3990000,
    sellerURL: 'https://www.bl.is/nyir/mg/zsev/',
    acceleration: 8.2,
    capacity: 44.5,
    range: 263,
    evDatabaseURL: 'https://ev-database.org/car/1201/MG-ZS-EV',
  },
  {
    make: 'MG',
    model: 'ZS Standard Range',
    id: 'mg-zs-ev-2022',
    price: 4690000,
    sellerURL: 'https://mgmotor.eu/is-IS/model/zs-ev',
    acceleration: 8.6,
    capacity: 50.3,
    range: 320,
    evDatabaseURL: 'https://ev-database.org/car/1540/MG-ZS-EV-Standard-Range',
  },
  {
    make: 'MG',
    model: 'ZS Long Range',
    id: 'mg-zs-ev-2022-lr',
    price: 5990000,
    sellerURL: 'https://mgmotor.eu/is-IS/model/zs-ev',
    acceleration: 8.4,
    capacity: 73,
    range: 440,
    evDatabaseURL: 'https://ev-database.org/car/1541/MG-ZS-EV-Long-Range',
  },
  {
    make: 'Honda',
    model: 'e',
    id: 'honda-e',
    price: 4290000,
    sellerURL: 'https://www.honda.is/voruflokkar/bilar/honda-e/',
    acceleration: 9.5,
    capacity: 32.0,
    range: 220,
    evDatabaseURL: 'https://ev-database.org/car/1171/Honda-e',
  },
  {
    make: 'Honda',
    model: 'e Advance',
    id: 'honda-e-advance',
    price: 4690000,
    sellerURL: 'https://www.honda.is/voruflokkar/bilar/honda-e/',
    acceleration: 8.3,
    capacity: 32.0,
    range: 220,
    evDatabaseURL: 'https://ev-database.org/car/1233/Honda-e-Advance',
  },
  {
    make: 'Mini Cooper',
    model: 'SE',
    id: 'mini-cooper-se',
    price: 4790000,
    sellerURL: 'https://www.mini.is/is_IS/home/range/electric.html',
    acceleration: 7.3,
    capacity: 28.9,
    range: 232,
    evDatabaseURL: 'https://ev-database.org/car/1163/Mini-Cooper-SE',
  },
  {
    make: 'Peugeot',
    model: 'e-208',
    id: 'peugeot-e-208',
    price: 4090000,
    sellerURL:
      'https://www.peugeotisland.is/nyir-bilar/velja-bil/glaenyr-peugeot-e-208/',
    acceleration: 8.1,
    capacity: 50,
    range: 340,
    evDatabaseURL: 'https://ev-database.org/car/1168/Peugeot-e-208',
  },
  {
    make: 'Peugeot',
    model: 'e-2008',
    id: 'peugeot-e-2008',
    price: 4490000,
    sellerURL:
      'https://www.peugeotisland.is/nyir-bilar/velja-bil/glaenyr-peugeot-e-2008/',
    acceleration: 8.5,
    capacity: 50,
    range: 320,
    evDatabaseURL: 'https://ev-database.org/car/1206/Peugeot-e-2008-SUV',
  },
  {
    make: 'Lexus',
    model: 'UX 300e',
    id: 'lexus-ux-300e',
    price: 8490000,
    sellerURL: 'https://www.lexus.is/car-models/ux-300e/',
    acceleration: 7.5,
    capacity: 50,
    range: 315,
    evDatabaseURL: 'https://ev-database.org/car/1251/Lexus-UX-300e',
  },
  {
    id: 'skoda-enyaq-iv-60',
    make: 'Skoda',
    model: 'Enyaq iV 60',
    price: 5790000,
    sellerURL: 'https://www.skoda.is/models/enyaq/enyaq',
    acceleration: 8.7,
    capacity: 58,
    range: 412,
    evDatabaseURL: 'https://ev-database.org/car/1279/Skoda-Enyaq-iV-60',
  },
  {
    id: 'skoda-enyaq-iv-80',
    make: 'Skoda',
    model: 'Enyaq iV 80',
    price: 6490000,
    sellerURL: 'https://www.skoda.is/models/enyaq/enyaq',
    acceleration: 8.5,
    capacity: 77,
    range: 536,
    evDatabaseURL: 'https://ev-database.org/car/1280/Skoda-Enyaq-iV-80',
  },
  {
    id: 'skoda-enyaq-iv-80x',
    make: 'Skoda',
    model: 'Enyaq iV 80X',
    price: 6790000,
    sellerURL: 'https://www.skoda.is/models/enyaq/enyaq',
    acceleration: 6.9,
    capacity: 77,
    range: 496,
    evDatabaseURL: 'https://ev-database.org/car/1281/Skoda-Enyaq-iV-80X',
  },
  {
    make: 'Opel',
    model: 'Corsa-e',
    id: 'opel-corsa-e',
    price: 3990000,
    sellerURL: 'https://www.opel.is/cars/corsa-models/corsa-e/overview.html',
    acceleration: 8.1,
    capacity: 50,
    range: 330,
    evDatabaseURL: 'https://ev-database.org/car/1192/Opel-Corsa-e',
  },
  {
    id: 'polestar-2srsm',
    make: 'Polestar',
    model: '2',
    price: 6840000,
    sellerURL: 'https://www.polestar.com/en-is/polestar-2/',
    acceleration: 7.4,
    capacity: 69,
    range: 440,
    evDatabaseURL:
      'https://ev-database.org/car/1654/Polestar-2-Standard-Range-Single-Motor',
  },
  {
    id: 'polestar-2-lrsm',
    make: 'Polestar',
    model: '2',
    price: 7340000,
    sellerURL: 'https://www.polestar.com/en-is/polestar-2/',
    acceleration: 7.4,
    capacity: 78,
    range: 542,
    evDatabaseURL:
      'https://ev-database.org/car/1487/Polestar-2-Long-Range-Single-Motor',
  },
  {
    id: 'polestar-2-lrdm',
    make: 'Polestar',
    model: '2',
    price: 7940000,
    sellerURL: 'https://www.polestar.com/en-is/polestar-2/',
    acceleration: 4.7,
    capacity: 78,
    range: 482,
    evDatabaseURL:
      'https://ev-database.org/car/1488/Polestar-2-Long-Range-Dual-Motor',
  },
  {
    id: 'volvo-xc40-recharge-twin',
    make: 'Volvo',
    model: 'XC40',
    price: 8397200,
    sellerURL: 'https://www.volvocars.com/is/v/cars/xc40-electric',
    acceleration: 4.9,
    capacity: 78,
    range: 437,
    evDatabaseURL:
      'https://ev-database.org/car/1593/Volvo-XC40-Recharge-Twin-Pure-Electric',
  },
  {
    id: 'citroen-ec4',
    make: 'Citroën',
    model: 'ë-C4',
    price: 5590000,
    sellerURL: 'https://www.citroen.is/bill/citroen-e-c4-rafbill/',
    acceleration: 9.7,
    capacity: 50,
    range: 350,
    evDatabaseURL: 'https://ev-database.org/car/1286/Citroen-e-C4',
  },
  {
    id: 'opel-mokka-e',
    make: 'Opel',
    model: 'Mokka-e',
    price: 5420000,
    sellerURL:
      'https://www.opelisland.is/cars/mokka-models/mokka-e/Yfirsyn.html',
    acceleration: 8.5,
    capacity: 50,
    range: 322,
    evDatabaseURL: 'https://ev-database.org/car/1278/Opel-Mokka-e',
  },
  {
    id: 'mg-marvel-r',
    make: 'MG',
    model: 'Marvel R',
    price: 7299000,
    sellerURL: 'https://mgmotor.eu/is-IS/model/marvel-r',
    acceleration: 7.9,
    capacity: 70,
    range: 402,
    evDatabaseURL: 'https://ev-database.org/car/1524/MG-Marvel-R',
  },
  {
    id: 'mg-marvel-r-performance',
    make: 'MG',
    model: 'Marvel R Performance',
    price: 7999000,
    sellerURL: 'https://mgmotor.eu/is-IS/model/marvel-r',
    acceleration: 4.9,
    capacity: 70,
    range: 370,
    evDatabaseURL: 'https://ev-database.org/car/1475/MG-Marvel-R-Performance',
  },
]

export default usedCarModels
